
# GPTQ full-quant notebook — GSM8K + ARC-Challenge only

This notebook does exactly three experiment steps for **Qwen2-1.5B full GPTQ quantization**:

1. quantize and save the model artifact
2. evaluate on **GSM8K**
3. evaluate on **ARC-Challenge**

It also keeps a compact experiment summary with the table-style metrics you wanted for the **full quant** row:

- Variant
- Compression
- Model Size (GB)
- Peak VRAM (GB)
- Bits/Param
- GSM8K Accuracy
- ARC Accuracy

The dataset settings are kept aligned with the earlier notebook:

- **GSM8K:** 8-shot, 300 samples, max_new_tokens=256
- **ARC-Challenge:** 500 samples, max_new_tokens=5

In [ ]:
# Colab / notebook setup
!pip install -U pip setuptools wheel
!pip install -U gptqmodel
!pip install -q torch transformers accelerate datasets pandas pyarrow safetensors tqdm

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (75.2.0)
Collecting setuptools
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from wheel) (26.0)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 77.3 MB/s eta 0:00:00
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 73.0 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Successfully installed pip-26.0.1 setuptools-82.0.1

Collecting gptqmodel
  Downloading gptqmodel-5.7.0.tar.gz (668 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.4/668.4 kB 33.5 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate>=1.10.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.12.0)
Collecting numpy==2.2.6 (from gptqmodel)
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: torch>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (2.10.0+cu128)
Requirement already satisfied: safetensors>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.7.0)
Requirement already satisfied: transformers>=4.57.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (5.0.0)
Requirement already satisfied: threadpoolctl>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (3.6.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (26.0)
Collecting device-smi>=0.5.3 (from gptqmodel)
  Downloading device_smi-0.5.3.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf>=6.32.0 (from gptqmodel)
  Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: pillow>=11.3.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (11.3.0)
Collecting hf_transfer>=0.1.9 (from gptqmodel)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: huggingface_hub>=0.34.4 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.5.0)
Collecting tokenicer>=0.0.6 (from gptqmodel)
  Downloading tokenicer-0.0.8.tar.gz (9.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting logbar>=0.2.1 (from gptqmodel)
  Downloading logbar-0.2.2.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting maturin>=1.9.4 (from gptqmodel)
  Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl.metadata (16 kB)
Requirement already satisfied: datasets>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (4.0.0)
Collecting pyarrow>=21.0 (from gptqmodel)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.3.8)
Collecting pypcre>=0.2.9 (from gptqmodel)
  Downloading pypcre-0.2.12.tar.gz (119 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torchao>=0.14.1 (from gptqmodel)
  Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting kernels>=0.11.1 (from gptqmodel)
  Downloading kernels-0.12.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (6.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.24.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.22.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.11)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.8.0->gptqmodel) (1.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.8.0->gptqmodel) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.24.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.8.0->gptqmodel) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.6.0->gptqmodel) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (0.1.2)
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 228.4 MB/s  0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 148.1 MB/s  0:00:00
Downloading kernels-0.12.2-py3-none-any.whl (55 kB)
Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 222.5 MB/s  0:00:00
Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 202.9 MB/s  0:00:00
Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 142.9 MB/s  0:00:00
Building wheels for collected packages: gptqmodel, device-smi, logbar, pypcre, tokenicer
  Building wheel for gptqmodel (pyproject.toml) ... done
  Created wheel for gptqmodel: filename=gptqmodel-5.7.0-py3-none-any.whl size=817346 sha256=3453eca0e385a1323e9589ed8f53071c0c74eda762f942e03c33f70359bc2975
  Stored in directory: /root/.cache/pip/wheels/f1/89/4a/76480c491998e47c9b7dc4b46b9839d4c9bbb547595240e42f
  Building wheel for device-smi (pyproject.toml) ... done
  Created wheel for device-smi: filename=device_smi-0.5.3-py3-none-any.whl size=19983 sha256=e9bdd7b03815aea49c1d9bcbe934360dc6c594c59e2b4c8c84cf2947bd0769b8
  Stored in directory: /root/.cache/pip/wheels/49/e4/63/c7c798f3ca05e6d3e15269dc7789adf9214fb1f5324cf2f0e3
  Building wheel for logbar (pyproject.toml) ... done
  Created wheel for logbar: filename=logbar-0.2.2-py3-none-any.whl size=31310 sha256=6a5cd729229a114a562650a445e855a25a49d7abb10785cf33e39ae628e9c3b8
  Stored in directory: /root/.cache/pip/wheels/8d/89/e6/c44856115298a2e8c1d0fe2cbfedd1090372f68c5083cdacf9
  Building wheel for pypcre (pyproject.toml) ... done
  Created wheel for pypcre: filename=pypcre-0.2.12-cp312-cp312-linux_x86_64.whl size=204033 sha256=5bc026c2f8636c684fc7b2924ff540711479889cf40e6d9618db8fdd2a27fac5
  Stored in directory: /root/.cache/pip/wheels/30/ab/28/ed1230e6afa79e0412bc432fcce0ca7e26bfe74ccd0567154a
  Building wheel for tokenicer (pyproject.toml) ... done
  Created wheel for tokenicer: filename=tokenicer-0.0.8-py3-none-any.whl size=11710 sha256=bbaac26a745a1368a9aab673149b36c0c5b0a65f0bc11a5616df9862a7b84e2d
  Stored in directory: /root/.cache/pip/wheels/0d/5c/f8/f551cf580b631f76fb0e802127948b414c906b768fac0cf662
Successfully built gptqmodel device-smi logbar pypcre tokenicer
Installing collected packages: torchao, tokenicer, pypcre, pyarrow, protobuf, numpy, maturin, logbar, hf_transfer, device-smi, kernels, gptqmodel
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [gptqmodel]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-trace 1.18.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-dataproc 5.25.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
googleapis-common-protos 1.72.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-resource-manager 1.16.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-firestore 2.23.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.0 which is incompatible.
grpc-google-iam-v1 0.14.3 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigtable 2.35.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 7.34.0 which is incompatible.
google-cloud-aiplatform 1.139.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigquery-storage 2.36.2 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-appengine-logging 1.8.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-spanner 3.63.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-iam 2.21.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 7.34.0 which is incompatible.

In [ ]:

# Restart once after installation in a fresh runtime, then skip this cell on reruns.
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

In [ ]:
def get_calibration_data(cfg, tokenizer=None):
    cal_cfg = cfg['calibration']
    cache_path = CALIB_DIR / f"calibration_{cal_cfg['num_samples']}_{cal_cfg['max_length']}.pt"
    if cache_path.exists():
        logger.info('Using cached calibration samples: %s', cache_path)
        return torch.load(cache_path, weights_only=False)

    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

    logger.info('Loading calibration dataset: %s / %s / %s', cal_cfg['dataset'], cal_cfg['dataset_name'], cal_cfg['split'])
    ds = load_dataset(cal_cfg['dataset'], cal_cfg['dataset_name'], split=cal_cfg['split'])
    all_text = '\n\n'.join(t for t in ds['text'] if t and t.strip())
    encoded = tokenizer(all_text, return_tensors='pt')
    total_tokens = encoded.input_ids.shape[1]
    max_len = cal_cfg['max_length']

    if total_tokens <= max_len:
        raise ValueError(f'Calibration corpus too short: total_tokens={total_tokens}, max_length={max_len}')

    rng = torch.Generator().manual_seed(cal_cfg['seed'])
    starts = torch.randint(0, total_tokens - max_len, (cal_cfg['num_samples'],), generator=rng)
    samples = []
    for start in tqdm(starts.tolist(), desc='Preparing calibration windows', unit='sample'):
        end = start + max_len
        input_ids = encoded.input_ids[:, start:end]
        samples.append({
            'input_ids': input_ids,
            'attention_mask': torch.ones_like(input_ids),
        })

    torch.save(samples, cache_path)
    logger.info('Saved calibration cache: %s', cache_path)
    return samples


def quantize_full_gptq(cfg):
    tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quantized_already = (ARTIFACT_DIR / 'config.json').exists() and find_gptq_model_basename(ARTIFACT_DIR) is not None
    if quantized_already:
        logger.info('Quantized artifact already exists at %s', ARTIFACT_DIR)
        zip_path = BUNDLE_DIR / 'full_quant_quantized_model.zip'
        if not zip_path.exists():
            zip_directory(ARTIFACT_DIR, zip_path)
        return {
            'artifact_dir': str(ARTIFACT_DIR),
            'zip_path': str(zip_path),
            'gptq_model_file': find_gptq_model_basename(ARTIFACT_DIR),
            'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
            'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        }

    samples = get_calibration_data(cfg, tokenizer)
    cal_dataset = [
        {
            'input_ids': s['input_ids'].squeeze(0),
            'attention_mask': s['attention_mask'].squeeze(0),
        }
        for s in samples
    ]

    quantize_config = QuantizeConfig(
        bits=cfg['quant']['bits'],
        group_size=cfg['quant']['group_size'],
        desc_act=cfg['quant'].get('desc_act', False),
    )

    logger.info('Starting GPTQ full quantization for %s', cfg['base_model'])
    t0 = time.time()
    model = GPTQModel.load(cfg['base_model'], quantize_config, trust_remote_code=True)
    model.quantize(cal_dataset)
    model.save(str(ARTIFACT_DIR))
    tokenizer.save_pretrained(str(ARTIFACT_DIR))
    elapsed = time.time() - t0
    logger.info('Quantization finished in %s', format_seconds(elapsed))

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    model_file = find_gptq_model_basename(ARTIFACT_DIR)
    if model_file is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {ARTIFACT_DIR}')

    manifest = {
        'variant': VARIANT,
        'base_model': cfg['base_model'],
        'quant': cfg['quant'],
        'artifact_dir': str(ARTIFACT_DIR),
        'gptq_model_file': model_file,
        'quantization_elapsed_sec': elapsed,
        'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
        'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        'created_at_unix': time.time(),
    }
    save_json(manifest, ARTIFACT_DIR / 'artifact_manifest.json')
    save_json(manifest, RESULTS_DIR / 'quantization_manifest.json')

    zip_path = zip_directory(ARTIFACT_DIR, BUNDLE_DIR / 'full_quant_quantized_model.zip')

    state = get_results_state()
    state['quantization'] = manifest | {'zip_path': str(zip_path)}
    save_results_state(state)
    summary = update_summary_table(state)

    print('Quantized artifact ready.')
    print(json.dumps(manifest, indent=2))
    display(pd.DataFrame([summary]))
    return manifest | {'zip_path': str(zip_path)}

In [ ]:
import os
import gc
import json
import math
import time
import torch
from datasets import load_dataset
from transformers import AutoTokenizer
from gptqmodel import GPTQModel

# -----------------------------
# Perplexity config
# -----------------------------
PPL_DATASET_NAME = "wikitext"
PPL_DATASET_CONFIG = "wikitext-2-raw-v1"
PPL_SPLIT = "test"
PPL_MAX_LENGTH = 2048
PPL_STRIDE = 1024

print("=" * 80)
print("PERPLEXITY EVALUATION")
print("=" * 80)
print(f"Dataset      : {PPL_DATASET_NAME}/{PPL_DATASET_CONFIG}")
print(f"Split        : {PPL_SPLIT}")
print(f"Max length   : {PPL_MAX_LENGTH}")
print(f"Stride       : {PPL_STRIDE}")
print(f"Artifact dir : {ARTIFACT_DIR}")
print(f"Results dir  : {RESULTS_DIR}")

# -----------------------------
# Reload quantized model
# -----------------------------
print("\n[1/4] Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(ARTIFACT_DIR, use_fast=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
if tokenizer.pad_token_id is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id

print("[2/4] Loading quantized model...")
torch.cuda.empty_cache()
gc.collect()

model = GPTQModel.load(
    ARTIFACT_DIR,
    device="cuda:0" if torch.cuda.is_available() else "cpu"
)
model.eval()

# -----------------------------
# Load dataset
# -----------------------------
print("[3/4] Loading WikiText-2 test split...")
dataset = load_dataset(PPL_DATASET_NAME, PPL_DATASET_CONFIG, split=PPL_SPLIT)
text = "\n\n".join(dataset["text"])

encodings = tokenizer(text, return_tensors="pt")
input_ids = encodings["input_ids"]

seq_len = input_ids.size(1)
print(f"Tokenized sequence length: {seq_len}")

# -----------------------------
# Sliding-window perplexity
# -----------------------------
print("[4/4] Running sliding-window perplexity evaluation...")

nlls = []
prev_end_loc = 0
num_steps = 0

estimated_total_steps = max(1, math.ceil(max(seq_len - PPL_MAX_LENGTH, 0) / PPL_STRIDE) + 1)
start_time = time.time()

for begin_loc in range(0, seq_len, PPL_STRIDE):
    end_loc = min(begin_loc + PPL_MAX_LENGTH, seq_len)
    trg_len = end_loc - prev_end_loc

    input_ids_slice = input_ids[:, begin_loc:end_loc].to(model.device)
    target_ids = input_ids_slice.clone()
    target_ids[:, :-trg_len] = -100

    with torch.no_grad():
        outputs = model(input_ids=input_ids_slice, labels=target_ids)
        neg_log_likelihood = outputs.loss

    nlls.append(neg_log_likelihood.detach().float() * trg_len)

    prev_end_loc = end_loc
    num_steps += 1

    elapsed = time.time() - start_time
    avg_step = elapsed / num_steps
    eta = avg_step * (estimated_total_steps - num_steps)

    print(
        f"[PPL] step {num_steps}/{estimated_total_steps} | "
        f"window=({begin_loc}, {end_loc}) | "
        f"elapsed={elapsed/60:.2f} min | eta={eta/60:.2f} min"
    )

    if end_loc == seq_len:
        break

ppl = torch.exp(torch.stack(nlls).sum() / end_loc).item()

ppl_metrics = {
    "dataset": f"{PPL_DATASET_NAME}/{PPL_DATASET_CONFIG}",
    "split": PPL_SPLIT,
    "max_length": PPL_MAX_LENGTH,
    "stride": PPL_STRIDE,
    "num_tokens": int(seq_len),
    "num_windows": int(num_steps),
    "perplexity": float(ppl),
}

with open(os.path.join(RESULTS_DIR, "perplexity_metrics.json"), "w") as f:
    json.dump(ppl_metrics, f, indent=2)

with open(os.path.join(RESULTS_DIR, "perplexity_eval_config.json"), "w") as f:
    json.dump({
        "dataset_name": PPL_DATASET_NAME,
        "dataset_config": PPL_DATASET_CONFIG,
        "split": PPL_SPLIT,
        "max_length": PPL_MAX_LENGTH,
        "stride": PPL_STRIDE
    }, f, indent=2)

print("\nPerplexity evaluation complete.")
print(json.dumps(ppl_metrics, indent=2))

================================================================================
PERPLEXITY EVALUATION
================================================================================
Dataset      : wikitext/wikitext-2-raw-v1
Split        : test
Max length   : 2048
Stride       : 1024
Artifact dir : /content/artifacts/gptq_w4_g128/full_quant
Results dir  : /content/results/gptq_w4_g128_full_quant/full_quant

[1/4] Loading tokenizer...
[2/4] Loading quantized model...
from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/bvtyioxl-pcnusonl/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-09 23:02:47,749 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  gc.collect() reclaimed 143 objects in 0.326s

2026-03-09 23:02:49,344 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

[3/4] Loading WikiText-2 test split...

2026-03-09 23:02:49,644 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:02:49,874 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:02:49,880 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-09 23:02:50,119 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:02:50,346 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-09 23:02:51,037 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-09 23:02:51,275 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:02:51,510 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-09 23:02:51,770 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-09 23:02:52,006 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:02:52,236 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"
Token indices sequence length is longer than the specified maximum sequence length for this model (299078 > 32768). Running this sequence through the model will result in indexing errors

Tokenized sequence length: 299078
[4/4] Running sliding-window perplexity evaluation...
[PPL] step 1/292 | window=(0, 2048) | elapsed=0.00 min | eta=0.94 min
[PPL] step 2/292 | window=(1024, 3072) | elapsed=0.00 min | eta=0.68 min
[PPL] step 3/292 | window=(2048, 4096) | elapsed=0.01 min | eta=0.75 min
[PPL] step 4/292 | window=(3072, 5120) | elapsed=0.01 min | eta=0.80 min
[PPL] step 5/292 | window=(4096, 6144) | elapsed=0.01 min | eta=0.82 min
[PPL] step 6/292 | window=(5120, 7168) | elapsed=0.02 min | eta=0.85 min
[PPL] step 7/292 | window=(6144, 8192) | elapsed=0.02 min | eta=0.86 min
[PPL] step 8/292 | window=(7168, 9216) | elapsed=0.02 min | eta=0.87 min
[PPL] step 9/292 | window=(8192, 10240) | elapsed=0.03 min | eta=0.87 min
[PPL] step 10/292 | window=(9216, 11264) | elapsed=0.03 min | eta=0.88 min
[PPL] step 11/292 | window=(10240, 12288) | elapsed=0.03 min | eta=0.88 min
[PPL] step 12/292 | window=(11264, 13312) | elapsed=0.04 min | eta=0.88 min
[PPL] step 13/292 | window=(12288, 14336) | elapsed=0.04 min | eta=0.88 min
[PPL] step 14/292 | window=(13312, 15360) | elapsed=0.04 min | eta=0.88 min
[PPL] step 15/292 | window=(14336, 16384) | elapsed=0.05 min | eta=0.88 min
[PPL] step 16/292 | window=(15360, 17408) | elapsed=0.05 min | eta=0.88 min
[PPL] step 17/292 | window=(16384, 18432) | elapsed=0.05 min | eta=0.88 min
[PPL] step 18/292 | window=(17408, 19456) | elapsed=0.06 min | eta=0.88 min
[PPL] step 19/292 | window=(18432, 20480) | elapsed=0.06 min | eta=0.88 min
[PPL] step 20/292 | window=(19456, 21504) | elapsed=0.06 min | eta=0.88 min
[PPL] step 21/292 | window=(20480, 22528) | elapsed=0.07 min | eta=0.88 min
[PPL] step 22/292 | window=(21504, 23552) | elapsed=0.07 min | eta=0.88 min
[PPL] step 23/292 | window=(22528, 24576) | elapsed=0.07 min | eta=0.87 min
[PPL] step 24/292 | window=(23552, 25600) | elapsed=0.08 min | eta=0.87 min
[PPL] step 25/292 | window=(24576, 26624) | elapsed=0.08 min | eta=0.87 min
[PPL] step 26/292 | window=(25600, 27648) | elapsed=0.08 min | eta=0.87 min
[PPL] step 27/292 | window=(26624, 28672) | elapsed=0.09 min | eta=0.86 min
[PPL] step 28/292 | window=(27648, 29696) | elapsed=0.09 min | eta=0.86 min
[PPL] step 29/292 | window=(28672, 30720) | elapsed=0.09 min | eta=0.86 min
[PPL] step 30/292 | window=(29696, 31744) | elapsed=0.10 min | eta=0.86 min
[PPL] step 31/292 | window=(30720, 32768) | elapsed=0.10 min | eta=0.86 min
[PPL] step 32/292 | window=(31744, 33792) | elapsed=0.10 min | eta=0.85 min
[PPL] step 33/292 | window=(32768, 34816) | elapsed=0.11 min | eta=0.85 min
[PPL] step 34/292 | window=(33792, 35840) | elapsed=0.11 min | eta=0.85 min
[PPL] step 35/292 | window=(34816, 36864) | elapsed=0.12 min | eta=0.84 min
[PPL] step 36/292 | window=(35840, 37888) | elapsed=0.12 min | eta=0.84 min
[PPL] step 37/292 | window=(36864, 38912) | elapsed=0.12 min | eta=0.84 min
[PPL] step 38/292 | window=(37888, 39936) | elapsed=0.13 min | eta=0.84 min
[PPL] step 39/292 | window=(38912, 40960) | elapsed=0.13 min | eta=0.83 min
[PPL] step 40/292 | window=(39936, 41984) | elapsed=0.13 min | eta=0.83 min
[PPL] step 41/292 | window=(40960, 43008) | elapsed=0.14 min | eta=0.83 min
[PPL] step 42/292 | window=(41984, 44032) | elapsed=0.14 min | eta=0.83 min
[PPL] step 43/292 | window=(43008, 45056) | elapsed=0.14 min | eta=0.82 min
[PPL] step 44/292 | window=(44032, 46080) | elapsed=0.15 min | eta=0.82 min
[PPL] step 45/292 | window=(45056, 47104) | elapsed=0.15 min | eta=0.82 min
[PPL] step 46/292 | window=(46080, 48128) | elapsed=0.15 min | eta=0.81 min
[PPL] step 47/292 | window=(47104, 49152) | elapsed=0.16 min | eta=0.81 min
[PPL] step 48/292 | window=(48128, 50176) | elapsed=0.16 min | eta=0.81 min
[PPL] step 49/292 | window=(49152, 51200) | elapsed=0.16 min | eta=0.81 min
[PPL] step 50/292 | window=(50176, 52224) | elapsed=0.17 min | eta=0.80 min
[PPL] step 51/292 | window=(51200, 53248) | elapsed=0.17 min | eta=0.80 min
[PPL] step 52/292 | window=(52224, 54272) | elapsed=0.17 min | eta=0.80 min
[PPL] step 53/292 | window=(53248, 55296) | elapsed=0.18 min | eta=0.79 min
[PPL] step 54/292 | window=(54272, 56320) | elapsed=0.18 min | eta=0.79 min
[PPL] step 55/292 | window=(55296, 57344) | elapsed=0.18 min | eta=0.79 min
[PPL] step 56/292 | window=(56320, 58368) | elapsed=0.19 min | eta=0.78 min
[PPL] step 57/292 | window=(57344, 59392) | elapsed=0.19 min | eta=0.78 min
[PPL] step 58/292 | window=(58368, 60416) | elapsed=0.19 min | eta=0.78 min
[PPL] step 59/292 | window=(59392, 61440) | elapsed=0.20 min | eta=0.78 min
[PPL] step 60/292 | window=(60416, 62464) | elapsed=0.20 min | eta=0.77 min
[PPL] step 61/292 | window=(61440, 63488) | elapsed=0.20 min | eta=0.77 min
[PPL] step 62/292 | window=(62464, 64512) | elapsed=0.21 min | eta=0.77 min
[PPL] step 63/292 | window=(63488, 65536) | elapsed=0.21 min | eta=0.76 min
[PPL] step 64/292 | window=(64512, 66560) | elapsed=0.21 min | eta=0.76 min
[PPL] step 65/292 | window=(65536, 67584) | elapsed=0.22 min | eta=0.76 min
[PPL] step 66/292 | window=(66560, 68608) | elapsed=0.22 min | eta=0.75 min
[PPL] step 67/292 | window=(67584, 69632) | elapsed=0.22 min | eta=0.75 min
[PPL] step 68/292 | window=(68608, 70656) | elapsed=0.23 min | eta=0.75 min
[PPL] step 69/292 | window=(69632, 71680) | elapsed=0.23 min | eta=0.75 min
[PPL] step 70/292 | window=(70656, 72704) | elapsed=0.23 min | eta=0.74 min
[PPL] step 71/292 | window=(71680, 73728) | elapsed=0.24 min | eta=0.74 min
[PPL] step 72/292 | window=(72704, 74752) | elapsed=0.24 min | eta=0.74 min
[PPL] step 73/292 | window=(73728, 75776) | elapsed=0.24 min | eta=0.73 min
[PPL] step 74/292 | window=(74752, 76800) | elapsed=0.25 min | eta=0.73 min
[PPL] step 75/292 | window=(75776, 77824) | elapsed=0.25 min | eta=0.73 min
[PPL] step 76/292 | window=(76800, 78848) | elapsed=0.25 min | eta=0.72 min
[PPL] step 77/292 | window=(77824, 79872) | elapsed=0.26 min | eta=0.72 min
[PPL] step 78/292 | window=(78848, 80896) | elapsed=0.26 min | eta=0.72 min
[PPL] step 79/292 | window=(79872, 81920) | elapsed=0.27 min | eta=0.71 min
[PPL] step 80/292 | window=(80896, 82944) | elapsed=0.27 min | eta=0.71 min
[PPL] step 81/292 | window=(81920, 83968) | elapsed=0.27 min | eta=0.71 min
[PPL] step 82/292 | window=(82944, 84992) | elapsed=0.28 min | eta=0.71 min
[PPL] step 83/292 | window=(83968, 86016) | elapsed=0.28 min | eta=0.70 min
[PPL] step 84/292 | window=(84992, 87040) | elapsed=0.28 min | eta=0.70 min
[PPL] step 85/292 | window=(86016, 88064) | elapsed=0.29 min | eta=0.70 min
[PPL] step 86/292 | window=(87040, 89088) | elapsed=0.29 min | eta=0.69 min
[PPL] step 87/292 | window=(88064, 90112) | elapsed=0.29 min | eta=0.69 min
[PPL] step 88/292 | window=(89088, 91136) | elapsed=0.30 min | eta=0.69 min
[PPL] step 89/292 | window=(90112, 92160) | elapsed=0.30 min | eta=0.68 min
[PPL] step 90/292 | window=(91136, 93184) | elapsed=0.30 min | eta=0.68 min
[PPL] step 91/292 | window=(92160, 94208) | elapsed=0.31 min | eta=0.68 min
[PPL] step 92/292 | window=(93184, 95232) | elapsed=0.31 min | eta=0.67 min
[PPL] step 93/292 | window=(94208, 96256) | elapsed=0.31 min | eta=0.67 min
[PPL] step 94/292 | window=(95232, 97280) | elapsed=0.32 min | eta=0.67 min
[PPL] step 95/292 | window=(96256, 98304) | elapsed=0.32 min | eta=0.66 min
[PPL] step 96/292 | window=(97280, 99328) | elapsed=0.32 min | eta=0.66 min
[PPL] step 97/292 | window=(98304, 100352) | elapsed=0.33 min | eta=0.66 min
[PPL] step 98/292 | window=(99328, 101376) | elapsed=0.33 min | eta=0.65 min
[PPL] step 99/292 | window=(100352, 102400) | elapsed=0.33 min | eta=0.65 min
[PPL] step 100/292 | window=(101376, 103424) | elapsed=0.34 min | eta=0.65 min
[PPL] step 101/292 | window=(102400, 104448) | elapsed=0.34 min | eta=0.64 min
[PPL] step 102/292 | window=(103424, 105472) | elapsed=0.34 min | eta=0.64 min
[PPL] step 103/292 | window=(104448, 106496) | elapsed=0.35 min | eta=0.64 min
[PPL] step 104/292 | window=(105472, 107520) | elapsed=0.35 min | eta=0.63 min
[PPL] step 105/292 | window=(106496, 108544) | elapsed=0.35 min | eta=0.63 min
[PPL] step 106/292 | window=(107520, 109568) | elapsed=0.36 min | eta=0.63 min
[PPL] step 107/292 | window=(108544, 110592) | elapsed=0.36 min | eta=0.62 min
[PPL] step 108/292 | window=(109568, 111616) | elapsed=0.36 min | eta=0.62 min
[PPL] step 109/292 | window=(110592, 112640) | elapsed=0.37 min | eta=0.62 min
[PPL] step 110/292 | window=(111616, 113664) | elapsed=0.37 min | eta=0.61 min
[PPL] step 111/292 | window=(112640, 114688) | elapsed=0.37 min | eta=0.61 min
[PPL] step 112/292 | window=(113664, 115712) | elapsed=0.38 min | eta=0.61 min
[PPL] step 113/292 | window=(114688, 116736) | elapsed=0.38 min | eta=0.60 min
[PPL] step 114/292 | window=(115712, 117760) | elapsed=0.38 min | eta=0.60 min
[PPL] step 115/292 | window=(116736, 118784) | elapsed=0.39 min | eta=0.60 min
[PPL] step 116/292 | window=(117760, 119808) | elapsed=0.39 min | eta=0.59 min
[PPL] step 117/292 | window=(118784, 120832) | elapsed=0.39 min | eta=0.59 min
[PPL] step 118/292 | window=(119808, 121856) | elapsed=0.40 min | eta=0.59 min
[PPL] step 119/292 | window=(120832, 122880) | elapsed=0.40 min | eta=0.58 min
[PPL] step 120/292 | window=(121856, 123904) | elapsed=0.40 min | eta=0.58 min
[PPL] step 121/292 | window=(122880, 124928) | elapsed=0.41 min | eta=0.58 min
[PPL] step 122/292 | window=(123904, 125952) | elapsed=0.41 min | eta=0.57 min
[PPL] step 123/292 | window=(124928, 126976) | elapsed=0.41 min | eta=0.57 min
[PPL] step 124/292 | window=(125952, 128000) | elapsed=0.42 min | eta=0.57 min
[PPL] step 125/292 | window=(126976, 129024) | elapsed=0.42 min | eta=0.56 min
[PPL] step 126/292 | window=(128000, 130048) | elapsed=0.42 min | eta=0.56 min
[PPL] step 127/292 | window=(129024, 131072) | elapsed=0.43 min | eta=0.56 min
[PPL] step 128/292 | window=(130048, 132096) | elapsed=0.43 min | eta=0.55 min
[PPL] step 129/292 | window=(131072, 133120) | elapsed=0.44 min | eta=0.55 min
[PPL] step 130/292 | window=(132096, 134144) | elapsed=0.44 min | eta=0.55 min
[PPL] step 131/292 | window=(133120, 135168) | elapsed=0.44 min | eta=0.54 min
[PPL] step 132/292 | window=(134144, 136192) | elapsed=0.45 min | eta=0.54 min
[PPL] step 133/292 | window=(135168, 137216) | elapsed=0.45 min | eta=0.54 min
[PPL] step 134/292 | window=(136192, 138240) | elapsed=0.45 min | eta=0.53 min
[PPL] step 135/292 | window=(137216, 139264) | elapsed=0.46 min | eta=0.53 min
[PPL] step 136/292 | window=(138240, 140288) | elapsed=0.46 min | eta=0.53 min
[PPL] step 137/292 | window=(139264, 141312) | elapsed=0.46 min | eta=0.52 min
[PPL] step 138/292 | window=(140288, 142336) | elapsed=0.47 min | eta=0.52 min
[PPL] step 139/292 | window=(141312, 143360) | elapsed=0.47 min | eta=0.52 min
[PPL] step 140/292 | window=(142336, 144384) | elapsed=0.47 min | eta=0.51 min
[PPL] step 141/292 | window=(143360, 145408) | elapsed=0.48 min | eta=0.51 min
[PPL] step 142/292 | window=(144384, 146432) | elapsed=0.48 min | eta=0.51 min
[PPL] step 143/292 | window=(145408, 147456) | elapsed=0.48 min | eta=0.50 min
[PPL] step 144/292 | window=(146432, 148480) | elapsed=0.49 min | eta=0.50 min
[PPL] step 145/292 | window=(147456, 149504) | elapsed=0.49 min | eta=0.50 min
[PPL] step 146/292 | window=(148480, 150528) | elapsed=0.49 min | eta=0.49 min
[PPL] step 147/292 | window=(149504, 151552) | elapsed=0.50 min | eta=0.49 min
[PPL] step 148/292 | window=(150528, 152576) | elapsed=0.50 min | eta=0.49 min
[PPL] step 149/292 | window=(151552, 153600) | elapsed=0.50 min | eta=0.48 min
[PPL] step 150/292 | window=(152576, 154624) | elapsed=0.51 min | eta=0.48 min
[PPL] step 151/292 | window=(153600, 155648) | elapsed=0.51 min | eta=0.48 min
[PPL] step 152/292 | window=(154624, 156672) | elapsed=0.51 min | eta=0.47 min
[PPL] step 153/292 | window=(155648, 157696) | elapsed=0.52 min | eta=0.47 min
[PPL] step 154/292 | window=(156672, 158720) | elapsed=0.52 min | eta=0.47 min
[PPL] step 155/292 | window=(157696, 159744) | elapsed=0.52 min | eta=0.46 min
[PPL] step 156/292 | window=(158720, 160768) | elapsed=0.53 min | eta=0.46 min
[PPL] step 157/292 | window=(159744, 161792) | elapsed=0.53 min | eta=0.46 min
[PPL] step 158/292 | window=(160768, 162816) | elapsed=0.53 min | eta=0.45 min
[PPL] step 159/292 | window=(161792, 163840) | elapsed=0.54 min | eta=0.45 min
[PPL] step 160/292 | window=(162816, 164864) | elapsed=0.54 min | eta=0.44 min
[PPL] step 161/292 | window=(163840, 165888) | elapsed=0.54 min | eta=0.44 min
[PPL] step 162/292 | window=(164864, 166912) | elapsed=0.55 min | eta=0.44 min
[PPL] step 163/292 | window=(165888, 167936) | elapsed=0.55 min | eta=0.43 min
[PPL] step 164/292 | window=(166912, 168960) | elapsed=0.55 min | eta=0.43 min
[PPL] step 165/292 | window=(167936, 169984) | elapsed=0.56 min | eta=0.43 min
[PPL] step 166/292 | window=(168960, 171008) | elapsed=0.56 min | eta=0.42 min
[PPL] step 167/292 | window=(169984, 172032) | elapsed=0.56 min | eta=0.42 min
[PPL] step 168/292 | window=(171008, 173056) | elapsed=0.57 min | eta=0.42 min
[PPL] step 169/292 | window=(172032, 174080) | elapsed=0.57 min | eta=0.41 min
[PPL] step 170/292 | window=(173056, 175104) | elapsed=0.57 min | eta=0.41 min
[PPL] step 171/292 | window=(174080, 176128) | elapsed=0.58 min | eta=0.41 min
[PPL] step 172/292 | window=(175104, 177152) | elapsed=0.58 min | eta=0.40 min
[PPL] step 173/292 | window=(176128, 178176) | elapsed=0.58 min | eta=0.40 min
[PPL] step 174/292 | window=(177152, 179200) | elapsed=0.59 min | eta=0.40 min
[PPL] step 175/292 | window=(178176, 180224) | elapsed=0.59 min | eta=0.39 min
[PPL] step 176/292 | window=(179200, 181248) | elapsed=0.59 min | eta=0.39 min
[PPL] step 177/292 | window=(180224, 182272) | elapsed=0.60 min | eta=0.39 min
[PPL] step 178/292 | window=(181248, 183296) | elapsed=0.60 min | eta=0.38 min
[PPL] step 179/292 | window=(182272, 184320) | elapsed=0.60 min | eta=0.38 min
[PPL] step 180/292 | window=(183296, 185344) | elapsed=0.61 min | eta=0.38 min
[PPL] step 181/292 | window=(184320, 186368) | elapsed=0.61 min | eta=0.37 min
[PPL] step 182/292 | window=(185344, 187392) | elapsed=0.61 min | eta=0.37 min
[PPL] step 183/292 | window=(186368, 188416) | elapsed=0.62 min | eta=0.37 min
[PPL] step 184/292 | window=(187392, 189440) | elapsed=0.62 min | eta=0.36 min
[PPL] step 185/292 | window=(188416, 190464) | elapsed=0.62 min | eta=0.36 min
[PPL] step 186/292 | window=(189440, 191488) | elapsed=0.63 min | eta=0.36 min
[PPL] step 187/292 | window=(190464, 192512) | elapsed=0.63 min | eta=0.35 min
[PPL] step 188/292 | window=(191488, 193536) | elapsed=0.63 min | eta=0.35 min
[PPL] step 189/292 | window=(192512, 194560) | elapsed=0.64 min | eta=0.35 min
[PPL] step 190/292 | window=(193536, 195584) | elapsed=0.64 min | eta=0.34 min
[PPL] step 191/292 | window=(194560, 196608) | elapsed=0.64 min | eta=0.34 min
[PPL] step 192/292 | window=(195584, 197632) | elapsed=0.65 min | eta=0.34 min
[PPL] step 193/292 | window=(196608, 198656) | elapsed=0.65 min | eta=0.33 min
[PPL] step 194/292 | window=(197632, 199680) | elapsed=0.65 min | eta=0.33 min
[PPL] step 195/292 | window=(198656, 200704) | elapsed=0.66 min | eta=0.33 min
[PPL] step 196/292 | window=(199680, 201728) | elapsed=0.66 min | eta=0.32 min
[PPL] step 197/292 | window=(200704, 202752) | elapsed=0.66 min | eta=0.32 min
[PPL] step 198/292 | window=(201728, 203776) | elapsed=0.67 min | eta=0.32 min
[PPL] step 199/292 | window=(202752, 204800) | elapsed=0.67 min | eta=0.31 min
[PPL] step 200/292 | window=(203776, 205824) | elapsed=0.67 min | eta=0.31 min
[PPL] step 201/292 | window=(204800, 206848) | elapsed=0.68 min | eta=0.31 min
[PPL] step 202/292 | window=(205824, 207872) | elapsed=0.68 min | eta=0.30 min
[PPL] step 203/292 | window=(206848, 208896) | elapsed=0.68 min | eta=0.30 min
[PPL] step 204/292 | window=(207872, 209920) | elapsed=0.69 min | eta=0.30 min
[PPL] step 205/292 | window=(208896, 210944) | elapsed=0.69 min | eta=0.29 min
[PPL] step 206/292 | window=(209920, 211968) | elapsed=0.69 min | eta=0.29 min
[PPL] step 207/292 | window=(210944, 212992) | elapsed=0.70 min | eta=0.29 min
[PPL] step 208/292 | window=(211968, 214016) | elapsed=0.70 min | eta=0.28 min
[PPL] step 209/292 | window=(212992, 215040) | elapsed=0.70 min | eta=0.28 min
[PPL] step 210/292 | window=(214016, 216064) | elapsed=0.71 min | eta=0.28 min
[PPL] step 211/292 | window=(215040, 217088) | elapsed=0.71 min | eta=0.27 min
[PPL] step 212/292 | window=(216064, 218112) | elapsed=0.71 min | eta=0.27 min
[PPL] step 213/292 | window=(217088, 219136) | elapsed=0.72 min | eta=0.27 min
[PPL] step 214/292 | window=(218112, 220160) | elapsed=0.72 min | eta=0.26 min
[PPL] step 215/292 | window=(219136, 221184) | elapsed=0.72 min | eta=0.26 min
[PPL] step 216/292 | window=(220160, 222208) | elapsed=0.73 min | eta=0.26 min
[PPL] step 217/292 | window=(221184, 223232) | elapsed=0.73 min | eta=0.25 min
[PPL] step 218/292 | window=(222208, 224256) | elapsed=0.73 min | eta=0.25 min
[PPL] step 219/292 | window=(223232, 225280) | elapsed=0.74 min | eta=0.25 min
[PPL] step 220/292 | window=(224256, 226304) | elapsed=0.74 min | eta=0.24 min
[PPL] step 221/292 | window=(225280, 227328) | elapsed=0.74 min | eta=0.24 min
[PPL] step 222/292 | window=(226304, 228352) | elapsed=0.75 min | eta=0.24 min
[PPL] step 223/292 | window=(227328, 229376) | elapsed=0.75 min | eta=0.23 min
[PPL] step 224/292 | window=(228352, 230400) | elapsed=0.75 min | eta=0.23 min
[PPL] step 225/292 | window=(229376, 231424) | elapsed=0.76 min | eta=0.23 min
[PPL] step 226/292 | window=(230400, 232448) | elapsed=0.76 min | eta=0.22 min
[PPL] step 227/292 | window=(231424, 233472) | elapsed=0.76 min | eta=0.22 min
[PPL] step 228/292 | window=(232448, 234496) | elapsed=0.77 min | eta=0.22 min
[PPL] step 229/292 | window=(233472, 235520) | elapsed=0.77 min | eta=0.21 min
[PPL] step 230/292 | window=(234496, 236544) | elapsed=0.77 min | eta=0.21 min
[PPL] step 231/292 | window=(235520, 237568) | elapsed=0.78 min | eta=0.21 min
[PPL] step 232/292 | window=(236544, 238592) | elapsed=0.78 min | eta=0.20 min
[PPL] step 233/292 | window=(237568, 239616) | elapsed=0.78 min | eta=0.20 min
[PPL] step 234/292 | window=(238592, 240640) | elapsed=0.79 min | eta=0.19 min
[PPL] step 235/292 | window=(239616, 241664) | elapsed=0.79 min | eta=0.19 min
[PPL] step 236/292 | window=(240640, 242688) | elapsed=0.79 min | eta=0.19 min
[PPL] step 237/292 | window=(241664, 243712) | elapsed=0.80 min | eta=0.18 min
[PPL] step 238/292 | window=(242688, 244736) | elapsed=0.80 min | eta=0.18 min
[PPL] step 239/292 | window=(243712, 245760) | elapsed=0.80 min | eta=0.18 min
[PPL] step 240/292 | window=(244736, 246784) | elapsed=0.81 min | eta=0.17 min
[PPL] step 241/292 | window=(245760, 247808) | elapsed=0.81 min | eta=0.17 min
[PPL] step 242/292 | window=(246784, 248832) | elapsed=0.81 min | eta=0.17 min
[PPL] step 243/292 | window=(247808, 249856) | elapsed=0.82 min | eta=0.16 min
[PPL] step 244/292 | window=(248832, 250880) | elapsed=0.82 min | eta=0.16 min
[PPL] step 245/292 | window=(249856, 251904) | elapsed=0.82 min | eta=0.16 min
[PPL] step 246/292 | window=(250880, 252928) | elapsed=0.83 min | eta=0.15 min
[PPL] step 247/292 | window=(251904, 253952) | elapsed=0.83 min | eta=0.15 min
[PPL] step 248/292 | window=(252928, 254976) | elapsed=0.83 min | eta=0.15 min
[PPL] step 249/292 | window=(253952, 256000) | elapsed=0.84 min | eta=0.14 min
[PPL] step 250/292 | window=(254976, 257024) | elapsed=0.84 min | eta=0.14 min
[PPL] step 251/292 | window=(256000, 258048) | elapsed=0.84 min | eta=0.14 min
[PPL] step 252/292 | window=(257024, 259072) | elapsed=0.85 min | eta=0.13 min
[PPL] step 253/292 | window=(258048, 260096) | elapsed=0.85 min | eta=0.13 min
[PPL] step 254/292 | window=(259072, 261120) | elapsed=0.85 min | eta=0.13 min
[PPL] step 255/292 | window=(260096, 262144) | elapsed=0.86 min | eta=0.12 min
[PPL] step 256/292 | window=(261120, 263168) | elapsed=0.86 min | eta=0.12 min

In [ ]:

# Cell 1 — Quantize the model and save the quantized artifact zip
quant_manifest = quantize_full_gptq(cfg)

2026-03-09 22:16:54,575 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-09 22:16:54,576 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-09 22:16:54,582 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:16:54,590 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

2026-03-09 22:16:54,833 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:54,839 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-09 22:16:54,846 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json: 0.00B [00:00, ?B/s]

2026-03-09 22:16:55,094 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-09 22:16:55,332 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:16:55,565 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:55,571 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"
2026-03-09 22:16:55,578 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"

vocab.json: 0.00B [00:00, ?B/s]

2026-03-09 22:16:55,852 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/merges.txt "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:55,858 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"
2026-03-09 22:16:55,865 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"

merges.txt: 0.00B [00:00, ?B/s]

2026-03-09 22:16:56,132 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:56,138 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"
2026-03-09 22:16:56,146 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

2026-03-09 22:16:56,440 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-03-09 22:16:56,721 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-03-09 22:16:56,954 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-03-09 22:16:57,954 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-03-09 22:16:57,957 | INFO    | Loading calibration dataset: wikitext / wikitext-2-raw-v1 / train
2026-03-09 22:16:58,188 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:58,423 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:58,429 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-09 22:16:58,436 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"

README.md: 0.00B [00:00, ?B/s]

2026-03-09 22:16:58,679 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:16:58,907 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-09 22:16:59,586 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-09 22:16:59,837 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:00,070 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"
2026-03-09 22:17:00,309 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:00,543 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-09 22:17:00,875 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-09 22:17:01,112 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:01,347 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:01,579 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:01,817 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:02,055 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:02,296 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-03-09 22:17:02,529 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:02,773 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:03,093 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:03,325 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-03-09 22:17:03,595 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/xet-read-token/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"

wikitext-2-raw-v1/test-00000-of-00001.pa(…):   0%|          | 0.00/733k [00:00<?, ?B/s]

2026-03-09 22:17:04,990 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:05,235 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/train-00000-of-00001.p(…):   0%|          | 0.00/6.36M [00:00<?, ?B/s]

2026-03-09 22:17:06,098 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:06,341 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/validation-00000-of-00(…):   0%|          | 0.00/657k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (2517232 > 32768). Running this sequence through the model will result in indexing errors

Preparing calibration windows:   0%|          | 0/512 [00:00<?, ?sample/s]

2026-03-09 22:17:19,020 | INFO    | Saved calibration cache: /content/calibration_data/calibration_512_2048.pt

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/hqdpgrum-rkaakpxx/`

2026-03-09 22:17:19,343 | INFO    | Starting GPTQ full quantization for Qwen/Qwen2-1.5B
2026-03-09 22:17:19,606 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:19,613 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:19,860 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:20,092 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:20,322 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:20,328 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:20,574 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:20,580 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:20,816 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/revision/main "HTTP/1.1 200 OK"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

2026-03-09 22:17:21,068 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:21,070 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:21,074 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:21,075 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:21,077 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-09 22:17:21,081 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-09 22:17:21,085 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:21,087 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-09 22:17:21,089 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-09 22:17:21,090 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/model.safetensors "HTTP/1.1 302 Found"
2026-03-09 22:17:21,090 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:21,100 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-09 22:17:21,106 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-09 22:17:21,325 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/xet-read-token/8a16abf2848eda07cc5253dec660bf1ce007ad7a "HTTP/1.1 200 OK"
2026-03-09 22:17:30,693 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:30,699 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:30,942 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:30,948 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:31,177 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-09 22:17:31,411 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 22:17:32,467 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

model: Qwen2ForCausalLM  (P=0 B=0) [- | - | ~0B]
├─ model.model: Qwen2Model  (P=0 B=0) [- | - | ~0B]
│  ├─ model.model.embed_tokens: Embedding  (P=233.37M B=0) [meta | bfloat16 | ~0B (est~445.12MB)]
│  │  │  param: weight  shape=(151936, 1536) dtype=bfloat16 device=meta ~445.12MB
│  ├─ model.model.layers: ModuleList  (P=0 B=0) [- | - | ~0B]
│  │  ├─ model.model.layers.0: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.0.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.0.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.0.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.0.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.1: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.1.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.1.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.1.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.1.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.1.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.2: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.2.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.2.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.2.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.2.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.2.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.3: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.3.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.3.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.3.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.3.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.3.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.4: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.4.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.4.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.4.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.4.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.4.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.5: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.5.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.5.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.5.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.5.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.5.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.6: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.6.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.6.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.6.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.6.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.6.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.7: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.7.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.7.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.7.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.7.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.7.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

2026-03-09 22:17:33,277 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 22:17:33,283 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 22:17:33,408 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[]`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Disk subsystem write throughput detected at 266.2 MB/s.

2026-03-09 22:17:34,872 | INFO    | Not a TTY. Pause/resume from keyboard is disabled.

INFO  ModuleLooper: capturing layer inputs from 512 calibration batches

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  Offloading base modules to disk...

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | region     | count | last_s | avg_s | total_s | pct    | source  |

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | Capture inputs | 1     | 2.202  | 2.202 | 2.202   | 85.0%  | cache_inputs:Qwen2DecoderLayer |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Turtle reload  | 1     | 0.389  | 0.389 | 0.389   | 15.0%  | auto:Embedding                 |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000056309 | 1048576 | 0.05000 | 2.309 | 3.101    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000010618 | 1048576 | 0.05000 | 2.346 | 3.101    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000001316 | 1048576 | 0.05000 | 2.366 | 3.101    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001152 | 1048576 | 0.05000 | 0.537 | 2.351    | cuda 0.74G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000032352 | 1048576 | 0.05000 | 0.994 | 3.696    | cuda 1.25G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000020776 | 1048576 | 0.05000 | 1.008 | 3.696    | cuda 1.25G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000001256 | 1048576 | 0.05000 | 3.505 | 17.618   | cuda 2.52G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward | 4     | 17.618 | 6.692 | 26.767  | 42.6%  | model.layers.0:subset4/4       |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Forward hook      | 3584  | 0.028  | 0.005 | 17.142  | 27.3%  | model.layers.0.mlp.down_proj   |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Process quant     | 14    | 3.515  | 0.939 | 13.152  | 20.9%  | model.layers.0.mlp.down_proj   |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Post-quant replay | 1     | 3.154  | 3.154 | 3.154   | 5.0%   | model.layers.0:subset4/4       |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Capture inputs    | 1     | 2.202  | 2.202 | 2.202   | 3.5%   | cache_inputs:Qwen2DecoderLayer |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Turtle reload     | 1     | 0.389  | 0.389 | 0.389   | 0.6%   | auto:Embedding                 |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  Format: Converting GPTQ v2 to v1

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003781 | 1048576 | 0.05000 | 1.584 | 2.963    | cuda 3.82G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000000500 | 1048576 | 0.05000 | 1.628 | 2.963    | cuda 3.82G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000011015 | 1048576 | 0.05000 | 1.640 | 2.963    | cuda 3.82G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000320 | 1048576 | 0.05000 | 0.556 | 1.604    | cuda 3.82G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000098303 | 1048576 | 0.05000 | 0.986 | 3.174    | cuda 4.14G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000068815 | 1048576 | 0.05000 | 1.000 | 3.174    | cuda 4.14G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000009690 | 1048576 | 0.05000 | 3.549 | 17.513   | cuda 5.34G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward | 8     | 17.513 | 6.503 | 52.020  | 38.4%  | model.layers.1:subset4/4       |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Forward hook      | 7168  | 0.028  | 0.005 | 35.118  | 25.9%  | model.layers.1.mlp.down_proj   |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Process quant     | 28    | 3.559  | 0.864 | 24.179  | 17.9%  | model.layers.1.mlp.down_proj   |

INFO  +-------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Submodule finalize | 14    | 1.648  | 0.576 | 8.062   | 6.0%   | model.layers.0.mlp.up_proj     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Post-quant replay  | 2     | 2.756  | 2.955 | 5.910   | 4.4%   | model.layers.1:subset4/4       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Finalize create    | 7     | 0.992  | 0.626 | 4.380   | 3.2%   | model.layers.0.mlp.up_proj     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Finalize pack      | 7     | 0.609  | 0.426 | 2.979   | 2.2%   | model.layers.0.mlp.up_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 1.6%   | cache_inputs:Qwen2DecoderLayer                 |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.389  | 0.389 | 0.389   | 0.3%   | auto:Embedding                                 |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Finalize offload   | 7     | 0.016  | 0.029 | 0.201   | 0.1%   | model.layers.0.mlp.up_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000045978 | 1048576 | 0.05000 | 1.589 | 2.298    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012945 | 1048576 | 0.05000 | 1.614 | 2.298    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003603 | 1048576 | 0.05000 | 1.625 | 2.298    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000822 | 1048576 | 0.05000 | 0.548 | 1.582    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000113527 | 1048576 | 0.05000 | 0.984 | 3.144    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000155993 | 1048576 | 0.05000 | 1.002 | 3.144    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000004864 | 1048576 | 0.05000 | 3.487 | 17.274   | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 12    | 17.274 | 6.360 | 76.318  | 38.6%  | model.layers.2:subset4/4                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Forward hook       | 10752 | 0.028  | 0.005 | 52.752  | 26.7%  | model.layers.2.mlp.down_proj                   |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Process quant      | 42    | 3.498  | 0.836 | 35.116  | 17.7%  | model.layers.2.mlp.down_proj                   |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Submodule finalize | 28    | 0.986  | 0.426 | 11.932  | 6.0%   | model.layers.1.mlp.down_proj                   |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Post-quant replay  | 3     | 2.737  | 2.882 | 8.647   | 4.4%   | model.layers.2:subset4/4                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Finalize create    | 14    | 0.318  | 0.379 | 5.311   | 2.7%   | model.layers.1.mlp.down_proj                   |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------+

INFO  | Finalize pack      | 14    | 0.617  | 0.330 | 4.622   | 2.3%   | model.layers.1.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 1.1%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 14    | 0.015  | 0.046 | 0.650   | 0.3%   | model.layers.1.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.389  | 0.389 | 0.389   | 0.2%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000041335 | 1048576 | 0.05000 | 1.577 | 2.301    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000004226 | 1048576 | 0.05000 | 1.601 | 2.301    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011185 | 1048576 | 0.05000 | 1.614 | 2.301    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000778 | 1048576 | 0.05000 | 0.595 | 1.620    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000201852 | 1048576 | 0.05000 | 1.001 | 3.111    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000145294 | 1048576 | 0.05000 | 1.003 | 3.111    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007827 | 1048576 | 0.05000 | 3.471 | 17.398   | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 16    | 17.398 | 6.297 | 100.748 | 38.7%  | model.layers.3:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 14336 | 0.028  | 0.005 | 70.537  | 27.1%  | model.layers.3.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 56    | 3.480  | 0.823 | 46.075  | 17.7%  | model.layers.3.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 42    | 0.951  | 0.369 | 15.498  | 6.0%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 4     | 2.758  | 2.851 | 11.405  | 4.4%   | model.layers.3:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 21    | 0.546  | 0.295 | 6.186   | 2.4%   | model.layers.2.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 21    | 0.353  | 0.292 | 6.122   | 2.4%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.8%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 21    | 0.017  | 0.061 | 1.271   | 0.5%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.389  | 0.389 | 0.389   | 0.1%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007637 | 1048576 | 0.05000 | 1.606 | 2.283    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000033682 | 1048576 | 0.05000 | 1.697 | 2.283    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000004751 | 1048576 | 0.05000 | 1.711 | 2.283    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001583 | 1048576 | 0.05000 | 0.553 | 1.522    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000256061 | 1048576 | 0.05000 | 1.032 | 3.116    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000173565 | 1048576 | 0.05000 | 1.051 | 3.116    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008416 | 1048576 | 0.05000 | 3.466 | 17.404   | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 20    | 17.404 | 6.254 | 125.074 | 38.8%  | model.layers.4:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 17920 | 0.029  | 0.005 | 88.276  | 27.4%  | model.layers.4.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 70    | 3.475  | 0.818 | 57.274  | 17.8%  | model.layers.4.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 56    | 0.902  | 0.336 | 18.842  | 5.8%   | model.layers.3.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 5     | 2.752  | 2.831 | 14.157  | 4.4%   | model.layers.4:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 28    | 0.525  | 0.274 | 7.684   | 2.4%   | model.layers.3.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 28    | 0.331  | 0.244 | 6.845   | 2.1%   | model.layers.3.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.7%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 28    | 0.017  | 0.066 | 1.860   | 0.6%   | model.layers.3.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.389  | 0.389 | 0.389   | 0.1%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018717 | 1048576 | 0.05000 | 1.620 | 2.292    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000070778 | 1048576 | 0.05000 | 1.653 | 2.292    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000006702 | 1048576 | 0.05000 | 1.655 | 2.292    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001619 | 1048576 | 0.05000 | 0.552 | 1.584    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000200622 | 1048576 | 0.05000 | 0.990 | 3.095    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000322532 | 1048576 | 0.05000 | 0.991 | 3.095    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000009453 | 1048576 | 0.05000 | 3.466 | 17.400   | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 24    | 17.400 | 6.227 | 149.445 | 38.8%  | model.layers.5:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 21504 | 0.029  | 0.005 | 105.970 | 27.5%  | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 84    | 3.475  | 0.813 | 68.300  | 17.7%  | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 70    | 0.934  | 0.323 | 22.602  | 5.9%   | model.layers.4.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 6     | 2.741  | 2.816 | 16.897  | 4.4%   | model.layers.5:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 35    | 0.518  | 0.264 | 9.235   | 2.4%   | model.layers.4.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 35    | 0.372  | 0.227 | 7.952   | 2.1%   | model.layers.4.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 35    | 0.025  | 0.073 | 2.567   | 0.7%   | model.layers.4.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.6%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.389  | 0.389 | 0.389   | 0.1%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000014397 | 1048576 | 0.05000 | 1.826 | 2.305    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000064795 | 1048576 | 0.05000 | 1.837 | 2.305    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007732 | 1048576 | 0.05000 | 1.846 | 2.305    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002396 | 1048576 | 0.05000 | 0.581 | 1.641    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000314785 | 1048576 | 0.05000 | 1.030 | 3.177    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000209109 | 1048576 | 0.05000 | 1.049 | 3.177    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010699 | 1048576 | 0.05000 | 3.532 | 17.515   | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 28    | 17.515 | 6.217 | 174.083 | 37.8%  | model.layers.6:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 25088 | 0.028  | 0.005 | 123.714 | 26.9%  | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 98    | 3.542  | 0.818 | 80.127  | 17.4%  | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 84    | 1.597  | 0.379 | 31.828  | 6.9%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 7     | 2.744  | 2.806 | 19.641  | 4.3%   | model.layers.6:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 42    | 0.691  | 0.297 | 12.488  | 2.7%   | model.layers.5.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 42    | 0.862  | 0.286 | 12.004  | 2.6%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 42    | 0.018  | 0.078 | 3.295   | 0.7%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.5%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.3%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003942 | 1048576 | 0.05000 | 1.626 | 2.316    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000042389 | 1048576 | 0.05000 | 1.671 | 2.316    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011219 | 1048576 | 0.05000 | 1.683 | 2.316    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001850 | 1048576 | 0.05000 | 0.543 | 1.563    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000198315 | 1048576 | 0.05000 | 0.974 | 3.128    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000243999 | 1048576 | 0.05000 | 0.991 | 3.128    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010823 | 1048576 | 0.05000 | 3.474 | 17.456   | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 32    | 17.456 | 6.205 | 198.547 | 38.0%  | model.layers.7:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 28672 | 0.028  | 0.005 | 141.479 | 27.0%  | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 112   | 3.483  | 0.814 | 91.172  | 17.4%  | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 98    | 0.928  | 0.362 | 35.498  | 6.8%   | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 8     | 2.745  | 2.798 | 22.386  | 4.3%   | model.layers.7:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 49    | 0.592  | 0.286 | 14.036  | 2.7%   | model.layers.6.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 49    | 0.298  | 0.258 | 12.666  | 2.4%   | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 49    | 0.016  | 0.079 | 3.875   | 0.7%   | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005268 | 1048576 | 0.05000 | 1.679 | 2.372    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000035448 | 1048576 | 0.05000 | 1.724 | 2.372    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000008396 | 1048576 | 0.05000 | 1.739 | 2.372    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000004689 | 1048576 | 0.05000 | 0.594 | 1.607    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000185360 | 1048576 | 0.05000 | 1.006 | 3.149    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000247648 | 1048576 | 0.05000 | 1.038 | 3.149    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010378 | 1048576 | 0.05000 | 3.539 | 17.421   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 36    | 17.421 | 6.197 | 223.096 | 38.0%  | model.layers.8:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 32256 | 0.028  | 0.005 | 159.233 | 27.2%  | model.layers.8.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 126   | 3.548  | 0.814 | 102.583 | 17.5%  | model.layers.8.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 112   | 0.938  | 0.350 | 39.169  | 6.7%   | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 9     | 2.757  | 2.794 | 25.143  | 4.3%   | model.layers.8:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 56    | 0.589  | 0.278 | 15.595  | 2.7%   | model.layers.7.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 56    | 0.306  | 0.242 | 13.538  | 2.3%   | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 56    | 0.019  | 0.083 | 4.644   | 0.8%   | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020212 | 1048576 | 0.05000 | 1.686 | 2.354    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000070646 | 1048576 | 0.05000 | 1.711 | 2.354    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005425 | 1048576 | 0.05000 | 1.739 | 2.354    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002427 | 1048576 | 0.05000 | 0.542 | 1.642    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000180107 | 1048576 | 0.05000 | 1.010 | 3.140    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000208475 | 1048576 | 0.05000 | 1.011 | 3.140    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008616 | 1048576 | 0.05000 | 3.496 | 17.396   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 40    | 17.396 | 6.191 | 247.628 | 38.1%  | model.layers.9:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 35840 | 0.027  | 0.005 | 176.971 | 27.3%  | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 140   | 3.505  | 0.813 | 113.877 | 17.5%  | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 126   | 0.918  | 0.338 | 42.593  | 6.6%   | model.layers.8.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 10    | 2.747  | 2.789 | 27.890  | 4.3%   | model.layers.9:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 63    | 0.595  | 0.271 | 17.053  | 2.6%   | model.layers.8.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 63    | 0.278  | 0.225 | 14.153  | 2.2%   | model.layers.8.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 63    | 0.026  | 0.087 | 5.491   | 0.8%   | model.layers.8.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.3%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000063065 | 1048576 | 0.05000 | 1.733 | 2.292    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007339 | 1048576 | 0.05000 | 1.757 | 2.292    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018305 | 1048576 | 0.05000 | 1.770 | 2.292    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003661 | 1048576 | 0.05000 | 0.541 | 1.571    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000189305 | 1048576 | 0.05000 | 0.987 | 3.139    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000166494 | 1048576 | 0.05000 | 0.992 | 3.139    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007746 | 1048576 | 0.05000 | 3.451 | 17.408   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 44    | 17.408 | 6.183 | 272.040 | 38.2%  | model.layers.10:subset4/4                        |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 39424 | 0.028  | 0.005 | 194.673 | 27.3%  | model.layers.10.mlp.down_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 154   | 3.459  | 0.813 | 125.196 | 17.6%  | model.layers.10.mlp.down_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 140   | 0.904  | 0.330 | 46.162  | 6.5%   | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 11    | 2.741  | 2.785 | 30.631  | 4.3%   | model.layers.10:subset4/4                        |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 70    | 0.580  | 0.265 | 18.522  | 2.6%   | model.layers.9.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 70    | 0.283  | 0.214 | 14.970  | 2.1%   | model.layers.9.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 70    | 0.024  | 0.089 | 6.259   | 0.9%   | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.3%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005674 | 1048576 | 0.05000 | 1.837 | 2.329    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012504 | 1048576 | 0.05000 | 1.886 | 2.329    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000047672 | 1048576 | 0.05000 | 1.903 | 2.329    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002996 | 1048576 | 0.05000 | 0.565 | 1.606    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000157805 | 1048576 | 0.05000 | 1.052 | 3.167    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000180123 | 1048576 | 0.05000 | 1.072 | 3.167    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007244 | 1048576 | 0.05000 | 3.506 | 17.417   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 48    | 17.417 | 6.178 | 296.559 | 38.2%  | model.layers.11:subset4/4                        |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 43008 | 0.028  | 0.005 | 212.354 | 27.4%  | model.layers.11.mlp.down_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 168   | 3.514  | 0.816 | 137.108 | 17.7%  | model.layers.11.mlp.down_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 154   | 0.920  | 0.323 | 49.737  | 6.4%   | model.layers.10.mlp.up_proj                      |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 12    | 2.747  | 2.782 | 33.379  | 4.3%   | model.layers.11:subset4/4                        |

INFO  +--------------------+-------+--------+-------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 77    | 0.537  | 0.260 | 20.015  | 2.6%   | model.layers.10.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 77    | 0.342  | 0.207 | 15.929  | 2.1%   | model.layers.10.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 77    | 0.016  | 0.089 | 6.886   | 0.9%   | model.layers.10.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.879  | 0.634 | 1.267   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000054048 | 1048576 | 0.05000 | 1.819 | 2.249    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007788 | 1048576 | 0.05000 | 1.875 | 2.249    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000013210 | 1048576 | 0.05000 | 1.884 | 2.249    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005131 | 1048576 | 0.05000 | 0.572 | 1.568    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000157167 | 1048576 | 0.05000 | 1.020 | 3.146    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000202403 | 1048576 | 0.05000 | 1.036 | 3.146    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007280 | 1048576 | 0.05000 | 3.500 | 17.416   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 52    | 17.416 | 6.172 | 320.939 | 38.0%  | model.layers.12:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 46592 | 0.028  | 0.005 | 230.113 | 27.2%  | model.layers.12.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 182   | 3.509  | 0.818 | 148.899 | 17.6%  | model.layers.12.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 168   | 1.235  | 0.335 | 56.339  | 6.7%   | model.layers.11.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 13    | 2.738  | 2.778 | 36.116  | 4.3%   | model.layers.12:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 84    | 0.617  | 0.270 | 22.639  | 2.7%   | model.layers.11.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 84    | 0.576  | 0.220 | 18.450  | 2.2%   | model.layers.11.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 84    | 0.017  | 0.090 | 7.531   | 0.9%   | model.layers.11.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011334 | 1048576 | 0.05000 | 1.767 | 2.268    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000042589 | 1048576 | 0.05000 | 1.804 | 2.268    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005383 | 1048576 | 0.05000 | 1.826 | 2.268    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003191 | 1048576 | 0.05000 | 0.556 | 1.567    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000156143 | 1048576 | 0.05000 | 1.013 | 3.124    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000174037 | 1048576 | 0.05000 | 1.029 | 3.124    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007016 | 1048576 | 0.05000 | 3.426 | 17.384   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 56    | 17.384 | 6.166 | 345.282 | 38.0%  | model.layers.13:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 50176 | 0.028  | 0.005 | 247.873 | 27.3%  | model.layers.13.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 196   | 3.435  | 0.818 | 160.405 | 17.7%  | model.layers.13.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 182   | 0.910  | 0.329 | 59.944  | 6.6%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 14    | 2.759  | 2.777 | 38.876  | 4.3%   | model.layers.13:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 91    | 0.576  | 0.265 | 24.135  | 2.7%   | model.layers.12.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 91    | 0.278  | 0.212 | 19.304  | 2.1%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 91    | 0.016  | 0.090 | 8.196   | 0.9%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000105545 | 1048576 | 0.05000 | 1.772 | 2.315    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000024379 | 1048576 | 0.05000 | 1.787 | 2.315    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000009583 | 1048576 | 0.05000 | 1.810 | 2.315    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002505 | 1048576 | 0.05000 | 0.555 | 1.628    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000180152 | 1048576 | 0.05000 | 1.093 | 3.145    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000178599 | 1048576 | 0.05000 | 1.107 | 3.145    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008270 | 1048576 | 0.05000 | 3.571 | 17.357   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 60    | 17.357 | 6.162 | 369.727 | 38.1%  | model.layers.14:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 53760 | 0.028  | 0.005 | 265.543 | 27.3%  | model.layers.14.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 210   | 3.580  | 0.820 | 172.195 | 17.7%  | model.layers.14.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 196   | 0.915  | 0.324 | 63.542  | 6.5%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 15    | 2.749  | 2.775 | 41.625  | 4.3%   | model.layers.14:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 98    | 0.595  | 0.262 | 25.713  | 2.6%   | model.layers.13.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 98    | 0.278  | 0.205 | 20.109  | 2.1%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 98    | 0.015  | 0.088 | 8.580   | 0.9%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000013432 | 1048576 | 0.05000 | 1.727 | 2.290    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000064572 | 1048576 | 0.05000 | 1.768 | 2.290    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011489 | 1048576 | 0.05000 | 1.782 | 2.290    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003425 | 1048576 | 0.05000 | 0.569 | 1.624    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000196291 | 1048576 | 0.05000 | 1.037 | 3.178    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000177851 | 1048576 | 0.05000 | 1.055 | 3.178    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008605 | 1048576 | 0.05000 | 3.481 | 17.397   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 64    | 17.397 | 6.160 | 394.217 | 38.1%  | model.layers.15:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 57344 | 0.028  | 0.005 | 283.331 | 27.4%  | model.layers.15.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 224   | 3.491  | 0.820 | 183.707 | 17.8%  | model.layers.15.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 210   | 0.929  | 0.320 | 67.235  | 6.5%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 16    | 2.745  | 2.773 | 44.369  | 4.3%   | model.layers.15:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 105   | 0.592  | 0.260 | 27.352  | 2.6%   | model.layers.14.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 105   | 0.296  | 0.200 | 20.956  | 2.0%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 105   | 0.008  | 0.086 | 9.033   | 0.9%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000076061 | 1048576 | 0.05000 | 1.646 | 2.260    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012764 | 1048576 | 0.05000 | 1.716 | 2.260    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000008149 | 1048576 | 0.05000 | 1.725 | 2.260    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000004907 | 1048576 | 0.05000 | 0.544 | 1.596    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000215163 | 1048576 | 0.05000 | 1.014 | 3.116    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000197649 | 1048576 | 0.05000 | 1.029 | 3.116    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000011255 | 1048576 | 0.05000 | 3.480 | 17.415   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 68    | 17.415 | 6.156 | 418.604 | 38.2%  | model.layers.16:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 60928 | 0.028  | 0.005 | 301.158 | 27.5%  | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 238   | 3.489  | 0.819 | 194.941 | 17.8%  | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 224   | 0.929  | 0.315 | 70.516  | 6.4%   | model.layers.15.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 17    | 2.738  | 2.771 | 47.107  | 4.3%   | model.layers.16:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 112   | 0.567  | 0.258 | 28.912  | 2.6%   | model.layers.15.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 112   | 0.329  | 0.196 | 21.918  | 2.0%   | model.layers.15.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 112   | 0.016  | 0.086 | 9.661   | 0.9%   | model.layers.15.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018188 | 1048576 | 0.05000 | 1.631 | 2.267    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000090832 | 1048576 | 0.05000 | 1.712 | 2.267    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000024386 | 1048576 | 0.05000 | 1.729 | 2.267    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005370 | 1048576 | 0.05000 | 0.554 | 1.625    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000255087 | 1048576 | 0.05000 | 1.064 | 3.163    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000230971 | 1048576 | 0.05000 | 1.085 | 3.163    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000016127 | 1048576 | 0.05000 | 3.520 | 17.470   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 72    | 17.470 | 6.155 | 443.128 | 38.2%  | model.layers.17:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 64512 | 0.029  | 0.005 | 319.032 | 27.5%  | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 252   | 3.530  | 0.819 | 206.340 | 17.8%  | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 238   | 0.910  | 0.310 | 73.859  | 6.4%   | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 18    | 2.748  | 2.770 | 49.855  | 4.3%   | model.layers.17:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 119   | 0.564  | 0.256 | 30.436  | 2.6%   | model.layers.16.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 119   | 0.300  | 0.190 | 22.563  | 1.9%   | model.layers.16.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 119   | 0.019  | 0.084 | 10.009  | 0.9%   | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.489  | 0.585 | 1.756   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000015440 | 1048576 | 0.05000 | 1.727 | 2.244    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000072455 | 1048576 | 0.05000 | 1.751 | 2.244    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000021615 | 1048576 | 0.05000 | 1.769 | 2.244    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000007077 | 1048576 | 0.05000 | 0.605 | 1.619    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000288446 | 1048576 | 0.05000 | 1.046 | 3.138    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000245642 | 1048576 | 0.05000 | 1.062 | 3.138    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000018548 | 1048576 | 0.05000 | 3.508 | 17.490   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 76    | 17.490 | 6.153 | 467.620 | 38.1%  | model.layers.18:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 68096 | 0.029  | 0.005 | 336.905 | 27.4%  | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 266   | 3.517  | 0.819 | 217.893 | 17.7%  | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 252   | 1.260  | 0.320 | 80.626  | 6.6%   | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 19    | 2.735  | 2.768 | 52.590  | 4.3%   | model.layers.18:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 126   | 0.606  | 0.263 | 33.094  | 2.7%   | model.layers.17.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 126   | 0.611  | 0.201 | 25.291  | 2.1%   | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 126   | 0.015  | 0.083 | 10.432  | 0.8%   | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000014402 | 1048576 | 0.05000 | 1.669 | 2.299    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000073820 | 1048576 | 0.05000 | 1.765 | 2.299    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000015829 | 1048576 | 0.05000 | 1.786 | 2.299    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005206 | 1048576 | 0.05000 | 0.553 | 1.629    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000274690 | 1048576 | 0.05000 | 1.020 | 3.154    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000321282 | 1048576 | 0.05000 | 1.049 | 3.154    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000023375 | 1048576 | 0.05000 | 3.469 | 17.451   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 80    | 17.451 | 6.152 | 492.153 | 38.1%  | model.layers.19:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 71680 | 0.028  | 0.005 | 354.677 | 27.5%  | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 280   | 3.478  | 0.819 | 229.286 | 17.8%  | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 266   | 0.908  | 0.316 | 84.156  | 6.5%   | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 20    | 2.739  | 2.766 | 55.330  | 4.3%   | model.layers.19:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 133   | 0.550  | 0.260 | 34.610  | 2.7%   | model.layers.18.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 133   | 0.314  | 0.197 | 26.176  | 2.0%   | model.layers.18.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 133   | 0.018  | 0.082 | 10.849  | 0.8%   | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016633 | 1048576 | 0.05000 | 1.732 | 2.298    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000017384 | 1048576 | 0.05000 | 1.800 | 2.298    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000078771 | 1048576 | 0.05000 | 1.816 | 2.298    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005002 | 1048576 | 0.05000 | 0.562 | 1.593    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000357247 | 1048576 | 0.05000 | 1.018 | 3.149    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000424839 | 1048576 | 0.05000 | 1.028 | 3.149    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000041025 | 1048576 | 0.05000 | 3.438 | 17.479   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 84    | 17.479 | 6.151 | 516.671 | 38.2%  | model.layers.20:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 75264 | 0.028  | 0.005 | 372.530 | 27.5%  | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 294   | 3.447  | 0.819 | 240.771 | 17.8%  | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 280   | 0.880  | 0.311 | 87.201  | 6.4%   | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 21    | 2.749  | 2.766 | 58.079  | 4.3%   | model.layers.20:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 140   | 0.561  | 0.257 | 35.939  | 2.7%   | model.layers.19.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 140   | 0.286  | 0.193 | 26.980  | 2.0%   | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 140   | 0.008  | 0.083 | 11.619  | 0.9%   | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000083885 | 1048576 | 0.05000 | 1.663 | 2.291    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016362 | 1048576 | 0.05000 | 1.703 | 2.291    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016392 | 1048576 | 0.05000 | 1.714 | 2.291    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000007541 | 1048576 | 0.05000 | 0.579 | 1.557    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000544197 | 1048576 | 0.05000 | 1.041 | 3.133    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000440954 | 1048576 | 0.05000 | 1.059 | 3.133    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000057551 | 1048576 | 0.05000 | 3.508 | 17.445   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 88    | 17.445 | 6.149 | 541.097 | 38.2%  | model.layers.21:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 78848 | 0.028  | 0.005 | 390.365 | 27.6%  | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 308   | 3.517  | 0.819 | 252.121 | 17.8%  | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 294   | 0.889  | 0.307 | 90.126  | 6.4%   | model.layers.20.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 22    | 2.735  | 2.764 | 60.814  | 4.3%   | model.layers.21:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 147   | 0.570  | 0.255 | 37.483  | 2.6%   | model.layers.20.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 147   | 0.289  | 0.189 | 27.804  | 2.0%   | model.layers.20.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 147   | 0.016  | 0.080 | 11.801  | 0.8%   | model.layers.20.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000140373 | 1048576 | 0.05000 | 1.685 | 2.273    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000057644 | 1048576 | 0.05000 | 1.709 | 2.273    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000029082 | 1048576 | 0.05000 | 1.729 | 2.273    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000009608 | 1048576 | 0.05000 | 0.577 | 1.584    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000512123 | 1048576 | 0.05000 | 1.048 | 3.192    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000629136 | 1048576 | 0.05000 | 1.069 | 3.192    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000064536 | 1048576 | 0.05000 | 3.507 | 17.472   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 92    | 17.472 | 6.148 | 565.617 | 38.2%  | model.layers.22:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 82432 | 0.029  | 0.005 | 408.224 | 27.6%  | model.layers.22.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 322   | 3.517  | 0.818 | 263.529 | 17.8%  | model.layers.22.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 308   | 0.915  | 0.305 | 93.805  | 6.3%   | model.layers.21.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 23    | 2.741  | 2.763 | 63.555  | 4.3%   | model.layers.22:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 154   | 0.522  | 0.253 | 38.988  | 2.6%   | model.layers.21.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 154   | 0.353  | 0.187 | 28.857  | 2.0%   | model.layers.21.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 154   | 0.018  | 0.079 | 12.182  | 0.8%   | model.layers.21.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000108075 | 1048576 | 0.05000 | 1.655 | 2.241    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000022384 | 1048576 | 0.05000 | 1.713 | 2.241    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000037428 | 1048576 | 0.05000 | 1.730 | 2.241    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005861 | 1048576 | 0.05000 | 0.575 | 1.551    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000525360 | 1048576 | 0.05000 | 1.059 | 3.124    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000605557 | 1048576 | 0.05000 | 1.083 | 3.124    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000068398 | 1048576 | 0.05000 | 3.482 | 17.489   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 96    | 17.489 | 6.146 | 590.023 | 38.3%  | model.layers.23:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 86016 | 0.027  | 0.005 | 425.984 | 27.6%  | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 336   | 3.492  | 0.818 | 274.913 | 17.8%  | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 322   | 0.905  | 0.301 | 96.766  | 6.3%   | model.layers.22.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 24    | 2.743  | 2.762 | 66.298  | 4.3%   | model.layers.23:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 161   | 0.535  | 0.251 | 40.473  | 2.6%   | model.layers.22.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 161   | 0.344  | 0.184 | 29.597  | 1.9%   | model.layers.22.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 161   | 0.016  | 0.077 | 12.341  | 0.8%   | model.layers.22.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.520  | 0.569 | 2.276   | 0.1%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018064 | 1048576 | 0.05000 | 1.756 | 2.278    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000081534 | 1048576 | 0.05000 | 1.807 | 2.278    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020248 | 1048576 | 0.05000 | 1.837 | 2.278    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000008862 | 1048576 | 0.05000 | 0.568 | 1.628    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000670993 | 1048576 | 0.05000 | 1.020 | 3.180    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000632831 | 1048576 | 0.05000 | 1.034 | 3.180    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000097902 | 1048576 | 0.05000 | 3.602 | 17.485   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 100   | 17.485 | 6.146 | 614.595 | 38.2%  | model.layers.24:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 89600 | 0.028  | 0.005 | 443.758 | 27.6%  | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 350   | 3.610  | 0.819 | 286.617 | 17.8%  | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 336   | 1.255  | 0.308 | 103.350 | 6.4%   | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 25    | 2.749  | 2.762 | 69.047  | 4.3%   | model.layers.24:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 168   | 0.657  | 0.261 | 43.811  | 2.7%   | model.layers.23.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 168   | 0.557  | 0.183 | 30.755  | 1.9%   | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 168   | 0.015  | 0.079 | 13.289  | 0.8%   | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000025734 | 1048576 | 0.05000 | 1.757 | 2.296    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000097769 | 1048576 | 0.05000 | 1.793 | 2.296    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000145465 | 1048576 | 0.05000 | 1.810 | 2.296    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000017882 | 1048576 | 0.05000 | 0.549 | 1.534    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000673887 | 1048576 | 0.05000 | 1.003 | 3.173    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000670318 | 1048576 | 0.05000 | 1.030 | 3.173    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000139922 | 1048576 | 0.05000 | 3.478 | 17.487   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 104   | 17.487 | 6.145 | 639.084 | 38.2%  | model.layers.25:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 93184 | 0.028  | 0.005 | 461.524 | 27.6%  | model.layers.25.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 364   | 3.489  | 0.819 | 298.120 | 17.8%  | model.layers.25.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 350   | 0.898  | 0.305 | 106.873 | 6.4%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 26    | 2.751  | 2.761 | 71.798  | 4.3%   | model.layers.25:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 175   | 0.566  | 0.258 | 45.165  | 2.7%   | model.layers.24.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 175   | 0.289  | 0.181 | 31.681  | 1.9%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 175   | 0.009  | 0.079 | 13.742  | 0.8%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020131 | 1048576 | 0.05000 | 1.642 | 2.310    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000110273 | 1048576 | 0.05000 | 1.691 | 2.310    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000083255 | 1048576 | 0.05000 | 1.713 | 2.310    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000018718 | 1048576 | 0.05000 | 0.543 | 1.565    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000642627 | 1048576 | 0.05000 | 1.078 | 3.153    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000677465 | 1048576 | 0.05000 | 1.099 | 3.153    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000213781 | 1048576 | 0.05000 | 3.463 | 17.476   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 108   | 17.476 | 6.144 | 663.589 | 38.2%  | model.layers.26:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 96768 | 0.028  | 0.005 | 479.324 | 27.6%  | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 378   | 3.472  | 0.819 | 309.432 | 17.8%  | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 364   | 0.876  | 0.303 | 110.296 | 6.4%   | model.layers.25.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.743  | 2.761 | 74.541  | 4.3%   | model.layers.26:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 182   | 0.540  | 0.256 | 46.630  | 2.7%   | model.layers.25.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 182   | 0.295  | 0.179 | 32.517  | 1.9%   | model.layers.25.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 182   | 0.017  | 0.079 | 14.441  | 0.8%   | model.layers.25.mlp.up_proj                       |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000091793 | 1048576 | 0.05000 | 1.693 | 2.350    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000118576 | 1048576 | 0.05000 | 1.698 | 2.350    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000021528 | 1048576 | 0.05000 | 1.724 | 2.350    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000052505 | 1048576 | 0.05000 | 0.535 | 1.611    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000831148 | 1048576 | 0.05000 | 1.069 | 3.126    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000882869 | 1048576 | 0.05000 | 1.084 | 3.126    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000413461 | 1048576 | 0.05000 | 3.426 | 17.434   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 112   | 17.434 | 6.144 | 688.110 | 38.3%  | model.layers.27:subset4/4                         |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 100352 | 0.028  | 0.005 | 497.110 | 27.7%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 392    | 3.435  | 0.818 | 320.766 | 17.9%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 378    | 0.933  | 0.301 | 113.825 | 6.3%   | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27     | 2.743  | 2.761 | 74.541  | 4.2%   | model.layers.26:subset4/4                         |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 189    | 0.599  | 0.254 | 48.077  | 2.7%   | model.layers.26.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 189    | 0.285  | 0.176 | 33.330  | 1.9%   | model.layers.26.mlp.gate_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 189    | 0.027  | 0.081 | 15.235  | 0.8%   | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5      | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1      | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000056309', 'samples': '1048576', 'damp': '0.05000', 'time': '2.309', 'fwd_time': '3.101', '(v)ram': 'cuda 0.69G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000010618', 'samples': '1048576', 'damp': '0.05000', 'time': '2.346', 'fwd_time': '3.101', '(v)ram': 'cuda 0.69G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000001316', 'samples': '1048576', 'damp': '0.05000', 'time': '2.366', 'fwd_time': '3.101', '(v)ram': 'cuda 0.69G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001152', 'samples': '1048576', 'damp': '0.05000', 'time': '0.537', 'fwd_time': '2.351', '(v)ram': 'cuda 0.74G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000032352', 'samples': '1048576', 'damp': '0.05000', 'time': '0.994', 'fwd_time': '3.696', '(v)ram': 'cuda 1.25G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000020776', 'samples': '1048576', 'damp': '0.05000', 'time': '1.008', 'fwd_time': '3.696', '(v)ram': 'cuda 1.25G'}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000001256', 'samples': '1048576', 'damp': '0.05000', 'time': '3.505', 'fwd_time': '17.618', '(v)ram': 'cuda 2.52G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003781', 'samples': '1048576', 'damp': '0.05000', 'time': '1.584', 'fwd_time': '2.963', '(v)ram': 'cuda 3.82G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000000500', 'samples': '1048576', 'damp': '0.05000', 'time': '1.628', 'fwd_time': '2.963', '(v)ram': 'cuda 3.82G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000011015', 'samples': '1048576', 'damp': '0.05000', 'time': '1.640', 'fwd_time': '2.963', '(v)ram': 'cuda 3.82G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000320', 'samples': '1048576', 'damp': '0.05000', 'time': '0.556', 'fwd_time': '1.604', '(v)ram': 'cuda 3.82G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000098303', 'samples': '1048576', 'damp': '0.05000', 'time': '0.986', 'fwd_time': '3.174', '(v)ram': 'cuda 4.14G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000068815', 'samples': '1048576', 'damp': '0.05000', 'time': '1.000', 'fwd_time': '3.174', '(v)ram': 'cuda 4.14G'}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000009690', 'samples': '1048576', 'damp': '0.05000', 'time': '3.549', 'fwd_time': '17.513', '(v)ram': 'cuda 5.34G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000045978', 'samples': '1048576', 'damp': '0.05000', 'time': '1.589', 'fwd_time': '2.298', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012945', 'samples': '1048576', 'damp': '0.05000', 'time': '1.614', 'fwd_time': '2.298', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003603', 'samples': '1048576', 'damp': '0.05000', 'time': '1.625', 'fwd_time': '2.298', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000822', 'samples': '1048576', 'damp': '0.05000', 'time': '0.548', 'fwd_time': '1.582', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000113527', 'samples': '1048576', 'damp': '0.05000', 'time': '0.984', 'fwd_time': '3.144', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000155993', 'samples': '1048576', 'damp': '0.05000', 'time': '1.002', 'fwd_time': '3.144', '(v)ram': 'cuda 6.85G'}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000004864', 'samples': '1048576', 'damp': '0.05000', 'time': '3.487', 'fwd_time': '17.274', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000041335', 'samples': '1048576', 'damp': '0.05000', 'time': '1.577', 'fwd_time': '2.301', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000004226', 'samples': '1048576', 'damp': '0.05000', 'time': '1.601', 'fwd_time': '2.301', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011185', 'samples': '1048576', 'damp': '0.05000', 'time': '1.614', 'fwd_time': '2.301', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000778', 'samples': '1048576', 'damp': '0.05000', 'time': '0.595', 'fwd_time': '1.620', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000201852', 'samples': '1048576', 'damp': '0.05000', 'time': '1.001', 'fwd_time': '3.111', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000145294', 'samples': '1048576', 'damp': '0.05000', 'time': '1.003', 'fwd_time': '3.111', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007827', 'samples': '1048576', 'damp': '0.05000', 'time': '3.471', 'fwd_time': '17.398', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007637', 'samples': '1048576', 'damp': '0.05000', 'time': '1.606', 'fwd_time': '2.283', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000033682', 'samples': '1048576', 'damp': '0.05000', 'time': '1.697', 'fwd_time': '2.283', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000004751', 'samples': '1048576', 'damp': '0.05000', 'time': '1.711', 'fwd_time': '2.283', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001583', 'samples': '1048576', 'damp': '0.05000', 'time': '0.553', 'fwd_time': '1.522', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000256061', 'samples': '1048576', 'damp': '0.05000', 'time': '1.032', 'fwd_time': '3.116', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000173565', 'samples': '1048576', 'damp': '0.05000', 'time': '1.051', 'fwd_time': '3.116', '(v)ram': 'cuda 7.15G'}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008416', 'samples': '1048576', 'damp': '0.05000', 'time': '3.466', 'fwd_time': '17.404', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018717', 'samples': '1048576', 'damp': '0.05000', 'time': '1.620', 'fwd_time': '2.292', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000070778', 'samples': '1048576', 'damp': '0.05000', 'time': '1.653', 'fwd_time': '2.292', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000006702', 'samples': '1048576', 'damp': '0.05000', 'time': '1.655', 'fwd_time': '2.292', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001619', 'samples': '1048576', 'damp': '0.05000', 'time': '0.552', 'fwd_time': '1.584', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000200622', 'samples': '1048576', 'damp': '0.05000', 'time': '0.990', 'fwd_time': '3.095', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000322532', 'samples': '1048576', 'damp': '0.05000', 'time': '0.991', 'fwd_time': '3.095', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000009453', 'samples': '1048576', 'damp': '0.05000', 'time': '3.466', 'fwd_time': '17.400', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000014397', 'samples': '1048576', 'damp': '0.05000', 'time': '1.826', 'fwd_time': '2.305', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000064795', 'samples': '1048576', 'damp': '0.05000', 'time': '1.837', 'fwd_time': '2.305', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007732', 'samples': '1048576', 'damp': '0.05000', 'time': '1.846', 'fwd_time': '2.305', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002396', 'samples': '1048576', 'damp': '0.05000', 'time': '0.581', 'fwd_time': '1.641', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000314785', 'samples': '1048576', 'damp': '0.05000', 'time': '1.030', 'fwd_time': '3.177', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000209109', 'samples': '1048576', 'damp': '0.05000', 'time': '1.049', 'fwd_time': '3.177', '(v)ram': 'cuda 7.45G'}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010699', 'samples': '1048576', 'damp': '0.05000', 'time': '3.532', 'fwd_time': '17.515', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003942', 'samples': '1048576', 'damp': '0.05000', 'time': '1.626', 'fwd_time': '2.316', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000042389', 'samples': '1048576', 'damp': '0.05000', 'time': '1.671', 'fwd_time': '2.316', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011219', 'samples': '1048576', 'damp': '0.05000', 'time': '1.683', 'fwd_time': '2.316', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001850', 'samples': '1048576', 'damp': '0.05000', 'time': '0.543', 'fwd_time': '1.563', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000198315', 'samples': '1048576', 'damp': '0.05000', 'time': '0.974', 'fwd_time': '3.128', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000243999', 'samples': '1048576', 'damp': '0.05000', 'time': '0.991', 'fwd_time': '3.128', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010823', 'samples': '1048576', 'damp': '0.05000', 'time': '3.474', 'fwd_time': '17.456', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005268', 'samples': '1048576', 'damp': '0.05000', 'time': '1.679', 'fwd_time': '2.372', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000035448', 'samples': '1048576', 'damp': '0.05000', 'time': '1.724', 'fwd_time': '2.372', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000008396', 'samples': '1048576', 'damp': '0.05000', 'time': '1.739', 'fwd_time': '2.372', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000004689', 'samples': '1048576', 'damp': '0.05000', 'time': '0.594', 'fwd_time': '1.607', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000185360', 'samples': '1048576', 'damp': '0.05000', 'time': '1.006', 'fwd_time': '3.149', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000247648', 'samples': '1048576', 'damp': '0.05000', 'time': '1.038', 'fwd_time': '3.149', '(v)ram': 'cuda 7.75G'}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010378', 'samples': '1048576', 'damp': '0.05000', 'time': '3.539', 'fwd_time': '17.421', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020212', 'samples': '1048576', 'damp': '0.05000', 'time': '1.686', 'fwd_time': '2.354', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000070646', 'samples': '1048576', 'damp': '0.05000', 'time': '1.711', 'fwd_time': '2.354', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005425', 'samples': '1048576', 'damp': '0.05000', 'time': '1.739', 'fwd_time': '2.354', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002427', 'samples': '1048576', 'damp': '0.05000', 'time': '0.542', 'fwd_time': '1.642', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000180107', 'samples': '1048576', 'damp': '0.05000', 'time': '1.010', 'fwd_time': '3.140', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000208475', 'samples': '1048576', 'damp': '0.05000', 'time': '1.011', 'fwd_time': '3.140', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008616', 'samples': '1048576', 'damp': '0.05000', 'time': '3.496', 'fwd_time': '17.396', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000063065', 'samples': '1048576', 'damp': '0.05000', 'time': '1.733', 'fwd_time': '2.292', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007339', 'samples': '1048576', 'damp': '0.05000', 'time': '1.757', 'fwd_time': '2.292', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018305', 'samples': '1048576', 'damp': '0.05000', 'time': '1.770', 'fwd_time': '2.292', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003661', 'samples': '1048576', 'damp': '0.05000', 'time': '0.541', 'fwd_time': '1.571', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000189305', 'samples': '1048576', 'damp': '0.05000', 'time': '0.987', 'fwd_time': '3.139', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000166494', 'samples': '1048576', 'damp': '0.05000', 'time': '0.992', 'fwd_time': '3.139', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007746', 'samples': '1048576', 'damp': '0.05000', 'time': '3.451', 'fwd_time': '17.408', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005674', 'samples': '1048576', 'damp': '0.05000', 'time': '1.837', 'fwd_time': '2.329', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012504', 'samples': '1048576', 'damp': '0.05000', 'time': '1.886', 'fwd_time': '2.329', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000047672', 'samples': '1048576', 'damp': '0.05000', 'time': '1.903', 'fwd_time': '2.329', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002996', 'samples': '1048576', 'damp': '0.05000', 'time': '0.565', 'fwd_time': '1.606', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000157805', 'samples': '1048576', 'damp': '0.05000', 'time': '1.052', 'fwd_time': '3.167', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000180123', 'samples': '1048576', 'damp': '0.05000', 'time': '1.072', 'fwd_time': '3.167', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007244', 'samples': '1048576', 'damp': '0.05000', 'time': '3.506', 'fwd_time': '17.417', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000054048', 'samples': '1048576', 'damp': '0.05000', 'time': '1.819', 'fwd_time': '2.249', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007788', 'samples': '1048576', 'damp': '0.05000', 'time': '1.875', 'fwd_time': '2.249', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000013210', 'samples': '1048576', 'damp': '0.05000', 'time': '1.884', 'fwd_time': '2.249', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005131', 'samples': '1048576', 'damp': '0.05000', 'time': '0.572', 'fwd_time': '1.568', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000157167', 'samples': '1048576', 'damp': '0.05000', 'time': '1.020', 'fwd_time': '3.146', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000202403', 'samples': '1048576', 'damp': '0.05000', 'time': '1.036', 'fwd_time': '3.146', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007280', 'samples': '1048576', 'damp': '0.05000', 'time': '3.500', 'fwd_time': '17.416', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011334', 'samples': '1048576', 'damp': '0.05000', 'time': '1.767', 'fwd_time': '2.268', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000042589', 'samples': '1048576', 'damp': '0.05000', 'time': '1.804', 'fwd_time': '2.268', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005383', 'samples': '1048576', 'damp': '0.05000', 'time': '1.826', 'fwd_time': '2.268', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003191', 'samples': '1048576', 'damp': '0.05000', 'time': '0.556', 'fwd_time': '1.567', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000156143', 'samples': '1048576', 'damp': '0.05000', 'time': '1.013', 'fwd_time': '3.124', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000174037', 'samples': '1048576', 'damp': '0.05000', 'time': '1.029', 'fwd_time': '3.124', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007016', 'samples': '1048576', 'damp': '0.05000', 'time': '3.426', 'fwd_time': '17.384', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000105545', 'samples': '1048576', 'damp': '0.05000', 'time': '1.772', 'fwd_time': '2.315', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000024379', 'samples': '1048576', 'damp': '0.05000', 'time': '1.787', 'fwd_time': '2.315', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000009583', 'samples': '1048576', 'damp': '0.05000', 'time': '1.810', 'fwd_time': '2.315', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002505', 'samples': '1048576', 'damp': '0.05000', 'time': '0.555', 'fwd_time': '1.628', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000180152', 'samples': '1048576', 'damp': '0.05000', 'time': '1.093', 'fwd_time': '3.145', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000178599', 'samples': '1048576', 'damp': '0.05000', 'time': '1.107', 'fwd_time': '3.145', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008270', 'samples': '1048576', 'damp': '0.05000', 'time': '3.571', 'fwd_time': '17.357', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000013432', 'samples': '1048576', 'damp': '0.05000', 'time': '1.727', 'fwd_time': '2.290', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000064572', 'samples': '1048576', 'damp': '0.05000', 'time': '1.768', 'fwd_time': '2.290', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011489', 'samples': '1048576', 'damp': '0.05000', 'time': '1.782', 'fwd_time': '2.290', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003425', 'samples': '1048576', 'damp': '0.05000', 'time': '0.569', 'fwd_time': '1.624', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000196291', 'samples': '1048576', 'damp': '0.05000', 'time': '1.037', 'fwd_time': '3.178', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000177851', 'samples': '1048576', 'damp': '0.05000', 'time': '1.055', 'fwd_time': '3.178', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008605', 'samples': '1048576', 'damp': '0.05000', 'time': '3.481', 'fwd_time': '17.397', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000076061', 'samples': '1048576', 'damp': '0.05000', 'time': '1.646', 'fwd_time': '2.260', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012764', 'samples': '1048576', 'damp': '0.05000', 'time': '1.716', 'fwd_time': '2.260', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000008149', 'samples': '1048576', 'damp': '0.05000', 'time': '1.725', 'fwd_time': '2.260', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000004907', 'samples': '1048576', 'damp': '0.05000', 'time': '0.544', 'fwd_time': '1.596', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000215163', 'samples': '1048576', 'damp': '0.05000', 'time': '1.014', 'fwd_time': '3.116', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000197649', 'samples': '1048576', 'damp': '0.05000', 'time': '1.029', 'fwd_time': '3.116', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000011255', 'samples': '1048576', 'damp': '0.05000', 'time': '3.480', 'fwd_time': '17.415', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018188', 'samples': '1048576', 'damp': '0.05000', 'time': '1.631', 'fwd_time': '2.267', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000090832', 'samples': '1048576', 'damp': '0.05000', 'time': '1.712', 'fwd_time': '2.267', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000024386', 'samples': '1048576', 'damp': '0.05000', 'time': '1.729', 'fwd_time': '2.267', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005370', 'samples': '1048576', 'damp': '0.05000', 'time': '0.554', 'fwd_time': '1.625', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000255087', 'samples': '1048576', 'damp': '0.05000', 'time': '1.064', 'fwd_time': '3.163', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000230971', 'samples': '1048576', 'damp': '0.05000', 'time': '1.085', 'fwd_time': '3.163', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000016127', 'samples': '1048576', 'damp': '0.05000', 'time': '3.520', 'fwd_time': '17.470', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000015440', 'samples': '1048576', 'damp': '0.05000', 'time': '1.727', 'fwd_time': '2.244', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000072455', 'samples': '1048576', 'damp': '0.05000', 'time': '1.751', 'fwd_time': '2.244', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000021615', 'samples': '1048576', 'damp': '0.05000', 'time': '1.769', 'fwd_time': '2.244', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000007077', 'samples': '1048576', 'damp': '0.05000', 'time': '0.605', 'fwd_time': '1.619', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000288446', 'samples': '1048576', 'damp': '0.05000', 'time': '1.046', 'fwd_time': '3.138', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000245642', 'samples': '1048576', 'damp': '0.05000', 'time': '1.062', 'fwd_time': '3.138', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000018548', 'samples': '1048576', 'damp': '0.05000', 'time': '3.508', 'fwd_time': '17.490', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000014402', 'samples': '1048576', 'damp': '0.05000', 'time': '1.669', 'fwd_time': '2.299', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000073820', 'samples': '1048576', 'damp': '0.05000', 'time': '1.765', 'fwd_time': '2.299', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000015829', 'samples': '1048576', 'damp': '0.05000', 'time': '1.786', 'fwd_time': '2.299', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005206', 'samples': '1048576', 'damp': '0.05000', 'time': '0.553', 'fwd_time': '1.629', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000274690', 'samples': '1048576', 'damp': '0.05000', 'time': '1.020', 'fwd_time': '3.154', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000321282', 'samples': '1048576', 'damp': '0.05000', 'time': '1.049', 'fwd_time': '3.154', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000023375', 'samples': '1048576', 'damp': '0.05000', 'time': '3.469', 'fwd_time': '17.451', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016633', 'samples': '1048576', 'damp': '0.05000', 'time': '1.732', 'fwd_time': '2.298', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000017384', 'samples': '1048576', 'damp': '0.05000', 'time': '1.800', 'fwd_time': '2.298', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000078771', 'samples': '1048576', 'damp': '0.05000', 'time': '1.816', 'fwd_time': '2.298', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005002', 'samples': '1048576', 'damp': '0.05000', 'time': '0.562', 'fwd_time': '1.593', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000357247', 'samples': '1048576', 'damp': '0.05000', 'time': '1.018', 'fwd_time': '3.149', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000424839', 'samples': '1048576', 'damp': '0.05000', 'time': '1.028', 'fwd_time': '3.149', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000041025', 'samples': '1048576', 'damp': '0.05000', 'time': '3.438', 'fwd_time': '17.479', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000083885', 'samples': '1048576', 'damp': '0.05000', 'time': '1.663', 'fwd_time': '2.291', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016362', 'samples': '1048576', 'damp': '0.05000', 'time': '1.703', 'fwd_time': '2.291', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016392', 'samples': '1048576', 'damp': '0.05000', 'time': '1.714', 'fwd_time': '2.291', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000007541', 'samples': '1048576', 'damp': '0.05000', 'time': '0.579', 'fwd_time': '1.557', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000544197', 'samples': '1048576', 'damp': '0.05000', 'time': '1.041', 'fwd_time': '3.133', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000440954', 'samples': '1048576', 'damp': '0.05000', 'time': '1.059', 'fwd_time': '3.133', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000057551', 'samples': '1048576', 'damp': '0.05000', 'time': '3.508', 'fwd_time': '17.445', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000140373', 'samples': '1048576', 'damp': '0.05000', 'time': '1.685', 'fwd_time': '2.273', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000057644', 'samples': '1048576', 'damp': '0.05000', 'time': '1.709', 'fwd_time': '2.273', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000029082', 'samples': '1048576', 'damp': '0.05000', 'time': '1.729', 'fwd_time': '2.273', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000009608', 'samples': '1048576', 'damp': '0.05000', 'time': '0.577', 'fwd_time': '1.584', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000512123', 'samples': '1048576', 'damp': '0.05000', 'time': '1.048', 'fwd_time': '3.192', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000629136', 'samples': '1048576', 'damp': '0.05000', 'time': '1.069', 'fwd_time': '3.192', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000064536', 'samples': '1048576', 'damp': '0.05000', 'time': '3.507', 'fwd_time': '17.472', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000108075', 'samples': '1048576', 'damp': '0.05000', 'time': '1.655', 'fwd_time': '2.241', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000022384', 'samples': '1048576', 'damp': '0.05000', 'time': '1.713', 'fwd_time': '2.241', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000037428', 'samples': '1048576', 'damp': '0.05000', 'time': '1.730', 'fwd_time': '2.241', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005861', 'samples': '1048576', 'damp': '0.05000', 'time': '0.575', 'fwd_time': '1.551', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000525360', 'samples': '1048576', 'damp': '0.05000', 'time': '1.059', 'fwd_time': '3.124', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000605557', 'samples': '1048576', 'damp': '0.05000', 'time': '1.083', 'fwd_time': '3.124', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000068398', 'samples': '1048576', 'damp': '0.05000', 'time': '3.482', 'fwd_time': '17.489', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018064', 'samples': '1048576', 'damp': '0.05000', 'time': '1.756', 'fwd_time': '2.278', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000081534', 'samples': '1048576', 'damp': '0.05000', 'time': '1.807', 'fwd_time': '2.278', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020248', 'samples': '1048576', 'damp': '0.05000', 'time': '1.837', 'fwd_time': '2.278', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000008862', 'samples': '1048576', 'damp': '0.05000', 'time': '0.568', 'fwd_time': '1.628', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000670993', 'samples': '1048576', 'damp': '0.05000', 'time': '1.020', 'fwd_time': '3.180', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000632831', 'samples': '1048576', 'damp': '0.05000', 'time': '1.034', 'fwd_time': '3.180', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000097902', 'samples': '1048576', 'damp': '0.05000', 'time': '3.602', 'fwd_time': '17.485', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000025734', 'samples': '1048576', 'damp': '0.05000', 'time': '1.757', 'fwd_time': '2.296', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000097769', 'samples': '1048576', 'damp': '0.05000', 'time': '1.793', 'fwd_time': '2.296', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000145465', 'samples': '1048576', 'damp': '0.05000', 'time': '1.810', 'fwd_time': '2.296', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000017882', 'samples': '1048576', 'damp': '0.05000', 'time': '0.549', 'fwd_time': '1.534', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000673887', 'samples': '1048576', 'damp': '0.05000', 'time': '1.003', 'fwd_time': '3.173', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000670318', 'samples': '1048576', 'damp': '0.05000', 'time': '1.030', 'fwd_time': '3.173', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000139922', 'samples': '1048576', 'damp': '0.05000', 'time': '3.478', 'fwd_time': '17.487', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020131', 'samples': '1048576', 'damp': '0.05000', 'time': '1.642', 'fwd_time': '2.310', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000110273', 'samples': '1048576', 'damp': '0.05000', 'time': '1.691', 'fwd_time': '2.310', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000083255', 'samples': '1048576', 'damp': '0.05000', 'time': '1.713', 'fwd_time': '2.310', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000018718', 'samples': '1048576', 'damp': '0.05000', 'time': '0.543', 'fwd_time': '1.565', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000642627', 'samples': '1048576', 'damp': '0.05000', 'time': '1.078', 'fwd_time': '3.153', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000677465', 'samples': '1048576', 'damp': '0.05000', 'time': '1.099', 'fwd_time': '3.153', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000213781', 'samples': '1048576', 'damp': '0.05000', 'time': '3.463', 'fwd_time': '17.476', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000091793', 'samples': '1048576', 'damp': '0.05000', 'time': '1.693', 'fwd_time': '2.350', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000118576', 'samples': '1048576', 'damp': '0.05000', 'time': '1.698', 'fwd_time': '2.350', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000021528', 'samples': '1048576', 'damp': '0.05000', 'time': '1.724', 'fwd_time': '2.350', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000052505', 'samples': '1048576', 'damp': '0.05000', 'time': '0.535', 'fwd_time': '1.611', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000831148', 'samples': '1048576', 'damp': '0.05000', 'time': '1.069', 'fwd_time': '3.126', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000882869', 'samples': '1048576', 'damp': '0.05000', 'time': '1.084', 'fwd_time': '3.126', '(v)ram': 'cuda 8.05G'}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000413461', 'samples': '1048576', 'damp': '0.05000', 'time': '3.426', 'fwd_time': '17.434', '(v)ram': 'cuda 8.05G'}

INFO  tp-pre-pad summary:
[]

INFO  | Pre-quant forward  | 112    | 17.434 | 6.144 | 688.110 | 38.2%  | model.layers.27:subset4/4                         |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 100352 | 0.028  | 0.005 | 497.110 | 27.6%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 392    | 3.435  | 0.818 | 320.766 | 17.8%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 392    | 0.808  | 0.298 | 116.785 | 6.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27     | 2.743  | 2.761 | 74.541  | 4.1%   | model.layers.26:subset4/4                         |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 196    | 0.517  | 0.252 | 49.376  | 2.7%   | model.layers.27.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 196    | 0.255  | 0.173 | 33.890  | 1.9%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 196    | 0.014  | 0.081 | 15.865  | 0.9%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5      | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1      | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process finalize   | 2      | 0.000  | 0.000 | 0.001   | 0.0%   | tp-pre-pad                                        |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

Writing model shards: 0it [00:00, ?it/s]

INFO  Saved Quantize Config:
{
  "bits": 4,
  "group_size": 128,
  "desc_act": false,
  "lm_head": false,
  "quant_method": "gptq",
  "checkpoint_format": "gptq",
  "pack_dtype": "int32",
  "meta": {
    "quantizer": [
      "gptqmodel:5.7.0"
    ],
    "uri": "https://github.com/modelcloud/gptqmodel",
    "damp_percent": 0.05,
    "damp_auto_increment": 0.01,
    "static_groups": false,
    "true_sequential": true,
    "mse": 0.0,
    "gptaq": null,
    "act_group_aware": true,
    "failsafe": {
      "strategy": "rtn",
      "threshold": "0.5%",
      "smooth": {
        "type": "mad",
        "group_size_threshold": 128,
        "k": 2.75
      }
    },
    "offload_to_disk": true,
    "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
    "pack_impl": "cpu",
    "mock_quantization": false,
    "gc_mode": "interval",
    "wait_for_submodule_finalizers": false,
    "auto_forward_data_parallel": true,
    "hessian": {
      "chunk_size": null,
      "chunk_bytes": null,
      "staging_dtype": "float32"
    },
    "vram_strategy": "exclusive"
  },
  "sym": true,
  "format": "gptq"
}

Files in directory:
quant_log.csv
quantize_config.json
generation_config.json
config.json
Content of saved `generation_config.json`:
{
    "bos_token_id": 151643,
    "do_sample": true,
    "eos_token_id": 151643,
    "max_new_tokens": 2048,
    "transformers_version": "5.0.0"
}
Content of saved `config.json`:
{
    "architectures": [
        "Qwen2ForCausalLM"
    ],
    "attention_dropout": 0.0,
    "bos_token_id": 151643,
    "dtype": "bfloat16",
    "eos_token_id": 151643,
    "hidden_act": "silu",
    "hidden_size": 1536,
    "initializer_range": 0.02,
    "intermediate_size": 8960,
    "layer_types": [
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention"
    ],
    "max_position_embeddings": 131072,
    "max_window_layers": 28,
    "model_type": "qwen2",
    "num_attention_heads": 12,
    "num_hidden_layers": 28,
    "num_key_value_heads": 2,
    "pad_token_id": null,
    "quantization_config": {
        "bits": 4,
        "checkpoint_format": "gptq",
        "desc_act": false,
        "format": "gptq",
        "group_size": 128,
        "lm_head": false,
        "meta": {
            "act_group_aware": true,
            "auto_forward_data_parallel": true,
            "damp_auto_increment": 0.01,
            "damp_percent": 0.05,
            "failsafe": {
                "smooth": {
                    "group_size_threshold": 128,
                    "k": 2.75,
                    "type": "mad"
                },
                "strategy": "rtn",
                "threshold": "0.5%"
            },
            "gc_mode": "interval",
            "gptaq": null,
            "hessian": {
                "chunk_bytes": null,
                "chunk_size": null,
                "staging_dtype": "float32"
            },
            "mock_quantization": false,
            "mse": 0.0,
            "offload_to_disk": true,
            "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
            "pack_impl": "cpu",
            "quantizer": [
                "gptqmodel:5.7.0"
            ],
            "static_groups": false,
            "true_sequential": true,
            "uri": "https://github.com/modelcloud/gptqmodel",
            "vram_strategy": "exclusive",
            "wait_for_submodule_finalizers": false
        },
        "pack_dtype": "int32",
        "quant_method": "gptq",
        "sym": true
    },
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
        "rope_theta": 1000000.0,
        "rope_type": "default"
    },
    "sliding_window": null,
    "tie_word_embeddings": true,
    "transformers_version": "5.0.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
}

INFO  Module: Sync model.embed_tokens <- from turtle (Embedding)

INFO  Module: Sync lm_head <- from turtle (Linear)

INFO  Module: Re-tied embedding weights on shell model after full sync

INFO  Module: Total synced modules: 2

INFO  Pre-Quantized model size: 2944.44MB, 2.88GB

INFO  Quantized model size: 1096.59MB, 1.07GB

INFO  Size difference: 1847.84MB, 1.80GB - 62.76%

INFO  | Pre-quant forward  | 112    | 17.434 | 6.144 | 688.110 | 38.2%  | model.layers.27:subset4/4                         |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 100352 | 0.028  | 0.005 | 497.110 | 27.6%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 392    | 3.435  | 0.818 | 320.766 | 17.8%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 392    | 0.808  | 0.298 | 116.785 | 6.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27     | 2.743  | 2.761 | 74.541  | 4.1%   | model.layers.26:subset4/4                         |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 196    | 0.517  | 0.252 | 49.376  | 2.7%   | model.layers.27.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 196    | 0.255  | 0.173 | 33.890  | 1.9%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 196    | 0.014  | 0.081 | 15.865  | 0.9%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5      | 0.531  | 0.561 | 2.807   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1      | 2.202  | 2.202 | 2.202   | 0.1%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Model save         | 1      | 1.698  | 1.698 | 1.698   | 0.1%   | /content/artifacts/gptq_w4_g128/full_quant        |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

INFO  | Process finalize   | 2      | 0.000  | 0.000 | 0.001   | 0.0%   | tp-pre-pad                                        |

INFO  +--------------------+--------+--------+-------+---------+--------+---------------------------------------------------+

2026-03-09 22:33:44,810 | INFO    | Quantization finished in 16:25
2026-03-09 22:35:12,814 | INFO    | Created zip: /content/zip_bundles/gptq_w4_g128_full_quant/full_quant/full_quant_quantized_model.zip (910.57 MB)

Quantized artifact ready.
{
  "variant": "full_quant",
  "base_model": "Qwen/Qwen2-1.5B",
  "quant": {
    "bits": 4,
    "group_size": 128,
    "desc_act": false
  },
  "artifact_dir": "/content/artifacts/gptq_w4_g128/full_quant",
  "gptq_model_file": "model.safetensors",
  "quantization_elapsed_sec": 985.466757774353,
  "model_size_gb": 1.0709,
  "bits_per_param": 5.5627,
  "created_at_unix": 1773095624.8650641
}

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,gsm8k_accuracy,arc_accuracy
0,full_quant,GPTQ W4 g128,1.0709,None,5.5627,None,None

In [ ]:
# Evaluation helpers for GSM8K and ARC-Challenge only

GSM_PROMPT = "Question: {question} Answer: Let's think step by step."


def evaluate_gsm8k_only(model, tokenizer, cfg):
    gsm_cfg = cfg['eval']['gsm8k']
    n_shot = gsm_cfg['num_fewshot']
    num_samples = gsm_cfg['num_samples']
    max_new = gsm_cfg['max_new_tokens']
    log_every = gsm_cfg.get('log_every', 25)

    logger.info('Loading GSM8K: %d-shot, %d samples, max_new_tokens=%d', n_shot, num_samples, max_new)
    train_ds = load_dataset('openai/gsm8k', 'main', split='train').shuffle(seed=42)
    test_ds = load_dataset('openai/gsm8k', 'main', split='test').shuffle(seed=42).select(range(num_samples))
    exemplars = train_ds.select(range(n_shot))

    prefix = ''
    for ex in exemplars:
        prefix += GSM_PROMPT.format(question=ex['question']) + ex['answer'] + '\n\n'

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(test_ds)

    for idx, row in enumerate(tqdm(test_ds, desc='GSM8K', unit='q'), start=1):
        prompt = prefix + GSM_PROMPT.format(question=row['question'])

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new)
        pred = extract_numeric_answer(generated)
        gold = extract_numeric_answer(row['answer'])
        is_correct = pred is not None and gold is not None and abs(pred - gold) < 1e-3
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_value': pred,
            'gold_value': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('GSM8K', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'gsm8k',
        'num_fewshot': n_shot,
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'gsm8k_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'gsm8k_metrics.json')

    state = get_results_state()
    state['gsm8k'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    logger.info('GSM8K finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    return result


def format_arc_prompt(row):
    labels = row['choices']['label']
    texts = row['choices']['text']
    prompt = row['question'] + '\n'
    for lbl, txt in zip(labels, texts):
        prompt += f'{lbl}. {txt}\n'
    prompt += 'Answer:'
    return prompt


def evaluate_arc_only(model, tokenizer, cfg):
    arc_cfg = cfg['eval']['arc_challenge']
    num_samples = arc_cfg['num_samples']
    max_new = arc_cfg['max_new_tokens']
    log_every = arc_cfg.get('log_every', 50)

    logger.info('Loading ARC-Challenge: %d samples, max_new_tokens=%d', num_samples, max_new)
    ds = load_dataset('allenai/ai2_arc', 'ARC-Challenge', split='test').shuffle(seed=42).select(range(num_samples))

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(ds)

    for idx, row in enumerate(tqdm(ds, desc='ARC-Challenge', unit='q'), start=1):
        prompt = format_arc_prompt(row)

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new).strip()
        pred = generated[:1].upper() if generated else None
        gold = row['answerKey'].strip().upper()
        is_correct = pred == gold
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_label': pred,
            'gold_label': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('ARC-Challenge', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'arc_challenge',
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'arc_challenge_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'arc_challenge_metrics.json')

    state = get_results_state()
    state['arc_challenge'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    results_zip = zip_directory(RESULTS_DIR, BUNDLE_DIR / 'full_quant_results_only.zip')
    state['results_zip'] = str(results_zip)
    save_results_state(state)

    logger.info('ARC-Challenge finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    print('Results zip:', results_zip)
    return result

In [ ]:

# Cell 2 — Evaluate on GSM8K only
# Run this after the quantization cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    gsm8k_result = evaluate_gsm8k_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

In [14]:

# Cell 3 — Evaluate on ARC-Challenge only and finalize the summary/results zip
# Run this after the GSM8K cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/pnnvijib-iqbxrhpb/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-09 23:09:06,232 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  gc.collect() reclaimed 143 objects in 0.336s

2026-03-09 23:09:07,874 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

2026-03-09 23:09:07,993 | INFO    | Loading ARC-Challenge: 500 samples, max_new_tokens=5
2026-03-09 23:09:08,233 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:09:08,495 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/allenai/ai2_arc/210d026faf9955653af8916fad021475a3f00453/README.md "HTTP/1.1 200 OK"
2026-03-09 23:09:08,738 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/allenai/ai2_arc/210d026faf9955653af8916fad021475a3f00453/README.md "HTTP/1.1 200 OK"

README.md: 0.00B [00:00, ?B/s]

2026-03-09 23:09:08,979 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-09 23:09:09,659 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/allenai/ai2_arc/allenai/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-09 23:09:10,232 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/revision/210d026faf9955653af8916fad021475a3f00453 "HTTP/1.1 200 OK"
2026-03-09 23:09:10,468 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-09 23:09:10,734 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=allenai/ai2_arc "HTTP/1.1 200 OK"
2026-03-09 23:09:10,971 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:09:11,200 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:09:11,446 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/revision/210d026faf9955653af8916fad021475a3f00453 "HTTP/1.1 200 OK"
2026-03-09 23:09:11,690 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-03-09 23:09:11,936 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/train-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-03-09 23:09:12,176 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/xet-read-token/210d026faf9955653af8916fad021475a3f00453 "HTTP/1.1 200 OK"

ARC-Challenge/train-00000-of-00001.parqu(…):   0%|          | 0.00/190k [00:00<?, ?B/s]

2026-03-09 23:09:13,429 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/test-00000-of-00001.parquet "HTTP/1.1 302 Found"

ARC-Challenge/test-00000-of-00001.parque(…):   0%|          | 0.00/204k [00:00<?, ?B/s]

2026-03-09 23:09:14,031 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/validation-00000-of-00001.parquet "HTTP/1.1 302 Found"

ARC-Challenge/validation-00000-of-00001.(…):   0%|          | 0.00/55.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1119 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1172 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/299 [00:00<?, ? examples/s]

ARC-Challenge:   0%|          | 0/500 [00:00<?, ?q/s]

2026-03-09 23:09:33,249 | INFO    | ARC-Challenge | 50/500 | acc=0.6200 | elapsed=0:18 | eta=2:49 | 0.38s/item
2026-03-09 23:09:51,940 | INFO    | ARC-Challenge | 100/500 | acc=0.6500 | elapsed=0:37 | eta=2:30 | 0.38s/item
2026-03-09 23:10:10,604 | INFO    | ARC-Challenge | 150/500 | acc=0.6333 | elapsed=0:56 | eta=2:11 | 0.37s/item
2026-03-09 23:10:29,167 | INFO    | ARC-Challenge | 200/500 | acc=0.6200 | elapsed=1:14 | eta=1:52 | 0.37s/item
2026-03-09 23:10:47,753 | INFO    | ARC-Challenge | 250/500 | acc=0.6480 | elapsed=1:33 | eta=1:33 | 0.37s/item
2026-03-09 23:11:06,425 | INFO    | ARC-Challenge | 300/500 | acc=0.6433 | elapsed=1:51 | eta=1:14 | 0.37s/item
2026-03-09 23:11:25,032 | INFO    | ARC-Challenge | 350/500 | acc=0.6371 | elapsed=2:10 | eta=0:55 | 0.37s/item
2026-03-09 23:11:43,613 | INFO    | ARC-Challenge | 400/500 | acc=0.6325 | elapsed=2:29 | eta=0:37 | 0.37s/item
2026-03-09 23:12:02,212 | INFO    | ARC-Challenge | 450/500 | acc=0.6244 | elapsed=2:47 | eta=0:18 | 0.37s/item
2026-03-09 23:12:20,826 | INFO    | ARC-Challenge | 500/500 | acc=0.6180 | elapsed=3:06 | eta=0:00 | 0.37s/item
2026-03-09 23:12:20,844 | INFO    | Created zip: /content/zip_bundles/gptq_w4_g128_full_quant/full_quant/full_quant_results_only.zip (0.03 MB)
2026-03-09 23:12:20,845 | INFO    | ARC-Challenge finished | acc=0.6180 | elapsed=3:06 | peak_vram_gb=6.756505489349365

,dataset,num_samples,max_new_tokens,accuracy,correct,elapsed_sec,elapsed_hms,peak_vram_gb
0,arc_challenge,500,5,0.618,309,186.393611,3:06,6.756505

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,gsm8k_accuracy,arc_accuracy
0,full_quant,GPTQ W4 g128,1.0709,6.7565,5.5627,None,0.618

Results zip: /content/zip_bundles/gptq_w4_g128_full_quant/full_quant/full_quant_results_only.zip

In [16]:
import os
import json
import pandas as pd

summary = {
    "variant": "full_quant",
    "compression": "GPTQ",
    "model_size_gb": float(quant_manifest['model_size_gb']),
    "peak_vram_gb": float(arc_result['peak_vram_gb']),
    "bits_per_param": float(quant_manifest['bits_per_param']),
    "perplexity": None,
    "arc_accuracy": None,
}

ppl_path = os.path.join(RESULTS_DIR, "perplexity_metrics.json")
arc_path = os.path.join(RESULTS_DIR, "arc_challenge_metrics.json")

if os.path.exists(ppl_path):
    with open(ppl_path, "r") as f:
        ppl_data = json.load(f)
    summary["perplexity"] = ppl_data.get("perplexity")


if os.path.exists(arc_path):
    with open(arc_path, "r") as f:
        arc_data = json.load(f)
    summary["arc_accuracy"] = arc_data.get("accuracy")

summary_json_path = os.path.join(RESULTS_DIR, "summary.json")
summary_csv_path = os.path.join(RESULTS_DIR, "summary.csv")

with open(summary_json_path, "w") as f:
    json.dump(summary, f, indent=2)

pd.DataFrame([summary]).to_csv(summary_csv_path, index=False)

print(pd.DataFrame([summary]))

      variant compression  model_size_gb  peak_vram_gb  bits_per_param  \
0  full_quant        GPTQ         1.0709      6.756505          5.5627

   perplexity  arc_accuracy
0    8.894765         0.618