# GPTQ attention-only notebook — Perplexity + GSM8K + ARC-Challenge

This notebook runs the same execution order as the full-quant notebook, but for **Qwen2-1.5B attention-only GPTQ quantization**:

1. quantize and save the model artifact
2. evaluate **Perplexity** on WikiText-2
3. evaluate **GSM8K**
4. evaluate **ARC-Challenge**

It saves:
- quantized GPTQ artifact folder
- quantized model zip
- perplexity / GSM8K / ARC-Challenge metrics and predictions
- summary table row
- results-only zip

In [ ]:

# Colab / notebook setup
!pip install -U pip setuptools wheel
!pip install -U gptqmodel
!pip install -q torch transformers accelerate datasets pandas pyarrow safetensors tqdm

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (75.2.0)
Collecting setuptools
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from wheel) (26.0)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 87.8 MB/s eta 0:00:00
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 72.1 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Successfully installed pip-26.0.1 setuptools-82.0.1

Collecting gptqmodel
  Downloading gptqmodel-5.7.0.tar.gz (668 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.4/668.4 kB 29.3 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate>=1.10.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.12.0)
Collecting numpy==2.2.6 (from gptqmodel)
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: torch>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (2.10.0+cu128)
Requirement already satisfied: safetensors>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.7.0)
Requirement already satisfied: transformers>=4.57.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (5.0.0)
Requirement already satisfied: threadpoolctl>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (3.6.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (26.0)
Collecting device-smi>=0.5.3 (from gptqmodel)
  Downloading device_smi-0.5.3.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf>=6.32.0 (from gptqmodel)
  Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: pillow>=11.3.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (11.3.0)
Collecting hf_transfer>=0.1.9 (from gptqmodel)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: huggingface_hub>=0.34.4 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.5.0)
Collecting tokenicer>=0.0.6 (from gptqmodel)
  Downloading tokenicer-0.0.8.tar.gz (9.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting logbar>=0.2.1 (from gptqmodel)
  Downloading logbar-0.2.2.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting maturin>=1.9.4 (from gptqmodel)
  Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl.metadata (16 kB)
Requirement already satisfied: datasets>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (4.0.0)
Collecting pyarrow>=21.0 (from gptqmodel)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.3.8)
Collecting pypcre>=0.2.9 (from gptqmodel)
  Downloading pypcre-0.2.12.tar.gz (119 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torchao>=0.14.1 (from gptqmodel)
  Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting kernels>=0.11.1 (from gptqmodel)
  Downloading kernels-0.12.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (6.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.24.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.22.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.11)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.8.0->gptqmodel) (1.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.8.0->gptqmodel) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.24.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.8.0->gptqmodel) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.6.0->gptqmodel) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (0.1.2)
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 188.1 MB/s  0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 162.9 MB/s  0:00:00
Downloading kernels-0.12.2-py3-none-any.whl (55 kB)
Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 224.3 MB/s  0:00:00
Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 194.8 MB/s  0:00:00
Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 146.6 MB/s  0:00:00
Building wheels for collected packages: gptqmodel, device-smi, logbar, pypcre, tokenicer
  Building wheel for gptqmodel (pyproject.toml) ... done
  Created wheel for gptqmodel: filename=gptqmodel-5.7.0-py3-none-any.whl size=817346 sha256=4663bff05c2e600ae41670d3dd95acc8a35a46963e82813964f7f652a7cc57a7
  Stored in directory: /root/.cache/pip/wheels/f1/89/4a/76480c491998e47c9b7dc4b46b9839d4c9bbb547595240e42f
  Building wheel for device-smi (pyproject.toml) ... done
  Created wheel for device-smi: filename=device_smi-0.5.3-py3-none-any.whl size=19983 sha256=fe9a3e164afd026f5ac38a1a85a5912c6556be75b707c7cd8e9b9e80a9c25ea8
  Stored in directory: /root/.cache/pip/wheels/49/e4/63/c7c798f3ca05e6d3e15269dc7789adf9214fb1f5324cf2f0e3
  Building wheel for logbar (pyproject.toml) ... done
  Created wheel for logbar: filename=logbar-0.2.2-py3-none-any.whl size=31310 sha256=67088ffa5673b36b15f660a0d61573f05c4cc6f0f884f6658e6de3424fe4dc16
  Stored in directory: /root/.cache/pip/wheels/8d/89/e6/c44856115298a2e8c1d0fe2cbfedd1090372f68c5083cdacf9
  Building wheel for pypcre (pyproject.toml) ... done
  Created wheel for pypcre: filename=pypcre-0.2.12-cp312-cp312-linux_x86_64.whl size=204032 sha256=9c8e7e51dc57fa59fe7cdadd29e89bf75dbeea2baca4f8c1f24063aceb014a1c
  Stored in directory: /root/.cache/pip/wheels/30/ab/28/ed1230e6afa79e0412bc432fcce0ca7e26bfe74ccd0567154a
  Building wheel for tokenicer (pyproject.toml) ... done
  Created wheel for tokenicer: filename=tokenicer-0.0.8-py3-none-any.whl size=11710 sha256=de9ea558251f344457d1835a2dd0d2cd7db4498b764e2826de44fff51a71c282
  Stored in directory: /root/.cache/pip/wheels/0d/5c/f8/f551cf580b631f76fb0e802127948b414c906b768fac0cf662
Successfully built gptqmodel device-smi logbar pypcre tokenicer
Installing collected packages: torchao, tokenicer, pypcre, pyarrow, protobuf, numpy, maturin, logbar, hf_transfer, device-smi, kernels, gptqmodel
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [gptqmodel]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-trace 1.18.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-dataproc 5.25.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
googleapis-common-protos 1.72.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-resource-manager 1.16.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-firestore 2.23.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.0 which is incompatible.
grpc-google-iam-v1 0.14.3 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigtable 2.35.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 7.34.0 which is incompatible.
google-cloud-aiplatform 1.139.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigquery-storage 2.36.2 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-appengine-logging 1.8.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-spanner 3.63.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-iam 2.21.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 7.34.0 which is incompatible.

In [ ]:

# Restart once after installation in a fresh runtime, then skip this cell on reruns.
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

In [ ]:

from __future__ import annotations

import json
import logging
import math
import os
import re
import time
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd
import torch
from datasets import load_dataset
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from gptqmodel import GPTQModel, QuantizeConfig

# ------------------------------
# Logging
# ------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    force=True,
)
logger = logging.getLogger('gptq_attn_only_quant')

PROJECT_ROOT = Path.cwd().resolve()
VARIANT = 'attn_only_quant'
RUN_NAME = 'gptq_w4_g128_attn_only_quant'
BASE_MODEL = 'Qwen/Qwen2-1.5B'

cfg = {
    'base_model': BASE_MODEL,
    'calibration': {
        'dataset': 'wikitext',
        'dataset_name': 'wikitext-2-raw-v1',
        'split': 'train',
        'num_samples': 512,
        'max_length': 2048,
        'seed': 42,
    },
    'quant': {
        'bits': 4,
        'group_size': 128,
        'desc_act': False,
    },
    'eval': {
        'perplexity': {
            'dataset': 'wikitext',
            'dataset_name': 'wikitext-2-raw-v1',
            'split': 'test',
            'max_length': 2048,
            'stride': 1024,
            'max_eval_tokens': 131072,
            'log_every': 25,
        },
        'gsm8k': {
            'num_fewshot': 8,
            'num_samples': 300,
            'max_new_tokens': 256,
            'log_every': 25,
        },
        'arc_challenge': {
            'num_samples': 500,
            'max_new_tokens': 5,
            'log_every': 50,
        },
    },
    'paths': {
        'artifacts_dir': str(PROJECT_ROOT / 'artifacts'),
        'results_dir': str(PROJECT_ROOT / 'results' / RUN_NAME),
        'calibration_dir': str(PROJECT_ROOT / 'calibration_data'),
        'bundles_dir': str(PROJECT_ROOT / 'zip_bundles' / RUN_NAME),
    },
}

PATHS = {k: Path(v) for k, v in cfg['paths'].items()}
for p in PATHS.values():
    p.mkdir(parents=True, exist_ok=True)

ARTIFACT_DIR = PATHS['artifacts_dir'] / 'gptq_w4_g128' / VARIANT
RESULTS_DIR = PATHS['results_dir'] / VARIANT
BUNDLE_DIR = PATHS['bundles_dir'] / VARIANT
CALIB_DIR = PATHS['calibration_dir']
for p in [ARTIFACT_DIR, RESULTS_DIR, BUNDLE_DIR, CALIB_DIR]:
    p.mkdir(parents=True, exist_ok=True)


def build_dynamic_config(variant: str) -> dict | None:
    if variant == 'full_quant':
        return None
    if variant == 'attn_only_quant':
        return {r'-:.*mlp\.(gate|up|down)_proj.*': {}}
    if variant == 'mlp_only_quant':
        return {r'-:.*self_attn\.(q|k|v|o)_proj.*': {}}
    raise ValueError(f'Unknown variant: {variant}')

print('Working directory:', PROJECT_ROOT)
print('Artifact dir:', ARTIFACT_DIR)
print('Results dir:', RESULTS_DIR)
print('Bundle dir:', BUNDLE_DIR)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

# ------------------------------
# Small utilities
# ------------------------------
def save_json(obj: Any, path: str | Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump(obj, f, indent=2)
    return path


def read_json(path: str | Path, default=None):
    path = Path(path)
    if not path.exists():
        return default
    with open(path) as f:
        return json.load(f)


def zip_directory(source_dir: str | Path, zip_path: str | Path, *, exclude_suffixes=('.lock',), exclude_dirs=('.ipynb_checkpoints',)):
    source_dir = Path(source_dir).resolve()
    zip_path = Path(zip_path).resolve()
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    tmp_zip = zip_path.with_suffix(zip_path.suffix + '.tmp')
    if tmp_zip.exists():
        tmp_zip.unlink()
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(tmp_zip, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        for path in sorted(source_dir.rglob('*')):
            if path.is_dir():
                continue
            if any(part in exclude_dirs for part in path.parts):
                continue
            if path.resolve() in {zip_path, tmp_zip}:
                continue
            if path.suffix in exclude_suffixes:
                continue
            zf.write(path, arcname=str(path.relative_to(source_dir)))

    tmp_zip.replace(zip_path)
    size_mb = zip_path.stat().st_size / (1024 ** 2)
    logger.info('Created zip: %s (%.2f MB)', zip_path, size_mb)
    return zip_path


def find_gptq_model_basename(model_dir: str | Path) -> str | None:
    model_dir = Path(model_dir)
    candidates = sorted(model_dir.glob('*.safetensors'))
    if not candidates:
        return None
    preferred = [p for p in candidates if 'gptq' in p.name.lower()]
    return (preferred[0] if preferred else candidates[0]).name


def estimate_num_params_from_config(model_dir: str | Path) -> int | None:
    cfg_path = Path(model_dir) / 'config.json'
    if not cfg_path.exists():
        return None
    cfg_json = json.loads(cfg_path.read_text())
    hidden_size = cfg_json.get('hidden_size')
    num_hidden_layers = cfg_json.get('num_hidden_layers')
    intermediate_size = cfg_json.get('intermediate_size')
    vocab_size = cfg_json.get('vocab_size')
    if not all(v is not None for v in [hidden_size, num_hidden_layers, intermediate_size, vocab_size]):
        return None
    rough_params = (
        vocab_size * hidden_size +
        num_hidden_layers * (4 * hidden_size * hidden_size) +
        num_hidden_layers * (3 * hidden_size * intermediate_size)
    )
    return int(rough_params)


def model_size_gb(model_dir: str | Path) -> float:
    files = list(Path(model_dir).glob('*.safetensors'))
    total_bytes = sum(p.stat().st_size for p in files)
    return total_bytes / (1024 ** 3)


def bits_per_param(model_dir: str | Path) -> float | None:
    files = list(Path(model_dir).glob('*.safetensors'))
    if not files:
        return None
    total_bytes = sum(p.stat().st_size for p in files)
    n_params = estimate_num_params_from_config(model_dir)
    if not n_params:
        return None
    return 8.0 * total_bytes / n_params


def get_results_state() -> dict:
    state = read_json(RESULTS_DIR / 'state.json', default={})
    return state or {}


def save_results_state(state: dict):
    save_json(state, RESULTS_DIR / 'state.json')
    return state


def update_summary_table(state: dict):
    size_gb = model_size_gb(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    bpp = bits_per_param(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    peak_candidates = []
    for key in ['perplexity', 'gsm8k', 'arc_challenge']:
        if key in state and isinstance(state[key], dict):
            val = state[key].get('peak_vram_gb')
            if val is not None:
                peak_candidates.append(val)

    summary_row = {
        'variant': VARIANT,
        'compression': f"GPTQ W{cfg['quant']['bits']} g{cfg['quant']['group_size']}",
        'model_size_gb': round(size_gb, 4) if size_gb is not None else None,
        'peak_vram_gb': round(max(peak_candidates), 4) if peak_candidates else None,
        'bits_per_param': round(bpp, 4) if bpp is not None else None,
        'perplexity': state.get('perplexity', {}).get('perplexity'),
        'gsm8k_accuracy': state.get('gsm8k', {}).get('accuracy'),
        'arc_accuracy': state.get('arc_challenge', {}).get('accuracy'),
    }
    save_json(summary_row, RESULTS_DIR / 'summary.json')
    pd.DataFrame([summary_row]).to_csv(RESULTS_DIR / 'summary.csv', index=False)
    return summary_row


def _is_gptq_checkpoint(model_path: str | Path) -> bool:
    cfg_path = Path(model_path) / 'config.json'
    if not cfg_path.exists():
        return False
    cfg_json = json.loads(cfg_path.read_text())
    return cfg_json.get('quantization_config', {}).get('quant_method') == 'gptq'


def load_quantized_model_and_tokenizer(model_path: str | Path):
    model_path = Path(model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'left'

    if not _is_gptq_checkpoint(model_path):
        raise ValueError(f'{model_path} is not a GPTQ checkpoint.')

    model_basename = find_gptq_model_basename(model_path)
    if model_basename is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {model_path}')

    model = GPTQModel.load(
        str(model_path),
        device_map='auto',
        trust_remote_code=True,
        model_basename=model_basename,
    )
    model.eval()
    return model, tokenizer


def get_model_device(model):
    if hasattr(model, 'device'):
        return model.device
    if hasattr(model, 'hf_device_map') and model.hf_device_map:
        first_device = next(iter(model.hf_device_map.values()))
        return torch.device(first_device)
    return torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


def generate_text(model, tokenizer, prompt: str, *, max_new_tokens: int):
    device = get_model_device(model)
    encoded = tokenizer(
        prompt,
        return_tensors='pt',
        truncation=True,
        max_length=min(getattr(tokenizer, 'model_max_length', 4096), 4096),
        padding=False,
    )
    input_ids = encoded['input_ids'].to(device)
    attention_mask = encoded['attention_mask'].to(device)

    with torch.inference_mode():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )
    gen_ids = outputs[0][input_ids.shape[-1]:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True)


ANSWER_RE = re.compile(r'####\s*(-?[\d,]+\.?\d*)')


def extract_numeric_answer(text: str):
    m = ANSWER_RE.search(text)
    if m:
        try:
            return float(m.group(1).replace(',', ''))
        except ValueError:
            return None
    nums = re.findall(r'-?[\d,]+\.?\d*', text)
    if not nums:
        return None
    try:
        return float(nums[-1].replace(',', ''))
    except ValueError:
        return None


def format_seconds(sec: float) -> str:
    sec = int(max(sec, 0))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    if h > 0:
        return f'{h:d}:{m:02d}:{s:02d}'
    return f'{m:d}:{s:02d}'


def log_progress(prefix: str, idx: int, total: int, start_time: float, correct: int):
    elapsed = time.time() - start_time
    avg = elapsed / max(idx, 1)
    eta = avg * max(total - idx, 0)
    logger.info(
        '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item',
        prefix,
        idx,
        total,
        correct / max(idx, 1),
        format_seconds(elapsed),
        format_seconds(eta),
        avg,
    )

WARN  Python GIL is enabled: Multi-gpu quant acceleration for MoE models is sub-optimal and multi-core accelerated cpu packing is also disabled. We recommend Python >= 3.13.3t with Pytorch > 2.8 for mult-gpu quantization and multi-cpu packing with env `PYTHON_GIL=0`.

WARN  Feature `utils/Perplexity` requires Python < 3.14 and Python GIL enabled and Python >= 3.13.3T (T for Threading-Free edition of Python) plus Torch 2.8. Feature is currently skipped/disabled.

INFO  ENV: Auto setting PYTORCH_ALLOC_CONF='expandable_segments:True,max_split_size_mb:256,garbage_collection_threshold:0.7' for memory saving.

INFO  ENV: Auto setting CUDA_DEVICE_ORDER=PCI_BUS_ID for correctness.

INFO

_____/\\\\\\\\\\\\__/\\\\\\\\\\\\\____/\\\\\\\\\\\\\\\______________________/\\\________/\\\\____________/\\\\_______________________/\\\__________________/\\\\\\____
 ___/\\\//////////__\/\\\/////////\\\_\///////\\\/////____________________/\\\\/\\\\____\/\\\\\\________/\\\\\\______________________\/\\\_________________\////\\\____
  __/\\\_____________\/\\\_______\/\\\_______\/\\\_______________________/\\\//\////\\\__\/\\\//\\\____/\\\//\\\______________________\/\\\____________________\/\\\____
   _\/\\\____/\\\\\\\_\/\\\\\\\\\\\\\/________\/\\\________/\\\\\\\\\\\__/\\\______\//\\\_\/\\\\///\\\/\\\/_\/\\\_____/\\\\\___________\/\\\______/\\\\\\\\_____\/\\\____
    _\/\\\___\/////\\\_\/\\\/////////__________\/\\\_______\///////////__\//\\\______/\\\__\/\\\__\///\\\/___\/\\\___/\\\///\\\____/\\\\\\\\\____/\\\/////\\\____\/\\\____
     _\/\\\_______\/\\\_\/\\\___________________\/\\\______________________\///\\\\/\\\\/___\/\\\____\///_____\/\\\__/\\\__\//\\\__/\\\////\\\___/\\\\\\\\\\\_____\/\\\____
      _\/\\\_______\/\\\_\/\\\___________________\/\\\________________________\////\\\//_____\/\\\_____________\/\\\_\//\\\__/\\\__\/\\\__\/\\\__\//\\///////______\/\\\____
       _\//\\\\\\\\\\\\/__\/\\\___________________\/\\\___________________________\///\\\\\\__\/\\\_____________\/\\\__\///\\\\\/___\//\\\\\\\/\\__\//\\\\\\\\\\__/\\\\\\\\\_
        __\////////////____\///____________________\///______________________________\//////___\///______________\///_____\/////______\///////\//____\//////////__\/////////__

Working directory: /content
Artifact dir: /content/artifacts/gptq_w4_g128/attn_only_quant
Results dir: /content/results/gptq_w4_g128_attn_only_quant/attn_only_quant
Bundle dir: /content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant
CUDA available: True
GPU: NVIDIA L4

In [ ]:
# Quantization helpers

def get_calibration_data(cfg, tokenizer=None):
    cal_cfg = cfg['calibration']
    cache_path = CALIB_DIR / f"calibration_{cal_cfg['num_samples']}_{cal_cfg['max_length']}.pt"
    if cache_path.exists():
        logger.info('Using cached calibration samples: %s', cache_path)
        return torch.load(cache_path, weights_only=False)

    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

    logger.info('Loading calibration dataset: %s / %s / %s', cal_cfg['dataset'], cal_cfg['dataset_name'], cal_cfg['split'])
    ds = load_dataset(cal_cfg['dataset'], cal_cfg['dataset_name'], split=cal_cfg['split'])
    all_text = '\n\n'.join(t for t in ds['text'] if t and t.strip())
    encoded = tokenizer(all_text, return_tensors='pt')
    total_tokens = encoded.input_ids.shape[1]
    max_len = cal_cfg['max_length']

    if total_tokens <= max_len:
        raise ValueError(f'Calibration corpus too short: total_tokens={total_tokens}, max_length={max_len}')

    rng = torch.Generator().manual_seed(cal_cfg['seed'])
    starts = torch.randint(0, total_tokens - max_len, (cal_cfg['num_samples'],), generator=rng)
    samples = []
    for start in tqdm(starts.tolist(), desc='Preparing calibration windows', unit='sample'):
        end = start + max_len
        input_ids = encoded.input_ids[:, start:end]
        samples.append({
            'input_ids': input_ids,
            'attention_mask': torch.ones_like(input_ids),
        })

    torch.save(samples, cache_path)
    logger.info('Saved calibration cache: %s', cache_path)
    return samples


def quantize_variant_gptq(cfg):
    tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quantized_already = (ARTIFACT_DIR / 'config.json').exists() and find_gptq_model_basename(ARTIFACT_DIR) is not None
    if quantized_already:
        logger.info('Quantized artifact already exists at %s', ARTIFACT_DIR)
        zip_path = BUNDLE_DIR / f'{VARIANT}_quantized_model.zip'
        if not zip_path.exists():
            zip_directory(ARTIFACT_DIR, zip_path)
        return {
            'artifact_dir': str(ARTIFACT_DIR),
            'zip_path': str(zip_path),
            'gptq_model_file': find_gptq_model_basename(ARTIFACT_DIR),
            'dynamic_config': build_dynamic_config(VARIANT),
            'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
            'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        }

    samples = get_calibration_data(cfg, tokenizer)
    cal_dataset = [
        {
            'input_ids': s['input_ids'].squeeze(0),
            'attention_mask': s['attention_mask'].squeeze(0),
        }
        for s in samples
    ]

    qcfg_kwargs = {
        'bits': cfg['quant']['bits'],
        'group_size': cfg['quant']['group_size'],
        'desc_act': cfg['quant'].get('desc_act', False),
    }
    dynamic = build_dynamic_config(VARIANT)
    if dynamic is not None:
        qcfg_kwargs['dynamic'] = dynamic

    quantize_config = QuantizeConfig(**qcfg_kwargs)

    logger.info('Starting GPTQ %s for %s', VARIANT, cfg['base_model'])
    t0 = time.time()
    model = GPTQModel.load(cfg['base_model'], quantize_config, trust_remote_code=True)
    model.quantize(cal_dataset)
    model.save(str(ARTIFACT_DIR))
    tokenizer.save_pretrained(str(ARTIFACT_DIR))
    elapsed = time.time() - t0
    logger.info('Quantization finished in %s', format_seconds(elapsed))

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    model_file = find_gptq_model_basename(ARTIFACT_DIR)
    if model_file is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {ARTIFACT_DIR}')

    manifest = {
        'variant': VARIANT,
        'base_model': cfg['base_model'],
        'quant': cfg['quant'],
        'dynamic_config': dynamic,
        'artifact_dir': str(ARTIFACT_DIR),
        'gptq_model_file': model_file,
        'quantization_elapsed_sec': elapsed,
        'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
        'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        'created_at_unix': time.time(),
    }
    save_json(manifest, ARTIFACT_DIR / 'artifact_manifest.json')
    save_json(manifest, RESULTS_DIR / 'quantization_manifest.json')

    zip_path = zip_directory(ARTIFACT_DIR, BUNDLE_DIR / f'{VARIANT}_quantized_model.zip')

    state = get_results_state()
    state['quantization'] = manifest | {'zip_path': str(zip_path)}
    save_results_state(state)
    summary = update_summary_table(state)

    print('Quantized artifact ready.')
    print(json.dumps(manifest, indent=2))
    display(pd.DataFrame([summary]))
    return manifest | {'zip_path': str(zip_path)}

In [ ]:
# Cell 1 — Quantize the model and save the quantized artifact zip
quant_manifest = quantize_variant_gptq(cfg)

2026-03-09 23:55:29,702 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:29,708 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:29,715 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

2026-03-09 23:55:30,028 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:30,034 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:30,041 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json: 0.00B [00:00, ?B/s]

2026-03-09 23:55:30,289 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-09 23:55:30,775 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:31,008 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:31,013 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"
2026-03-09 23:55:31,020 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"

vocab.json: 0.00B [00:00, ?B/s]

2026-03-09 23:55:31,294 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/merges.txt "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-09 23:55:31,295 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-09 23:55:31,301 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"
2026-03-09 23:55:31,308 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"

merges.txt: 0.00B [00:00, ?B/s]

2026-03-09 23:55:31,575 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:31,581 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"
2026-03-09 23:55:31,589 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

2026-03-09 23:55:31,881 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-03-09 23:55:32,111 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-03-09 23:55:32,345 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-03-09 23:55:33,426 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-03-09 23:55:33,429 | INFO    | Loading calibration dataset: wikitext / wikitext-2-raw-v1 / train
2026-03-09 23:55:33,666 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:33,891 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:33,897 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-09 23:55:33,904 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"

README.md: 0.00B [00:00, ?B/s]

2026-03-09 23:55:34,149 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:34,390 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-09 23:55:35,083 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-09 23:55:35,332 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:35,570 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"
2026-03-09 23:55:35,815 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:36,044 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-09 23:55:36,306 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-09 23:55:36,548 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:36,791 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:37,016 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:37,257 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:37,494 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:37,730 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-03-09 23:55:37,959 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:38,195 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:38,517 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:38,759 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-03-09 23:55:39,040 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/xet-read-token/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"

wikitext-2-raw-v1/test-00000-of-00001.pa(…):   0%|          | 0.00/733k [00:00<?, ?B/s]

2026-03-09 23:55:41,262 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:41,498 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/train-00000-of-00001.p(…):   0%|          | 0.00/6.36M [00:00<?, ?B/s]

2026-03-09 23:55:42,352 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:42,576 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/validation-00000-of-00(…):   0%|          | 0.00/657k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (2517232 > 32768). Running this sequence through the model will result in indexing errors

Preparing calibration windows:   0%|          | 0/512 [00:00<?, ?sample/s]

2026-03-09 23:55:55,292 | INFO    | Saved calibration cache: /content/calibration_data/calibration_512_2048.pt

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/hqdpgrum-rkaakpxx/`

2026-03-09 23:55:55,613 | INFO    | Starting GPTQ attn_only_quant for Qwen/Qwen2-1.5B
2026-03-09 23:55:55,875 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:55,881 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:56,114 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:56,347 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:55:56,591 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:56,598 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"

WARN  GPTQModel's per-module `dynamic` quantization feature is fully supported in latest vLLM and SGLang but not yet available in hf transformers.

2026-03-09 23:55:56,832 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:56,839 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:57,104 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/revision/main "HTTP/1.1 200 OK"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

2026-03-09 23:55:57,349 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:57,355 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-09 23:55:57,360 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:57,362 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/model.safetensors "HTTP/1.1 302 Found"
2026-03-09 23:55:57,363 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-09 23:55:57,364 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:57,365 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:55:57,366 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:57,374 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-09 23:55:57,376 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-09 23:55:57,383 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-09 23:55:57,385 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-09 23:55:57,386 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-09 23:55:57,598 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/xet-read-token/8a16abf2848eda07cc5253dec660bf1ce007ad7a "HTTP/1.1 200 OK"
2026-03-09 23:56:07,441 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:56:07,447 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 23:56:07,687 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:56:07,694 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-09 23:56:07,953 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-09 23:56:08,202 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-09 23:56:09,339 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

model: Qwen2ForCausalLM  (P=0 B=0) [- | - | ~0B]
├─ model.model: Qwen2Model  (P=0 B=0) [- | - | ~0B]
│  ├─ model.model.embed_tokens: Embedding  (P=233.37M B=0) [meta | bfloat16 | ~0B (est~445.12MB)]
│  │  │  param: weight  shape=(151936, 1536) dtype=bfloat16 device=meta ~445.12MB
│  ├─ model.model.layers: ModuleList  (P=0 B=0) [- | - | ~0B]
│  │  ├─ model.model.layers.0: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.0.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.0.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.0.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.0.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.1: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.1.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.1.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.1.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.1.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.1.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.2: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.2.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.2.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.2.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.2.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.2.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.3: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.3.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.3.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.3.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.3.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.3.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.4: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.4.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.4.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.4.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.4.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.4.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.5: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.5.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.5.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.5.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.5.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.5.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.6: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.6.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.6.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.6.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.6.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.6.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.7: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.7.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.7.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.7.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.7.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.7.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

2026-03-09 23:56:10,199 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-09 23:56:10,205 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-09 23:56:10,365 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[]`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Disk subsystem write throughput detected at 256.7 MB/s.

2026-03-09 23:56:11,974 | INFO    | Not a TTY. Pause/resume from keyboard is disabled.

INFO  ModuleLooper: capturing layer inputs from 512 calibration batches

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  Offloading base modules to disk...

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | region     | count | last_s | avg_s | total_s | pct    | source  |

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | Capture inputs | 1     | 2.261  | 2.261 | 2.261   | 84.7%  | cache_inputs:Qwen2DecoderLayer |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Turtle reload  | 1     | 0.408  | 0.408 | 0.408   | 15.3%  | auto:Embedding                 |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000010618 | 1048576 | 0.05000 | 2.236 | 3.191    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000056309 | 1048576 | 0.05000 | 2.277 | 3.191    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000001316 | 1048576 | 0.05000 | 2.290 | 3.191    | cuda 0.69G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001152 | 1048576 | 0.05000 | 0.549 | 2.406    | cuda 0.74G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant  | 8     | 0.558  | 0.926 | 7.411   | 36.4%  | model.layers.0.self_attn.o_proj |

INFO  +----------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Pre-quant forward | 2     | 2.406  | 2.798 | 5.597   | 27.5%  | model.layers.0:subset2/2        |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Post-quant replay | 1     | 3.151  | 3.151 | 3.151   | 15.5%  | model.layers.0:subset2/2        |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Capture inputs    | 1     | 2.261  | 2.261 | 2.261   | 11.1%  | cache_inputs:Qwen2DecoderLayer  |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Forward hook      | 2048  | 0.001  | 0.001 | 1.526   | 7.5%   | model.layers.0.self_attn.o_proj |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Turtle reload     | 1     | 0.408  | 0.408 | 0.408   | 2.0%   | auto:Embedding                  |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  Format: Converting GPTQ v2 to v1

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000010982 | 1048576 | 0.05000 | 1.605 | 2.378    | cuda 3.8G    |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000000499 | 1048576 | 0.05000 | 1.645 | 2.378    | cuda 3.8G    |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003771 | 1048576 | 0.05000 | 1.668 | 2.378    | cuda 3.8G    |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000321 | 1048576 | 0.05000 | 0.537 | 1.606    | cuda 3.8G    |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant     | 16    | 0.546  | 0.808 | 12.927  | 31.2%  | model.layers.1.self_attn.o_proj |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Pre-quant forward | 4     | 1.606  | 2.395 | 9.580   | 23.1%  | model.layers.1:subset2/2        |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Post-quant replay | 2     | 2.762  | 2.956 | 5.913   | 14.3%  | model.layers.1:subset2/2        |

INFO  +-------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Submodule finalize | 8     | 0.921  | 0.457 | 3.657   | 8.8%   | model.layers.0.self_attn.v_proj |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Forward hook       | 4096  | 0.001  | 0.001 | 3.121   | 7.5%   | model.layers.1.self_attn.o_proj |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Finalize create    | 4     | 0.795  | 0.598 | 2.391   | 5.8%   | model.layers.0.self_attn.v_proj |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 5.5%   | cache_inputs:Qwen2DecoderLayer  |

INFO  +--------------------+-------+--------+-------+---------+--------+---------------------------------+

INFO  | Finalize pack      | 4     | 0.095  | 0.260 | 1.041   | 2.5%   | model.layers.0.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.408  | 0.408 | 0.408   | 1.0%   | auto:Embedding                                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 4     | 0.011  | 0.031 | 0.122   | 0.3%   | model.layers.0.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000045917 | 1048576 | 0.05000 | 1.558 | 2.156    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012877 | 1048576 | 0.05000 | 1.596 | 2.156    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003589 | 1048576 | 0.05000 | 1.609 | 2.156    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000825 | 1048576 | 0.05000 | 0.541 | 1.593    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 24    | 0.551  | 0.762 | 18.288  | 32.6%  | model.layers.2.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 6     | 1.593  | 2.222 | 13.330  | 23.8%  | model.layers.2:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 3     | 2.768  | 2.894 | 8.681   | 15.5%  | model.layers.2:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 6144  | 0.001  | 0.001 | 4.735   | 8.4%   | model.layers.2.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 16    | 0.177  | 0.272 | 4.345   | 7.7%   | model.layers.1.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 8     | 0.059  | 0.322 | 2.574   | 4.6%   | model.layers.1.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 4.0%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 8     | 0.089  | 0.155 | 1.243   | 2.2%   | model.layers.1.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.408  | 0.408 | 0.408   | 0.7%   | auto:Embedding                                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 8     | 0.010  | 0.030 | 0.237   | 0.4%   | model.layers.1.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011183 | 1048576 | 0.05000 | 1.565 | 2.181    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000041165 | 1048576 | 0.05000 | 1.571 | 2.181    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000004210 | 1048576 | 0.05000 | 1.602 | 2.181    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000000775 | 1048576 | 0.05000 | 0.561 | 1.619    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 32    | 0.569  | 0.739 | 23.657  | 33.4%  | model.layers.3.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 8     | 1.619  | 2.141 | 17.131  | 24.2%  | model.layers.3:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 4     | 2.769  | 2.862 | 11.450  | 16.2%  | model.layers.3:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 8192  | 0.001  | 0.001 | 6.344   | 9.0%   | model.layers.3.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 24    | 0.176  | 0.207 | 4.973   | 7.0%   | model.layers.2.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 12    | 0.065  | 0.231 | 2.775   | 3.9%   | model.layers.2.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 3.2%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 12    | 0.089  | 0.121 | 1.451   | 2.0%   | model.layers.2.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.408  | 0.408 | 0.408   | 0.6%   | auto:Embedding                                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 12    | 0.004  | 0.033 | 0.397   | 0.6%   | model.layers.2.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007599 | 1048576 | 0.05000 | 1.606 | 2.179    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000033506 | 1048576 | 0.05000 | 1.674 | 2.179    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000004720 | 1048576 | 0.05000 | 1.684 | 2.179    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001610 | 1048576 | 0.05000 | 0.550 | 1.597    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 40    | 0.558  | 0.731 | 29.226  | 34.1%  | model.layers.4.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 10    | 1.597  | 2.091 | 20.907  | 24.4%  | model.layers.4:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 5     | 2.775  | 2.845 | 14.224  | 16.6%  | model.layers.4:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 10240 | 0.001  | 0.001 | 7.983   | 9.3%   | model.layers.4.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 32    | 0.175  | 0.175 | 5.594   | 6.5%   | model.layers.3.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 16    | 0.067  | 0.186 | 2.980   | 3.5%   | model.layers.3.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 2.6%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 16    | 0.088  | 0.103 | 1.651   | 1.9%   | model.layers.3.self_attn.o_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 16    | 0.008  | 0.032 | 0.517   | 0.6%   | model.layers.3.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.408  | 0.408 | 0.408   | 0.5%   | auto:Embedding                                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018593 | 1048576 | 0.05000 | 1.571 | 2.161    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000006658 | 1048576 | 0.05000 | 1.600 | 2.161    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000070386 | 1048576 | 0.05000 | 1.613 | 2.161    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001596 | 1048576 | 0.05000 | 0.548 | 1.585    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 48    | 0.557  | 0.721 | 34.614  | 34.5%  | model.layers.5.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 12    | 1.585  | 2.054 | 24.653  | 24.5%  | model.layers.5:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 6     | 2.796  | 2.837 | 17.020  | 16.9%  | model.layers.5:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 12288 | 0.001  | 0.001 | 9.601   | 9.6%   | model.layers.5.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 40    | 0.155  | 0.155 | 6.191   | 6.2%   | model.layers.4.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 20    | 0.056  | 0.158 | 3.150   | 3.1%   | model.layers.4.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 2.3%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 20    | 0.073  | 0.095 | 1.894   | 1.9%   | model.layers.4.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 20    | 0.008  | 0.032 | 0.631   | 0.6%   | model.layers.4.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.408  | 0.408 | 0.408   | 0.4%   | auto:Embedding                                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000064465 | 1048576 | 0.05000 | 1.753 | 2.178    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000014297 | 1048576 | 0.05000 | 1.778 | 2.178    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007682 | 1048576 | 0.05000 | 1.787 | 2.178    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002429 | 1048576 | 0.05000 | 0.555 | 1.584    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 56    | 0.565  | 0.724 | 40.542  | 33.9%  | model.layers.6.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 14    | 1.584  | 2.030 | 28.416  | 23.7%  | model.layers.6:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 7     | 2.795  | 2.831 | 19.814  | 16.6%  | model.layers.6:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 14336 | 0.001  | 0.001 | 11.225  | 9.4%   | model.layers.6.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 48    | 0.605  | 0.178 | 8.567   | 7.2%   | model.layers.5.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 24    | 0.417  | 0.184 | 4.408   | 3.7%   | model.layers.5.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 24    | 0.164  | 0.115 | 2.755   | 2.3%   | model.layers.5.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.9%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.7%   | auto:Qwen2DecoderLayer                              |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 24    | 0.004  | 0.035 | 0.828   | 0.7%   | model.layers.5.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000042238 | 1048576 | 0.05000 | 1.593 | 2.167    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011166 | 1048576 | 0.05000 | 1.610 | 2.167    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000003931 | 1048576 | 0.05000 | 1.628 | 2.167    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000001937 | 1048576 | 0.05000 | 0.562 | 1.574    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 64    | 0.572  | 0.719 | 45.990  | 34.2%  | model.layers.7.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 16    | 1.574  | 2.010 | 32.156  | 23.9%  | model.layers.7:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 8     | 2.802  | 2.827 | 22.616  | 16.8%  | model.layers.7:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 16384 | 0.001  | 0.001 | 12.855  | 9.6%   | model.layers.7.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 56    | 0.162  | 0.164 | 9.195   | 6.8%   | model.layers.6.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 28    | 0.013  | 0.159 | 4.451   | 3.3%   | model.layers.6.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 28    | 0.123  | 0.108 | 3.030   | 2.3%   | model.layers.6.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.7%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 28    | 0.014  | 0.035 | 0.988   | 0.7%   | model.layers.6.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.6%   | auto:Qwen2DecoderLayer                              |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000035208 | 1048576 | 0.05000 | 1.672 | 2.172    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000008360 | 1048576 | 0.05000 | 1.708 | 2.172    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005238 | 1048576 | 0.05000 | 1.730 | 2.172    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000004620 | 1048576 | 0.05000 | 0.555 | 1.570    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 72    | 0.565  | 0.718 | 51.712  | 34.6%  | model.layers.8.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 18    | 1.570  | 1.994 | 35.898  | 24.0%  | model.layers.8:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 9     | 2.799  | 2.824 | 25.415  | 17.0%  | model.layers.8:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 18432 | 0.001  | 0.001 | 14.484  | 9.7%   | model.layers.8.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 64    | 0.157  | 0.153 | 9.790   | 6.6%   | model.layers.7.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 32    | 0.055  | 0.144 | 4.621   | 3.1%   | model.layers.7.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 32    | 0.080  | 0.103 | 3.286   | 2.2%   | model.layers.7.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.5%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 32    | 0.003  | 0.034 | 1.096   | 0.7%   | model.layers.7.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.6%   | auto:Qwen2DecoderLayer                              |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000070125 | 1048576 | 0.05000 | 1.596 | 2.158    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005353 | 1048576 | 0.05000 | 1.618 | 2.158    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020010 | 1048576 | 0.05000 | 1.620 | 2.158    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002384 | 1048576 | 0.05000 | 0.556 | 1.608    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 80    | 0.566  | 0.715 | 57.169  | 34.9%  | model.layers.9.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 20    | 1.608  | 1.983 | 39.664  | 24.2%  | model.layers.9:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 10    | 2.796  | 2.821 | 28.211  | 17.2%  | model.layers.9:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 20480 | 0.001  | 0.001 | 16.111  | 9.8%   | model.layers.9.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 72    | 0.146  | 0.143 | 10.303  | 6.3%   | model.layers.8.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 36    | 0.015  | 0.130 | 4.670   | 2.8%   | model.layers.8.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 36    | 0.108  | 0.098 | 3.519   | 2.1%   | model.layers.8.self_attn.o_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.4%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 36    | 0.004  | 0.035 | 1.268   | 0.8%   | model.layers.8.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.5%   | auto:Qwen2DecoderLayer                              |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018003 | 1048576 | 0.05000 | 1.608 | 2.141    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000061867 | 1048576 | 0.05000 | 1.631 | 2.141    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007226 | 1048576 | 0.05000 | 1.640 | 2.141    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003570 | 1048576 | 0.05000 | 0.551 | 1.594    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 88    | 0.560  | 0.712 | 62.662  | 35.1%  | model.layers.10.self_attn.o_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 22    | 1.594  | 1.973 | 43.398  | 24.3%  | model.layers.10:subset2/2                           |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 11    | 2.797  | 2.819 | 31.007  | 17.3%  | model.layers.10:subset2/2                           |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 22528 | 0.001  | 0.001 | 17.727  | 9.9%   | model.layers.10.self_attn.o_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 80    | 0.161  | 0.137 | 10.927  | 6.1%   | model.layers.9.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 40    | 0.057  | 0.121 | 4.848   | 2.7%   | model.layers.9.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 40    | 0.077  | 0.093 | 3.734   | 2.1%   | model.layers.9.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.3%   | cache_inputs:Qwen2DecoderLayer                      |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize offload   | 40    | 0.008  | 0.034 | 1.378   | 0.8%   | model.layers.9.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.5%   | auto:Qwen2DecoderLayer                              |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005563 | 1048576 | 0.05000 | 1.717 | 2.183    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000046783 | 1048576 | 0.05000 | 1.753 | 2.183    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012285 | 1048576 | 0.05000 | 1.789 | 2.183    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002987 | 1048576 | 0.05000 | 0.566 | 1.617    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 96    | 0.575  | 0.714 | 68.542  | 35.3%  | model.layers.11.self_attn.o_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Pre-quant forward  | 24    | 1.617  | 1.967 | 47.199  | 24.3%  | model.layers.11:subset2/2                           |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Post-quant replay  | 12    | 2.784  | 2.816 | 33.792  | 17.4%  | model.layers.11:subset2/2                           |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Forward hook       | 24576 | 0.001  | 0.001 | 19.350  | 10.0%  | model.layers.11.self_attn.o_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Submodule finalize | 88    | 0.172  | 0.132 | 11.594  | 6.0%   | model.layers.10.self_attn.k_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize create    | 44    | 0.066  | 0.115 | 5.051   | 2.6%   | model.layers.10.self_attn.k_proj                    |

INFO  +--------------------+-------+--------+-------+---------+--------+-----------------------------------------------------+

INFO  | Finalize pack      | 44    | 0.079  | 0.091 | 4.008   | 2.1%   | model.layers.10.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.2%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 44    | 0.010  | 0.034 | 1.483   | 0.8%   | model.layers.10.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.430  | 0.419 | 0.837   | 0.4%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000007630 | 1048576 | 0.05000 | 1.793 | 2.217    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000053048 | 1048576 | 0.05000 | 1.827 | 2.217    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012987 | 1048576 | 0.05000 | 1.846 | 2.217    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000004906 | 1048576 | 0.05000 | 0.620 | 1.624    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 104   | 0.629  | 0.718 | 74.687  | 35.0%  | model.layers.12.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 26    | 1.624  | 1.963 | 51.040  | 23.9%  | model.layers.12:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 13    | 2.777  | 2.813 | 36.568  | 17.1%  | model.layers.12:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 26624 | 0.001  | 0.001 | 20.955  | 9.8%   | model.layers.12.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 96    | 0.602  | 0.146 | 13.976  | 6.6%   | model.layers.11.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 48    | 0.295  | 0.124 | 5.943   | 2.8%   | model.layers.11.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 48    | 0.275  | 0.105 | 5.032   | 2.4%   | model.layers.11.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.1%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 48    | 0.014  | 0.034 | 1.613   | 0.8%   | model.layers.11.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000005295 | 1048576 | 0.05000 | 1.800 | 2.168    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000041821 | 1048576 | 0.05000 | 1.849 | 2.168    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011107 | 1048576 | 0.05000 | 1.877 | 2.168    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003205 | 1048576 | 0.05000 | 0.588 | 1.637    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 112   | 0.598  | 0.722 | 80.859  | 35.3%  | model.layers.13.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 28    | 1.637  | 1.959 | 54.845  | 24.0%  | model.layers.13:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 14    | 2.784  | 2.811 | 39.353  | 17.2%  | model.layers.13:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 28672 | 0.001  | 0.001 | 22.580  | 9.9%   | model.layers.13.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 104   | 0.167  | 0.141 | 14.628  | 6.4%   | model.layers.12.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 52    | 0.060  | 0.118 | 6.127   | 2.7%   | model.layers.12.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 52    | 0.082  | 0.101 | 5.261   | 2.3%   | model.layers.12.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 1.0%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 52    | 0.011  | 0.033 | 1.713   | 0.7%   | model.layers.12.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000103949 | 1048576 | 0.05000 | 1.698 | 2.203    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000009435 | 1048576 | 0.05000 | 1.714 | 2.203    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000023934 | 1048576 | 0.05000 | 1.732 | 2.203    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000002425 | 1048576 | 0.05000 | 0.585 | 1.635    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 120   | 0.593  | 0.722 | 86.649  | 35.5%  | model.layers.14.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 30    | 1.635  | 1.956 | 58.683  | 24.0%  | model.layers.14:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 15    | 2.786  | 2.809 | 42.139  | 17.3%  | model.layers.14:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 30720 | 0.001  | 0.001 | 24.203  | 9.9%   | model.layers.14.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 112   | 0.170  | 0.137 | 15.290  | 6.3%   | model.layers.13.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 56    | 0.058  | 0.113 | 6.307   | 2.6%   | model.layers.13.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 56    | 0.084  | 0.098 | 5.505   | 2.3%   | model.layers.13.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.9%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 56    | 0.010  | 0.033 | 1.822   | 0.7%   | model.layers.13.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.5%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000011268 | 1048576 | 0.05000 | 1.687 | 2.163    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000013126 | 1048576 | 0.05000 | 1.789 | 2.163    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000063141 | 1048576 | 0.05000 | 1.799 | 2.163    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000003464 | 1048576 | 0.05000 | 0.546 | 1.590    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 128   | 0.555  | 0.723 | 92.523  | 35.7%  | model.layers.15.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 32    | 1.590  | 1.951 | 62.437  | 24.1%  | model.layers.15:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 16    | 2.789  | 2.808 | 44.928  | 17.3%  | model.layers.15:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 32768 | 0.001  | 0.001 | 25.821  | 10.0%  | model.layers.15.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 120   | 0.161  | 0.133 | 15.913  | 6.1%   | model.layers.14.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 60    | 0.061  | 0.108 | 6.494   | 2.5%   | model.layers.14.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 60    | 0.074  | 0.095 | 5.721   | 2.2%   | model.layers.14.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.9%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 60    | 0.010  | 0.032 | 1.920   | 0.7%   | model.layers.14.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.5%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000008019 | 1048576 | 0.05000 | 1.695 | 2.149    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000012511 | 1048576 | 0.05000 | 1.726 | 2.149    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000074481 | 1048576 | 0.05000 | 1.738 | 2.149    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000004835 | 1048576 | 0.05000 | 0.560 | 1.591    | cuda 6.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 136   | 0.568  | 0.723 | 98.295  | 35.9%  | model.layers.16.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 34    | 1.591  | 1.946 | 66.177  | 24.1%  | model.layers.16:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 17    | 2.791  | 2.807 | 47.719  | 17.4%  | model.layers.16:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 34816 | 0.001  | 0.001 | 27.444  | 10.0%  | model.layers.16.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 128   | 0.168  | 0.128 | 16.431  | 6.0%   | model.layers.15.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 64    | 0.015  | 0.102 | 6.538   | 2.4%   | model.layers.15.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 64    | 0.128  | 0.094 | 6.011   | 2.2%   | model.layers.15.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.8%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 64    | 0.011  | 0.030 | 1.949   | 0.7%   | model.layers.15.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.5%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000024007 | 1048576 | 0.05000 | 1.710 | 2.175    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000089587 | 1048576 | 0.05000 | 1.756 | 2.175    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000017966 | 1048576 | 0.05000 | 1.758 | 2.175    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005272 | 1048576 | 0.05000 | 0.583 | 1.611    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 144   | 0.591  | 0.723 | 104.167 | 36.0%  | model.layers.17.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 36    | 1.611  | 1.943 | 69.963  | 24.2%  | model.layers.17:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 18    | 2.800  | 2.807 | 50.519  | 17.5%  | model.layers.17:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 36864 | 0.001  | 0.001 | 29.057  | 10.0%  | model.layers.17.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 136   | 0.172  | 0.126 | 17.094  | 5.9%   | model.layers.16.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 68    | 0.063  | 0.099 | 6.733   | 2.3%   | model.layers.16.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 68    | 0.078  | 0.092 | 6.283   | 2.2%   | model.layers.16.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.8%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 68    | 0.004  | 0.029 | 1.998   | 0.7%   | model.layers.16.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.464  | 0.434 | 1.302   | 0.4%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000015306 | 1048576 | 0.05000 | 1.738 | 2.159    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000021431 | 1048576 | 0.05000 | 1.766 | 2.159    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000071866 | 1048576 | 0.05000 | 1.776 | 2.159    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000007051 | 1048576 | 0.05000 | 0.560 | 1.570    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 152   | 0.568  | 0.724 | 110.063 | 35.4%  | model.layers.18.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 38    | 1.570  | 1.939 | 73.692  | 23.7%  | model.layers.18:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 19    | 2.786  | 2.806 | 53.306  | 17.1%  | model.layers.18:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 38912 | 0.001  | 0.001 | 30.685  | 9.9%   | model.layers.18.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 144   | 0.899  | 0.144 | 20.667  | 6.6%   | model.layers.17.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 72    | 0.591  | 0.118 | 8.512   | 2.7%   | model.layers.17.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 72    | 0.277  | 0.104 | 7.485   | 2.4%   | model.layers.17.self_attn.o_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 72    | 0.010  | 0.032 | 2.298   | 0.7%   | model.layers.17.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.7%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.7%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000073190 | 1048576 | 0.05000 | 1.736 | 2.163    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000015707 | 1048576 | 0.05000 | 1.768 | 2.163    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000014265 | 1048576 | 0.05000 | 1.778 | 2.163    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005216 | 1048576 | 0.05000 | 0.565 | 1.629    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 160   | 0.574  | 0.725 | 115.962 | 35.5%  | model.layers.19.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 40    | 1.629  | 1.937 | 77.484  | 23.8%  | model.layers.19:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 20    | 2.785  | 2.805 | 56.090  | 17.2%  | model.layers.19:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 40960 | 0.001  | 0.001 | 32.320  | 9.9%   | model.layers.19.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 152   | 0.174  | 0.140 | 21.256  | 6.5%   | model.layers.18.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 76    | 0.075  | 0.115 | 8.725   | 2.7%   | model.layers.18.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 76    | 0.080  | 0.102 | 7.762   | 2.4%   | model.layers.18.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 76    | 0.011  | 0.031 | 2.326   | 0.7%   | model.layers.18.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.7%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000017229 | 1048576 | 0.05000 | 1.719 | 2.160    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000077997 | 1048576 | 0.05000 | 1.761 | 2.160    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016428 | 1048576 | 0.05000 | 1.778 | 2.160    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005249 | 1048576 | 0.05000 | 0.550 | 1.616    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 168   | 0.560  | 0.725 | 121.825 | 35.7%  | model.layers.20.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 42    | 1.616  | 1.935 | 81.261  | 23.8%  | model.layers.20:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 21    | 2.793  | 2.804 | 58.884  | 17.3%  | model.layers.20:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 43008 | 0.001  | 0.001 | 33.955  | 9.9%   | model.layers.20.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 160   | 0.150  | 0.136 | 21.837  | 6.4%   | model.layers.19.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 80    | 0.051  | 0.111 | 8.882   | 2.6%   | model.layers.19.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 80    | 0.073  | 0.100 | 8.001   | 2.3%   | model.layers.19.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 80    | 0.011  | 0.030 | 2.385   | 0.7%   | model.layers.19.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.7%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016331 | 1048576 | 0.05000 | 1.633 | 2.166    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000016349 | 1048576 | 0.05000 | 1.670 | 2.166    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000083597 | 1048576 | 0.05000 | 1.669 | 2.166    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000007516 | 1048576 | 0.05000 | 0.554 | 1.578    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 176   | 0.562  | 0.724 | 127.413 | 35.8%  | model.layers.21.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 44    | 1.578  | 1.932 | 85.004  | 23.9%  | model.layers.21:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 22    | 2.794  | 2.804 | 61.677  | 17.3%  | model.layers.21:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 45056 | 0.001  | 0.001 | 35.569  | 10.0%  | model.layers.21.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 168   | 0.150  | 0.133 | 22.413  | 6.3%   | model.layers.20.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 84    | 0.050  | 0.108 | 9.040   | 2.5%   | model.layers.20.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 84    | 0.072  | 0.098 | 8.236   | 2.3%   | model.layers.20.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 84    | 0.011  | 0.029 | 2.430   | 0.7%   | model.layers.20.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.6%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000057587 | 1048576 | 0.05000 | 1.663 | 2.167    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000029097 | 1048576 | 0.05000 | 1.712 | 2.167    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000140167 | 1048576 | 0.05000 | 1.722 | 2.167    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000009251 | 1048576 | 0.05000 | 0.535 | 1.595    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 184   | 0.545  | 0.723 | 133.100 | 35.9%  | model.layers.22.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 46    | 1.595  | 1.930 | 88.767  | 23.9%  | model.layers.22:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 23    | 2.786  | 2.803 | 64.463  | 17.4%  | model.layers.22:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 47104 | 0.001  | 0.001 | 37.200  | 10.0%  | model.layers.22.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 176   | 0.177  | 0.131 | 23.096  | 6.2%   | model.layers.21.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 88    | 0.061  | 0.105 | 9.229   | 2.5%   | model.layers.21.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 88    | 0.087  | 0.097 | 8.524   | 2.3%   | model.layers.21.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 88    | 0.011  | 0.028 | 2.488   | 0.7%   | model.layers.21.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.6%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000108265 | 1048576 | 0.05000 | 1.857 | 2.120    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000022461 | 1048576 | 0.05000 | 1.865 | 2.120    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000037470 | 1048576 | 0.05000 | 1.914 | 2.120    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000005754 | 1048576 | 0.05000 | 0.578 | 1.632    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 192   | 0.586  | 0.726 | 139.387 | 36.1%  | model.layers.23.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 48    | 1.632  | 1.927 | 92.519  | 23.9%  | model.layers.23:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 24    | 2.799  | 2.803 | 67.262  | 17.4%  | model.layers.23:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 49152 | 0.001  | 0.001 | 38.820  | 10.0%  | model.layers.23.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 184   | 0.151  | 0.129 | 23.675  | 6.1%   | model.layers.22.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 92    | 0.014  | 0.101 | 9.277   | 2.4%   | model.layers.22.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 92    | 0.110  | 0.096 | 8.807   | 2.3%   | model.layers.22.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 92    | 0.012  | 0.028 | 2.578   | 0.7%   | model.layers.22.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.6%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.748  | 0.512 | 2.050   | 0.5%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000018072 | 1048576 | 0.05000 | 1.703 | 2.193    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020235 | 1048576 | 0.05000 | 1.741 | 2.193    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000081634 | 1048576 | 0.05000 | 1.752 | 2.193    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000008647 | 1048576 | 0.05000 | 0.561 | 1.635    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 200   | 0.574  | 0.726 | 145.204 | 35.8%  | model.layers.24.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 50    | 1.635  | 1.927 | 96.347  | 23.7%  | model.layers.24:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 25    | 2.791  | 2.802 | 70.053  | 17.3%  | model.layers.24:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 51200 | 0.001  | 0.001 | 40.439  | 10.0%  | model.layers.24.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 192   | 0.639  | 0.137 | 26.210  | 6.5%   | model.layers.23.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 96    | 0.444  | 0.111 | 10.615  | 2.6%   | model.layers.23.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 96    | 0.165  | 0.100 | 9.635   | 2.4%   | model.layers.23.self_attn.v_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 96    | 0.010  | 0.029 | 2.770   | 0.7%   | model.layers.23.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.6%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000146302 | 1048576 | 0.05000 | 1.681 | 2.152    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000098453 | 1048576 | 0.05000 | 1.759 | 2.152    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000025923 | 1048576 | 0.05000 | 1.769 | 2.152    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000016776 | 1048576 | 0.05000 | 0.539 | 1.590    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 208   | 0.547  | 0.726 | 151.021 | 35.9%  | model.layers.25.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 52    | 1.590  | 1.925 | 100.089 | 23.8%  | model.layers.25:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 26    | 2.798  | 2.802 | 72.851  | 17.3%  | model.layers.25:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 53248 | 0.001  | 0.001 | 42.058  | 10.0%  | model.layers.25.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 200   | 0.174  | 0.134 | 26.881  | 6.4%   | model.layers.24.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 100   | 0.075  | 0.108 | 10.844  | 2.6%   | model.layers.24.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 100   | 0.071  | 0.099 | 9.861   | 2.3%   | model.layers.24.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 100   | 0.011  | 0.029 | 2.860   | 0.7%   | model.layers.24.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.5%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000020178 | 1048576 | 0.05000 | 1.668 | 2.183    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000083713 | 1048576 | 0.05000 | 1.711 | 2.183    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000110736 | 1048576 | 0.05000 | 1.723 | 2.183    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000017859 | 1048576 | 0.05000 | 0.547 | 1.601    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 216   | 0.555  | 0.726 | 156.722 | 35.9%  | model.layers.26.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 54    | 1.601  | 1.924 | 103.873 | 23.8%  | model.layers.26:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.791  | 2.802 | 75.642  | 17.3%  | model.layers.26:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 55296 | 0.001  | 0.001 | 43.688  | 10.0%  | model.layers.26.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 208   | 0.162  | 0.132 | 27.510  | 6.3%   | model.layers.25.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 104   | 0.057  | 0.106 | 11.023  | 2.5%   | model.layers.25.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 104   | 0.079  | 0.097 | 10.126  | 2.3%   | model.layers.25.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 104   | 0.008  | 0.029 | 2.980   | 0.7%   | model.layers.25.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.5%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.q_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000119360 | 1048576 | 0.05000 | 1.690 | 2.147    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.k_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000021660 | 1048576 | 0.05000 | 1.734 | 2.147    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.v_proj          | 1536, 256     | bf16: 0.8MB  | 0.0000092558 | 1048576 | 0.05000 | 1.756 | 2.147    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | self_attn.o_proj          | 1536, 1536    | bf16: 4.6MB  | 0.0000051232 | 1048576 | 0.05000 | 0.551 | 1.592    | cuda 6.79G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Process quant      | 224   | 0.560  | 0.725 | 162.512 | 36.2%  | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 56    | 1.592  | 1.922 | 107.611 | 24.0%  | model.layers.27:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.791  | 2.802 | 75.642  | 16.9%  | model.layers.26:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 57344 | 0.001  | 0.001 | 45.304  | 10.1%  | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 216   | 0.150  | 0.130 | 28.087  | 6.3%   | model.layers.26.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 108   | 0.012  | 0.102 | 11.065  | 2.5%   | model.layers.26.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 108   | 0.108  | 0.096 | 10.404  | 2.3%   | model.layers.26.self_attn.k_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 108   | 0.010  | 0.028 | 3.069   | 0.7%   | model.layers.26.self_attn.v_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.5%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000010618', 'samples': '1048576', 'damp': '0.05000', 'time': '2.236', 'fwd_time': '3.191', '(v)ram': 'cuda 0.69G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000056309', 'samples': '1048576', 'damp': '0.05000', 'time': '2.277', 'fwd_time': '3.191', '(v)ram': 'cuda 0.69G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000001316', 'samples': '1048576', 'damp': '0.05000', 'time': '2.290', 'fwd_time': '3.191', '(v)ram': 'cuda 0.69G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001152', 'samples': '1048576', 'damp': '0.05000', 'time': '0.549', 'fwd_time': '2.406', '(v)ram': 'cuda 0.74G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000010982', 'samples': '1048576', 'damp': '0.05000', 'time': '1.605', 'fwd_time': '2.378', '(v)ram': 'cuda 3.8G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000000499', 'samples': '1048576', 'damp': '0.05000', 'time': '1.645', 'fwd_time': '2.378', '(v)ram': 'cuda 3.8G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003771', 'samples': '1048576', 'damp': '0.05000', 'time': '1.668', 'fwd_time': '2.378', '(v)ram': 'cuda 3.8G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000321', 'samples': '1048576', 'damp': '0.05000', 'time': '0.537', 'fwd_time': '1.606', '(v)ram': 'cuda 3.8G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000045917', 'samples': '1048576', 'damp': '0.05000', 'time': '1.558', 'fwd_time': '2.156', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012877', 'samples': '1048576', 'damp': '0.05000', 'time': '1.596', 'fwd_time': '2.156', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003589', 'samples': '1048576', 'damp': '0.05000', 'time': '1.609', 'fwd_time': '2.156', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000825', 'samples': '1048576', 'damp': '0.05000', 'time': '0.541', 'fwd_time': '1.593', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011183', 'samples': '1048576', 'damp': '0.05000', 'time': '1.565', 'fwd_time': '2.181', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000041165', 'samples': '1048576', 'damp': '0.05000', 'time': '1.571', 'fwd_time': '2.181', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000004210', 'samples': '1048576', 'damp': '0.05000', 'time': '1.602', 'fwd_time': '2.181', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000000775', 'samples': '1048576', 'damp': '0.05000', 'time': '0.561', 'fwd_time': '1.619', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007599', 'samples': '1048576', 'damp': '0.05000', 'time': '1.606', 'fwd_time': '2.179', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000033506', 'samples': '1048576', 'damp': '0.05000', 'time': '1.674', 'fwd_time': '2.179', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000004720', 'samples': '1048576', 'damp': '0.05000', 'time': '1.684', 'fwd_time': '2.179', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001610', 'samples': '1048576', 'damp': '0.05000', 'time': '0.550', 'fwd_time': '1.597', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018593', 'samples': '1048576', 'damp': '0.05000', 'time': '1.571', 'fwd_time': '2.161', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000006658', 'samples': '1048576', 'damp': '0.05000', 'time': '1.600', 'fwd_time': '2.161', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000070386', 'samples': '1048576', 'damp': '0.05000', 'time': '1.613', 'fwd_time': '2.161', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001596', 'samples': '1048576', 'damp': '0.05000', 'time': '0.548', 'fwd_time': '1.585', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000064465', 'samples': '1048576', 'damp': '0.05000', 'time': '1.753', 'fwd_time': '2.178', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000014297', 'samples': '1048576', 'damp': '0.05000', 'time': '1.778', 'fwd_time': '2.178', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007682', 'samples': '1048576', 'damp': '0.05000', 'time': '1.787', 'fwd_time': '2.178', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002429', 'samples': '1048576', 'damp': '0.05000', 'time': '0.555', 'fwd_time': '1.584', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000042238', 'samples': '1048576', 'damp': '0.05000', 'time': '1.593', 'fwd_time': '2.167', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011166', 'samples': '1048576', 'damp': '0.05000', 'time': '1.610', 'fwd_time': '2.167', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000003931', 'samples': '1048576', 'damp': '0.05000', 'time': '1.628', 'fwd_time': '2.167', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000001937', 'samples': '1048576', 'damp': '0.05000', 'time': '0.562', 'fwd_time': '1.574', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000035208', 'samples': '1048576', 'damp': '0.05000', 'time': '1.672', 'fwd_time': '2.172', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000008360', 'samples': '1048576', 'damp': '0.05000', 'time': '1.708', 'fwd_time': '2.172', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005238', 'samples': '1048576', 'damp': '0.05000', 'time': '1.730', 'fwd_time': '2.172', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000004620', 'samples': '1048576', 'damp': '0.05000', 'time': '0.555', 'fwd_time': '1.570', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000070125', 'samples': '1048576', 'damp': '0.05000', 'time': '1.596', 'fwd_time': '2.158', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005353', 'samples': '1048576', 'damp': '0.05000', 'time': '1.618', 'fwd_time': '2.158', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020010', 'samples': '1048576', 'damp': '0.05000', 'time': '1.620', 'fwd_time': '2.158', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002384', 'samples': '1048576', 'damp': '0.05000', 'time': '0.556', 'fwd_time': '1.608', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018003', 'samples': '1048576', 'damp': '0.05000', 'time': '1.608', 'fwd_time': '2.141', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000061867', 'samples': '1048576', 'damp': '0.05000', 'time': '1.631', 'fwd_time': '2.141', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007226', 'samples': '1048576', 'damp': '0.05000', 'time': '1.640', 'fwd_time': '2.141', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003570', 'samples': '1048576', 'damp': '0.05000', 'time': '0.551', 'fwd_time': '1.594', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005563', 'samples': '1048576', 'damp': '0.05000', 'time': '1.717', 'fwd_time': '2.183', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000046783', 'samples': '1048576', 'damp': '0.05000', 'time': '1.753', 'fwd_time': '2.183', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012285', 'samples': '1048576', 'damp': '0.05000', 'time': '1.789', 'fwd_time': '2.183', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002987', 'samples': '1048576', 'damp': '0.05000', 'time': '0.566', 'fwd_time': '1.617', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000007630', 'samples': '1048576', 'damp': '0.05000', 'time': '1.793', 'fwd_time': '2.217', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000053048', 'samples': '1048576', 'damp': '0.05000', 'time': '1.827', 'fwd_time': '2.217', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012987', 'samples': '1048576', 'damp': '0.05000', 'time': '1.846', 'fwd_time': '2.217', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000004906', 'samples': '1048576', 'damp': '0.05000', 'time': '0.620', 'fwd_time': '1.624', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000005295', 'samples': '1048576', 'damp': '0.05000', 'time': '1.800', 'fwd_time': '2.168', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000041821', 'samples': '1048576', 'damp': '0.05000', 'time': '1.849', 'fwd_time': '2.168', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011107', 'samples': '1048576', 'damp': '0.05000', 'time': '1.877', 'fwd_time': '2.168', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003205', 'samples': '1048576', 'damp': '0.05000', 'time': '0.588', 'fwd_time': '1.637', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000103949', 'samples': '1048576', 'damp': '0.05000', 'time': '1.698', 'fwd_time': '2.203', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000009435', 'samples': '1048576', 'damp': '0.05000', 'time': '1.714', 'fwd_time': '2.203', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000023934', 'samples': '1048576', 'damp': '0.05000', 'time': '1.732', 'fwd_time': '2.203', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000002425', 'samples': '1048576', 'damp': '0.05000', 'time': '0.585', 'fwd_time': '1.635', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000011268', 'samples': '1048576', 'damp': '0.05000', 'time': '1.687', 'fwd_time': '2.163', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000013126', 'samples': '1048576', 'damp': '0.05000', 'time': '1.789', 'fwd_time': '2.163', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000063141', 'samples': '1048576', 'damp': '0.05000', 'time': '1.799', 'fwd_time': '2.163', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000003464', 'samples': '1048576', 'damp': '0.05000', 'time': '0.546', 'fwd_time': '1.590', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000008019', 'samples': '1048576', 'damp': '0.05000', 'time': '1.695', 'fwd_time': '2.149', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000012511', 'samples': '1048576', 'damp': '0.05000', 'time': '1.726', 'fwd_time': '2.149', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000074481', 'samples': '1048576', 'damp': '0.05000', 'time': '1.738', 'fwd_time': '2.149', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000004835', 'samples': '1048576', 'damp': '0.05000', 'time': '0.560', 'fwd_time': '1.591', '(v)ram': 'cuda 6.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000024007', 'samples': '1048576', 'damp': '0.05000', 'time': '1.710', 'fwd_time': '2.175', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000089587', 'samples': '1048576', 'damp': '0.05000', 'time': '1.756', 'fwd_time': '2.175', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000017966', 'samples': '1048576', 'damp': '0.05000', 'time': '1.758', 'fwd_time': '2.175', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005272', 'samples': '1048576', 'damp': '0.05000', 'time': '0.583', 'fwd_time': '1.611', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000015306', 'samples': '1048576', 'damp': '0.05000', 'time': '1.738', 'fwd_time': '2.159', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000021431', 'samples': '1048576', 'damp': '0.05000', 'time': '1.766', 'fwd_time': '2.159', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000071866', 'samples': '1048576', 'damp': '0.05000', 'time': '1.776', 'fwd_time': '2.159', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000007051', 'samples': '1048576', 'damp': '0.05000', 'time': '0.560', 'fwd_time': '1.570', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000073190', 'samples': '1048576', 'damp': '0.05000', 'time': '1.736', 'fwd_time': '2.163', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000015707', 'samples': '1048576', 'damp': '0.05000', 'time': '1.768', 'fwd_time': '2.163', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000014265', 'samples': '1048576', 'damp': '0.05000', 'time': '1.778', 'fwd_time': '2.163', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005216', 'samples': '1048576', 'damp': '0.05000', 'time': '0.565', 'fwd_time': '1.629', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000017229', 'samples': '1048576', 'damp': '0.05000', 'time': '1.719', 'fwd_time': '2.160', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000077997', 'samples': '1048576', 'damp': '0.05000', 'time': '1.761', 'fwd_time': '2.160', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016428', 'samples': '1048576', 'damp': '0.05000', 'time': '1.778', 'fwd_time': '2.160', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005249', 'samples': '1048576', 'damp': '0.05000', 'time': '0.550', 'fwd_time': '1.616', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016331', 'samples': '1048576', 'damp': '0.05000', 'time': '1.633', 'fwd_time': '2.166', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000016349', 'samples': '1048576', 'damp': '0.05000', 'time': '1.670', 'fwd_time': '2.166', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000083597', 'samples': '1048576', 'damp': '0.05000', 'time': '1.669', 'fwd_time': '2.166', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000007516', 'samples': '1048576', 'damp': '0.05000', 'time': '0.554', 'fwd_time': '1.578', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000057587', 'samples': '1048576', 'damp': '0.05000', 'time': '1.663', 'fwd_time': '2.167', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000029097', 'samples': '1048576', 'damp': '0.05000', 'time': '1.712', 'fwd_time': '2.167', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000140167', 'samples': '1048576', 'damp': '0.05000', 'time': '1.722', 'fwd_time': '2.167', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000009251', 'samples': '1048576', 'damp': '0.05000', 'time': '0.535', 'fwd_time': '1.595', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000108265', 'samples': '1048576', 'damp': '0.05000', 'time': '1.857', 'fwd_time': '2.120', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000022461', 'samples': '1048576', 'damp': '0.05000', 'time': '1.865', 'fwd_time': '2.120', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000037470', 'samples': '1048576', 'damp': '0.05000', 'time': '1.914', 'fwd_time': '2.120', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000005754', 'samples': '1048576', 'damp': '0.05000', 'time': '0.578', 'fwd_time': '1.632', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000018072', 'samples': '1048576', 'damp': '0.05000', 'time': '1.703', 'fwd_time': '2.193', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020235', 'samples': '1048576', 'damp': '0.05000', 'time': '1.741', 'fwd_time': '2.193', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000081634', 'samples': '1048576', 'damp': '0.05000', 'time': '1.752', 'fwd_time': '2.193', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000008647', 'samples': '1048576', 'damp': '0.05000', 'time': '0.561', 'fwd_time': '1.635', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000146302', 'samples': '1048576', 'damp': '0.05000', 'time': '1.681', 'fwd_time': '2.152', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000098453', 'samples': '1048576', 'damp': '0.05000', 'time': '1.759', 'fwd_time': '2.152', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000025923', 'samples': '1048576', 'damp': '0.05000', 'time': '1.769', 'fwd_time': '2.152', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000016776', 'samples': '1048576', 'damp': '0.05000', 'time': '0.539', 'fwd_time': '1.590', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000020178', 'samples': '1048576', 'damp': '0.05000', 'time': '1.668', 'fwd_time': '2.183', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000083713', 'samples': '1048576', 'damp': '0.05000', 'time': '1.711', 'fwd_time': '2.183', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000110736', 'samples': '1048576', 'damp': '0.05000', 'time': '1.723', 'fwd_time': '2.183', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000017859', 'samples': '1048576', 'damp': '0.05000', 'time': '0.547', 'fwd_time': '1.601', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.q_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000119360', 'samples': '1048576', 'damp': '0.05000', 'time': '1.690', 'fwd_time': '2.147', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.k_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000021660', 'samples': '1048576', 'damp': '0.05000', 'time': '1.734', 'fwd_time': '2.147', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.v_proj', 'feat: in, out': '1536, 256', 'dtype: size': 'bf16: 0.8MB', 'loss': '0.0000092558', 'samples': '1048576', 'damp': '0.05000', 'time': '1.756', 'fwd_time': '2.147', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'self_attn.o_proj', 'feat: in, out': '1536, 1536', 'dtype: size': 'bf16: 4.6MB', 'loss': '0.0000051232', 'samples': '1048576', 'damp': '0.05000', 'time': '0.551', 'fwd_time': '1.592', '(v)ram': 'cuda 6.79G', 'dynamic': None}

INFO  tp-pre-pad summary:
[]

INFO  | Process quant      | 224   | 0.560  | 0.725 | 162.512 | 36.2%  | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 56    | 1.592  | 1.922 | 107.611 | 24.0%  | model.layers.27:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.791  | 2.802 | 75.642  | 16.8%  | model.layers.26:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 57344 | 0.001  | 0.001 | 45.304  | 10.1%  | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 224   | 0.121  | 0.127 | 28.554  | 6.4%   | model.layers.27.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 112   | 0.012  | 0.099 | 11.105  | 2.5%   | model.layers.27.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 112   | 0.087  | 0.094 | 10.562  | 2.4%   | model.layers.27.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 112   | 0.009  | 0.028 | 3.174   | 0.7%   | model.layers.27.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.6%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.5%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Process finalize   | 2     | 0.000  | 0.000 | 0.001   | 0.0%   | tp-pre-pad                                           |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

Writing model shards: 0it [00:00, ?it/s]

INFO  Saved Quantize Config:
{
  "bits": 4,
  "dynamic": {
    "-:.*mlp\\.(gate|up|down)_proj.*": {}
  },
  "group_size": 128,
  "desc_act": false,
  "lm_head": false,
  "quant_method": "gptq",
  "checkpoint_format": "gptq",
  "pack_dtype": "int32",
  "meta": {
    "quantizer": [
      "gptqmodel:5.7.0"
    ],
    "uri": "https://github.com/modelcloud/gptqmodel",
    "damp_percent": 0.05,
    "damp_auto_increment": 0.01,
    "static_groups": false,
    "true_sequential": true,
    "mse": 0.0,
    "gptaq": null,
    "act_group_aware": true,
    "failsafe": {
      "strategy": "rtn",
      "threshold": "0.5%",
      "smooth": {
        "type": "mad",
        "group_size_threshold": 128,
        "k": 2.75
      }
    },
    "offload_to_disk": true,
    "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
    "pack_impl": "cpu",
    "mock_quantization": false,
    "gc_mode": "interval",
    "wait_for_submodule_finalizers": false,
    "auto_forward_data_parallel": true,
    "hessian": {
      "chunk_size": null,
      "chunk_bytes": null,
      "staging_dtype": "float32"
    },
    "vram_strategy": "exclusive"
  },
  "sym": true,
  "format": "gptq"
}

Files in directory:
quant_log.csv
quantize_config.json
generation_config.json
config.json
Content of saved `generation_config.json`:
{
    "bos_token_id": 151643,
    "do_sample": true,
    "eos_token_id": 151643,
    "max_new_tokens": 2048,
    "transformers_version": "5.0.0"
}
Content of saved `config.json`:
{
    "architectures": [
        "Qwen2ForCausalLM"
    ],
    "attention_dropout": 0.0,
    "bos_token_id": 151643,
    "dtype": "bfloat16",
    "eos_token_id": 151643,
    "hidden_act": "silu",
    "hidden_size": 1536,
    "initializer_range": 0.02,
    "intermediate_size": 8960,
    "layer_types": [
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention"
    ],
    "max_position_embeddings": 131072,
    "max_window_layers": 28,
    "model_type": "qwen2",
    "num_attention_heads": 12,
    "num_hidden_layers": 28,
    "num_key_value_heads": 2,
    "pad_token_id": null,
    "quantization_config": {
        "bits": 4,
        "checkpoint_format": "gptq",
        "desc_act": false,
        "dynamic": {
            "-:.*mlp\\.(gate|up|down)_proj.*": {}
        },
        "format": "gptq",
        "group_size": 128,
        "lm_head": false,
        "meta": {
            "act_group_aware": true,
            "auto_forward_data_parallel": true,
            "damp_auto_increment": 0.01,
            "damp_percent": 0.05,
            "failsafe": {
                "smooth": {
                    "group_size_threshold": 128,
                    "k": 2.75,
                    "type": "mad"
                },
                "strategy": "rtn",
                "threshold": "0.5%"
            },
            "gc_mode": "interval",
            "gptaq": null,
            "hessian": {
                "chunk_bytes": null,
                "chunk_size": null,
                "staging_dtype": "float32"
            },
            "mock_quantization": false,
            "mse": 0.0,
            "offload_to_disk": true,
            "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
            "pack_impl": "cpu",
            "quantizer": [
                "gptqmodel:5.7.0"
            ],
            "static_groups": false,
            "true_sequential": true,
            "uri": "https://github.com/modelcloud/gptqmodel",
            "vram_strategy": "exclusive",
            "wait_for_submodule_finalizers": false
        },
        "pack_dtype": "int32",
        "quant_method": "gptq",
        "sym": true
    },
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
        "rope_theta": 1000000.0,
        "rope_type": "default"
    },
    "sliding_window": null,
    "tie_word_embeddings": true,
    "transformers_version": "5.0.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
}

INFO  Module: Sync model.embed_tokens <- from turtle (Embedding)

INFO  Module: Sync lm_head <- from turtle (Linear)

INFO  Module: Re-tied embedding weights on shell model after full sync

INFO  Module: Total synced modules: 2

INFO  Pre-Quantized model size: 2944.44MB, 2.88GB

INFO  Quantized model size: 2727.50MB, 2.66GB

INFO  Size difference: 216.94MB, 0.21GB - 7.37%

INFO  | Process quant      | 224   | 0.560  | 0.725 | 162.512 | 35.5%  | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Pre-quant forward  | 56    | 1.592  | 1.922 | 107.611 | 23.5%  | model.layers.27:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.791  | 2.802 | 75.642  | 16.5%  | model.layers.26:subset2/2                            |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Forward hook       | 57344 | 0.001  | 0.001 | 45.304  | 9.9%   | model.layers.27.self_attn.o_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Submodule finalize | 224   | 0.121  | 0.127 | 28.554  | 6.2%   | model.layers.27.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize create    | 112   | 0.012  | 0.099 | 11.105  | 2.4%   | model.layers.27.self_attn.q_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize pack      | 112   | 0.087  | 0.094 | 10.562  | 2.3%   | model.layers.27.self_attn.q_proj [module.pack_block] |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Model save         | 1     | 8.101  | 8.101 | 8.101   | 1.8%   | /content/artifacts/gptq_w4_g128/attn_only_quant      |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Finalize offload   | 112   | 0.009  | 0.028 | 3.174   | 0.7%   | model.layers.27.self_attn.k_proj                     |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.461  | 0.502 | 2.511   | 0.5%   | auto:Qwen2DecoderLayer                               |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.261  | 2.261 | 2.261   | 0.5%   | cache_inputs:Qwen2DecoderLayer                       |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

INFO  | Process finalize   | 2     | 0.000  | 0.000 | 0.001   | 0.0%   | tp-pre-pad                                           |

INFO  +--------------------+-------+--------+-------+---------+--------+------------------------------------------------------+

2026-03-10 00:00:40,097 | INFO    | Quantization finished in 4:44
2026-03-10 00:05:43,840 | INFO    | Created zip: /content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant/attn_only_quant_quantized_model.zip (2172.80 MB)

Quantized artifact ready.
{
  "variant": "attn_only_quant",
  "base_model": "Qwen/Qwen2-1.5B",
  "quant": {
    "bits": 4,
    "group_size": 128,
    "desc_act": false
  },
  "dynamic_config": {
    "-:.*mlp\\.(gate|up|down)_proj.*": {}
  },
  "artifact_dir": "/content/artifacts/gptq_w4_g128/attn_only_quant",
  "gptq_model_file": "model.safetensors",
  "quantization_elapsed_sec": 284.4835362434387,
  "model_size_gb": 2.6636,
  "bits_per_param": 13.8359,
  "created_at_unix": 1773100840.1789382
}

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,attn_only_quant,GPTQ W4 g128,2.6636,None,13.8359,None,None,None

In [ ]:
from __future__ import annotations

import json
import logging
import math
import os
import re
import time
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd
import torch
from datasets import load_dataset
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from gptqmodel import GPTQModel, QuantizeConfig

# ------------------------------
# Logging
# ------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    force=True,
)
logger = logging.getLogger('gptq_attn_only_quant')

PROJECT_ROOT = Path.cwd().resolve()
VARIANT = 'attn_only_quant'
RUN_NAME = 'gptq_w4_g128_attn_only_quant'
BASE_MODEL = 'Qwen/Qwen2-1.5B'

cfg = {
    'base_model': BASE_MODEL,
    'calibration': {
        'dataset': 'wikitext',
        'dataset_name': 'wikitext-2-raw-v1',
        'split': 'train',
        'num_samples': 512,
        'max_length': 2048,
        'seed': 42,
    },
    'quant': {
        'bits': 4,
        'group_size': 128,
        'desc_act': False,
    },
    'eval': {
        'perplexity': {
            'dataset': 'wikitext',
            'dataset_name': 'wikitext-2-raw-v1',
            'split': 'test',
            'max_length': 2048,
            'stride': 1024,
            'max_eval_tokens': 131072,
            'log_every': 25,
        },
        'gsm8k': {
            'num_fewshot': 8,
            'num_samples': 300,
            'max_new_tokens': 256,
            'log_every': 25,
        },
        'arc_challenge': {
            'num_samples': 500,
            'max_new_tokens': 5,
            'log_every': 50,
        },
    },
    'paths': {
        'artifacts_dir': str(PROJECT_ROOT / 'artifacts'),
        'results_dir': str(PROJECT_ROOT / 'results' / RUN_NAME),
        'calibration_dir': str(PROJECT_ROOT / 'calibration_data'),
        'bundles_dir': str(PROJECT_ROOT / 'zip_bundles' / RUN_NAME),
    },
}

PATHS = {k: Path(v) for k, v in cfg['paths'].items()}
for p in PATHS.values():
    p.mkdir(parents=True, exist_ok=True)

ARTIFACT_DIR = PATHS['artifacts_dir'] / 'gptq_w4_g128' / VARIANT
RESULTS_DIR = PATHS['results_dir'] / VARIANT
BUNDLE_DIR = PATHS['bundles_dir'] / VARIANT
CALIB_DIR = PATHS['calibration_dir']
for p in [ARTIFACT_DIR, RESULTS_DIR, BUNDLE_DIR, CALIB_DIR]:
    p.mkdir(parents=True, exist_ok=True)


def build_dynamic_config(variant: str) -> dict | None:
    if variant == 'full_quant':
        return None
    if variant == 'attn_only_quant':
        return {r'-:.*mlp\.(gate|up|down)_proj.*': {}}
    if variant == 'mlp_only_quant':
        return {r'-:.*self_attn\.(q|k|v|o)_proj.*': {}}
    raise ValueError(f'Unknown variant: {variant}')


print('Working directory:', PROJECT_ROOT)
print('Artifact dir:', ARTIFACT_DIR)
print('Results dir:', RESULTS_DIR)
print('Bundle dir:', BUNDLE_DIR)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

# ------------------------------
# Small utilities
# ------------------------------
def save_json(obj: Any, path: str | Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump(obj, f, indent=2)
    return path


def read_json(path: str | Path, default=None):
    path = Path(path)
    if not path.exists():
        return default
    with open(path) as f:
        return json.load(f)


def zip_directory(source_dir: str | Path, zip_path: str | Path, *, exclude_suffixes=('.lock',), exclude_dirs=('.ipynb_checkpoints',)):
    source_dir = Path(source_dir).resolve()
    zip_path = Path(zip_path).resolve()
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    tmp_zip = zip_path.with_suffix(zip_path.suffix + '.tmp')
    if tmp_zip.exists():
        tmp_zip.unlink()
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(tmp_zip, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        for path in sorted(source_dir.rglob('*')):
            if path.is_dir():
                continue
            if any(part in exclude_dirs for part in path.parts):
                continue
            if path.resolve() in {zip_path, tmp_zip}:
                continue
            if path.suffix in exclude_suffixes:
                continue
            zf.write(path, arcname=str(path.relative_to(source_dir)))

    tmp_zip.replace(zip_path)
    size_mb = zip_path.stat().st_size / (1024 ** 2)
    logger.info('Created zip: %s (%.2f MB)', zip_path, size_mb)
    return zip_path


def find_gptq_model_basename(model_dir: str | Path) -> str | None:
    model_dir = Path(model_dir)
    candidates = sorted(model_dir.glob('*.safetensors'))
    if not candidates:
        return None
    preferred = [p for p in candidates if 'gptq' in p.name.lower()]
    return (preferred[0] if preferred else candidates[0]).name


def estimate_num_params_from_config(model_dir: str | Path) -> int | None:
    cfg_path = Path(model_dir) / 'config.json'
    if not cfg_path.exists():
        return None
    cfg_json = json.loads(cfg_path.read_text())
    hidden_size = cfg_json.get('hidden_size')
    num_hidden_layers = cfg_json.get('num_hidden_layers')
    intermediate_size = cfg_json.get('intermediate_size')
    vocab_size = cfg_json.get('vocab_size')
    if not all(v is not None for v in [hidden_size, num_hidden_layers, intermediate_size, vocab_size]):
        return None
    rough_params = (
        vocab_size * hidden_size +
        num_hidden_layers * (4 * hidden_size * hidden_size) +
        num_hidden_layers * (3 * hidden_size * intermediate_size)
    )
    return int(rough_params)


def model_size_gb(model_dir: str | Path) -> float:
    files = list(Path(model_dir).glob('*.safetensors'))
    total_bytes = sum(p.stat().st_size for p in files)
    return total_bytes / (1024 ** 3)


def bits_per_param(model_dir: str | Path) -> float | None:
    files = list(Path(model_dir).glob('*.safetensors'))
    if not files:
        return None
    total_bytes = sum(p.stat().st_size for p in files)
    n_params = estimate_num_params_from_config(model_dir)
    if not n_params:
        return None
    return 8.0 * total_bytes / n_params


def get_results_state() -> dict:
    state = read_json(RESULTS_DIR / 'state.json', default={})
    return state or {}


def save_results_state(state: dict):
    save_json(state, RESULTS_DIR / 'state.json')
    return state


def update_summary_table(state: dict):
    size_gb = model_size_gb(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    bpp = bits_per_param(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    peak_candidates = []
    for key in ['perplexity', 'gsm8k', 'arc_challenge']:
        if key in state and isinstance(state[key], dict):
            val = state[key].get('peak_vram_gb')
            if val is not None:
                peak_candidates.append(val)

    summary_row = {
        'variant': VARIANT,
        'compression': f"GPTQ W{cfg['quant']['bits']} g{cfg['quant']['group_size']}",
        'model_size_gb': round(size_gb, 4) if size_gb is not None else None,
        'peak_vram_gb': round(max(peak_candidates), 4) if peak_candidates else None,
        'bits_per_param': round(bpp, 4) if bpp is not None else None,
        'perplexity': state.get('perplexity', {}).get('perplexity'),
        'gsm8k_accuracy': state.get('gsm8k', {}).get('accuracy'),
        'arc_accuracy': state.get('arc_challenge', {}).get('accuracy'),
    }
    save_json(summary_row, RESULTS_DIR / 'summary.json')
    pd.DataFrame([summary_row]).to_csv(RESULTS_DIR / 'summary.csv', index=False)
    return summary_row


def _is_gptq_checkpoint(model_path: str | Path) -> bool:
    cfg_path = Path(model_path) / 'config.json'
    if not cfg_path.exists():
        return False
    cfg_json = json.loads(cfg_path.read_text())
    return cfg_json.get('quantization_config', {}).get('quant_method') == 'gptq'


def load_quantized_model_and_tokenizer(model_path: str | Path):
    model_path = Path(model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'left'

    if not _is_gptq_checkpoint(model_path):
        raise ValueError(f'{model_path} is not a GPTQ checkpoint.')

    model_basename = find_gptq_model_basename(model_path)
    if model_basename is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {model_path}')

    model = GPTQModel.load(
        str(model_path),
        device_map='auto',
        trust_remote_code=True,
        model_basename=model_basename,
    )
    model.eval()
    return model, tokenizer


def get_model_device(model):
    if hasattr(model, 'device'):
        return model.device
    if hasattr(model, 'hf_device_map') and model.hf_device_map:
        first_device = next(iter(model.hf_device_map.values()))
        return torch.device(first_device)
    return torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


def generate_text(model, tokenizer, prompt: str, *, max_new_tokens: int):
    device = get_model_device(model)
    encoded = tokenizer(
        prompt,
        return_tensors='pt',
        truncation=True,
        max_length=min(getattr(tokenizer, 'model_max_length', 4096), 4096),
        padding=False,
    )
    input_ids = encoded['input_ids'].to(device)
    attention_mask = encoded['attention_mask'].to(device)

    with torch.inference_mode():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )
    gen_ids = outputs[0][input_ids.shape[-1]:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True)


ANSWER_RE = re.compile(r'####\s*(-?[\d,]+\.?\d*)')


def extract_numeric_answer(text: str):
    m = ANSWER_RE.search(text)
    if m:
        try:
            return float(m.group(1).replace(',', ''))
        except ValueError:
            return None
    nums = re.findall(r'-?[\d,]+\.?\d*', text)
    if not nums:
        return None
    try:
        return float(nums[-1].replace(',', ''))
    except ValueError:
        return None


def format_seconds(sec: float) -> str:
    sec = int(max(sec, 0))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    if h > 0:
        return f'{h:d}:{m:02d}:{s:02d}'
    return f'{m:d}:{s:02d}'


def log_progress(prefix: str, idx: int, total: int, start_time: float, correct: int):
    elapsed = time.time() - start_time
    avg = elapsed / max(idx, 1)
    eta = avg * max(total - idx, 0)
    logger.info(
        '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item',
        prefix,
        idx,
        total,
        correct / max(idx, 1),
        format_seconds(elapsed),
        format_seconds(eta),
        avg,
    )


GSM_PROMPT = """Question: {question}
Answer: Let's think step by step.
"""

def evaluate_gsm8k_only(model, tokenizer, cfg):
    gsm_cfg = cfg['eval']['gsm8k']
    n_shot = gsm_cfg['num_fewshot']
    num_samples = gsm_cfg['num_samples']
    max_new = gsm_cfg['max_new_tokens']
    log_every = gsm_cfg.get('log_every', 25)

    logger.info('Loading GSM8K: %d-shot, %d samples, max_new_tokens=%d', n_shot, num_samples, max_new)
    train_ds = load_dataset('openai/gsm8k', 'main', split='train').shuffle(seed=42)
    test_ds = load_dataset('openai/gsm8k', 'main', split='test').shuffle(seed=42).select(range(num_samples))
    exemplars = train_ds.select(range(n_shot))

    prefix = ''
    for ex in exemplars:
        prefix += GSM_PROMPT.format(question=ex['question']) + ex['answer'] + '\n\n'

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(test_ds)

    for idx, row in enumerate(tqdm(test_ds, desc='GSM8K', unit='q'), start=1):
        prompt = prefix + GSM_PROMPT.format(question=row['question'])

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new)
        pred = extract_numeric_answer(generated)
        gold = extract_numeric_answer(row['answer'])
        is_correct = pred is not None and gold is not None and abs(pred - gold) < 1e-3
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_value': pred,
            'gold_value': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('GSM8K', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'gsm8k',
        'num_fewshot': n_shot,
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'gsm8k_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'gsm8k_metrics.json')

    state = get_results_state()
    state['gsm8k'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    logger.info('GSM8K finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    return result


def format_arc_prompt(row):
    labels = row['choices']['label']
    texts = row['choices']['text']
    prompt = row['question'] + '\n'
    for lbl, txt in zip(labels, texts):
        prompt += f'{lbl}. {txt}\n'
    prompt += 'Answer:'
    return prompt


def evaluate_arc_only(model, tokenizer, cfg):
    arc_cfg = cfg['eval']['arc_challenge']
    num_samples = arc_cfg['num_samples']
    max_new = arc_cfg['max_new_tokens']
    log_every = arc_cfg.get('log_every', 50)

    logger.info('Loading ARC-Challenge: %d samples, max_new_tokens=%d', num_samples, max_new)
    ds = load_dataset('allenai/ai2_arc', 'ARC-Challenge', split='test').shuffle(seed=42).select(range(num_samples))

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(ds)

    for idx, row in enumerate(tqdm(ds, desc='ARC-Challenge', unit='q'), start=1):
        prompt = format_arc_prompt(row)

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new).strip()
        pred = generated[:1].upper() if generated else None
        gold = row['answerKey'].strip().upper()
        is_correct = pred == gold
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_label': pred,
            'gold_label': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('ARC-Challenge', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'arc_challenge',
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'arc_challenge_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'arc_challenge_metrics.json')

    state = get_results_state()
    state['arc_challenge'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    results_zip = zip_directory(RESULTS_DIR, BUNDLE_DIR / 'full_quant_results_only.zip')
    state['results_zip'] = str(results_zip)
    save_results_state(state)

    logger.info('ARC-Challenge finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    print('Results zip:', results_zip)

Working directory: /content
Artifact dir: /content/artifacts/gptq_w4_g128/attn_only_quant
Results dir: /content/results/gptq_w4_g128_attn_only_quant/attn_only_quant
Bundle dir: /content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant
CUDA available: True
GPU: NVIDIA L4

In [ ]:
import os
import json
import time
import math
import torch
from datasets import load_dataset


def evaluate_perplexity_only(model, tokenizer, results_dir):

    print("=" * 80)
    print("PERPLEXITY EVALUATION")
    print("=" * 80)

    dataset_name = "wikitext"
    dataset_config = "wikitext-2-raw-v1"
    split = "test"

    max_length = 2048
    stride = 1024

    print(f"Dataset: {dataset_name}/{dataset_config}")
    print(f"Split: {split}")
    print(f"Max length: {max_length}")
    print(f"Stride: {stride}")

    os.makedirs(results_dir, exist_ok=True)

    print("\nLoading dataset...")
    dataset = load_dataset(dataset_name, dataset_config, split=split)

    text = "\n\n".join(dataset["text"])

    print("Tokenizing...")
    encodings = tokenizer(text, return_tensors="pt")

    input_ids = encodings.input_ids
    seq_len = input_ids.size(1)

    print(f"Total tokens: {seq_len}")

    nlls = []
    prev_end_loc = 0

    start_time = time.time()

    total_steps = math.ceil((seq_len - max_length) / stride) + 1

    step = 0

    for begin_loc in range(0, seq_len, stride):

        end_loc = min(begin_loc + max_length, seq_len)
        trg_len = end_loc - prev_end_loc

        input_ids_slice = input_ids[:, begin_loc:end_loc].to(model.device)

        target_ids = input_ids_slice.clone()
        target_ids[:, :-trg_len] = -100

        with torch.no_grad():

            outputs = model(
                input_ids=input_ids_slice,
                labels=target_ids
            )

            neg_log_likelihood = outputs.loss

        nlls.append(neg_log_likelihood * trg_len)

        prev_end_loc = end_loc

        step += 1

        elapsed = time.time() - start_time
        avg = elapsed / step
        eta = avg * (total_steps - step)

        print(
            f"[PPL] step {step}/{total_steps} | "
            f"tokens {begin_loc}-{end_loc} | "
            f"elapsed {elapsed/60:.2f} min | "
            f"eta {eta/60:.2f} min"
        )

        if end_loc == seq_len:
            break

    ppl = torch.exp(torch.stack(nlls).sum() / end_loc).item()

    metrics = {
        "dataset": "wikitext-2",
        "split": "test",
        "max_length": max_length,
        "stride": stride,
        "perplexity": float(ppl)
    }

    with open(os.path.join(results_dir, "perplexity_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    print("\nPerplexity:", ppl)

    return metrics

In [ ]:
# Cell 2 — Evaluate Perplexity only
# Run this after the quantization cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    perplexity_result = evaluate_perplexity_only(model, tokenizer, RESULTS_DIR)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/ywcpdvot-tkcxvfua/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  The layer model.layers.0.mlp.gate_proj is not quantized.

INFO  The layer model.layers.0.mlp.up_proj is not quantized.

INFO  The layer model.layers.0.mlp.down_proj is not quantized.

INFO  The layer model.layers.1.mlp.gate_proj is not quantized.

INFO  The layer model.layers.1.mlp.up_proj is not quantized.

INFO  The layer model.layers.1.mlp.down_proj is not quantized.

INFO  The layer model.layers.2.mlp.gate_proj is not quantized.

INFO  The layer model.layers.2.mlp.up_proj is not quantized.

INFO  The layer model.layers.2.mlp.down_proj is not quantized.

INFO  The layer model.layers.3.mlp.gate_proj is not quantized.

INFO  The layer model.layers.3.mlp.up_proj is not quantized.

INFO  The layer model.layers.3.mlp.down_proj is not quantized.

INFO  The layer model.layers.4.mlp.gate_proj is not quantized.

INFO  The layer model.layers.4.mlp.up_proj is not quantized.

INFO  The layer model.layers.4.mlp.down_proj is not quantized.

INFO  The layer model.layers.5.mlp.gate_proj is not quantized.

INFO  The layer model.layers.5.mlp.up_proj is not quantized.

INFO  The layer model.layers.5.mlp.down_proj is not quantized.

INFO  The layer model.layers.6.mlp.gate_proj is not quantized.

INFO  The layer model.layers.6.mlp.up_proj is not quantized.

INFO  The layer model.layers.6.mlp.down_proj is not quantized.

INFO  The layer model.layers.7.mlp.gate_proj is not quantized.

INFO  The layer model.layers.7.mlp.up_proj is not quantized.

INFO  The layer model.layers.7.mlp.down_proj is not quantized.

INFO  The layer model.layers.8.mlp.gate_proj is not quantized.

INFO  The layer model.layers.8.mlp.up_proj is not quantized.

INFO  The layer model.layers.8.mlp.down_proj is not quantized.

INFO  The layer model.layers.9.mlp.gate_proj is not quantized.

INFO  The layer model.layers.9.mlp.up_proj is not quantized.

INFO  The layer model.layers.9.mlp.down_proj is not quantized.

INFO  The layer model.layers.10.mlp.gate_proj is not quantized.

INFO  The layer model.layers.10.mlp.up_proj is not quantized.

INFO  The layer model.layers.10.mlp.down_proj is not quantized.

INFO  The layer model.layers.11.mlp.gate_proj is not quantized.

INFO  The layer model.layers.11.mlp.up_proj is not quantized.

INFO  The layer model.layers.11.mlp.down_proj is not quantized.

INFO  The layer model.layers.12.mlp.gate_proj is not quantized.

INFO  The layer model.layers.12.mlp.up_proj is not quantized.

INFO  The layer model.layers.12.mlp.down_proj is not quantized.

INFO  The layer model.layers.13.mlp.gate_proj is not quantized.

INFO  The layer model.layers.13.mlp.up_proj is not quantized.

INFO  The layer model.layers.13.mlp.down_proj is not quantized.

INFO  The layer model.layers.14.mlp.gate_proj is not quantized.

INFO  The layer model.layers.14.mlp.up_proj is not quantized.

INFO  The layer model.layers.14.mlp.down_proj is not quantized.

INFO  The layer model.layers.15.mlp.gate_proj is not quantized.

INFO  The layer model.layers.15.mlp.up_proj is not quantized.

INFO  The layer model.layers.15.mlp.down_proj is not quantized.

INFO  The layer model.layers.16.mlp.gate_proj is not quantized.

INFO  The layer model.layers.16.mlp.up_proj is not quantized.

INFO  The layer model.layers.16.mlp.down_proj is not quantized.

INFO  The layer model.layers.17.mlp.gate_proj is not quantized.

INFO  The layer model.layers.17.mlp.up_proj is not quantized.

INFO  The layer model.layers.17.mlp.down_proj is not quantized.

INFO  The layer model.layers.18.mlp.gate_proj is not quantized.

INFO  The layer model.layers.18.mlp.up_proj is not quantized.

INFO  The layer model.layers.18.mlp.down_proj is not quantized.

INFO  The layer model.layers.19.mlp.gate_proj is not quantized.

INFO  The layer model.layers.19.mlp.up_proj is not quantized.

INFO  The layer model.layers.19.mlp.down_proj is not quantized.

INFO  The layer model.layers.20.mlp.gate_proj is not quantized.

INFO  The layer model.layers.20.mlp.up_proj is not quantized.

INFO  The layer model.layers.20.mlp.down_proj is not quantized.

INFO  The layer model.layers.21.mlp.gate_proj is not quantized.

INFO  The layer model.layers.21.mlp.up_proj is not quantized.

INFO  The layer model.layers.21.mlp.down_proj is not quantized.

INFO  The layer model.layers.22.mlp.gate_proj is not quantized.

INFO  The layer model.layers.22.mlp.up_proj is not quantized.

INFO  The layer model.layers.22.mlp.down_proj is not quantized.

INFO  The layer model.layers.23.mlp.gate_proj is not quantized.

INFO  The layer model.layers.23.mlp.up_proj is not quantized.

INFO  The layer model.layers.23.mlp.down_proj is not quantized.

INFO  The layer model.layers.24.mlp.gate_proj is not quantized.

INFO  The layer model.layers.24.mlp.up_proj is not quantized.

INFO  The layer model.layers.24.mlp.down_proj is not quantized.

INFO  The layer model.layers.25.mlp.gate_proj is not quantized.

INFO  The layer model.layers.25.mlp.up_proj is not quantized.

INFO  The layer model.layers.25.mlp.down_proj is not quantized.

INFO  The layer model.layers.26.mlp.gate_proj is not quantized.

INFO  The layer model.layers.26.mlp.up_proj is not quantized.

INFO  The layer model.layers.26.mlp.down_proj is not quantized.

INFO  The layer model.layers.27.mlp.gate_proj is not quantized.

INFO  The layer model.layers.27.mlp.up_proj is not quantized.

INFO  The layer model.layers.27.mlp.down_proj is not quantized.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-10 00:15:46,131 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  gc.collect() reclaimed 143 objects in 0.356s

2026-03-10 00:15:48,067 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

================================================================================
PERPLEXITY EVALUATION
================================================================================
Dataset: wikitext/wikitext-2-raw-v1
Split: test
Max length: 2048
Stride: 1024

Loading dataset...

2026-03-10 00:15:48,335 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:15:48,566 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:15:48,572 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-10 00:15:48,873 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:15:49,114 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-10 00:15:49,806 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-10 00:15:50,050 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:15:50,283 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-10 00:15:50,545 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-10 00:15:50,782 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:15:51,020 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"

Tokenizing...

Token indices sequence length is longer than the specified maximum sequence length for this model (299078 > 32768). Running this sequence through the model will result in indexing errors

Total tokens: 299078
[PPL] step 1/292 | tokens 0-2048 | elapsed 0.00 min | eta 0.92 min
[PPL] step 2/292 | tokens 1024-3072 | elapsed 0.00 min | eta 0.63 min
[PPL] step 3/292 | tokens 2048-4096 | elapsed 0.01 min | eta 0.70 min
[PPL] step 4/292 | tokens 3072-5120 | elapsed 0.01 min | eta 0.74 min
[PPL] step 5/292 | tokens 4096-6144 | elapsed 0.01 min | eta 0.77 min
[PPL] step 6/292 | tokens 5120-7168 | elapsed 0.02 min | eta 0.79 min
[PPL] step 7/292 | tokens 6144-8192 | elapsed 0.02 min | eta 0.80 min
[PPL] step 8/292 | tokens 7168-9216 | elapsed 0.02 min | eta 0.81 min
[PPL] step 9/292 | tokens 8192-10240 | elapsed 0.03 min | eta 0.81 min
[PPL] step 10/292 | tokens 9216-11264 | elapsed 0.03 min | eta 0.82 min
[PPL] step 11/292 | tokens 10240-12288 | elapsed 0.03 min | eta 0.82 min
[PPL] step 12/292 | tokens 11264-13312 | elapsed 0.04 min | eta 0.82 min
[PPL] step 13/292 | tokens 12288-14336 | elapsed 0.04 min | eta 0.82 min
[PPL] step 14/292 | tokens 13312-15360 | elapsed 0.04 min | eta 0.82 min
[PPL] step 15/292 | tokens 14336-16384 | elapsed 0.04 min | eta 0.82 min
[PPL] step 16/292 | tokens 15360-17408 | elapsed 0.05 min | eta 0.82 min
[PPL] step 17/292 | tokens 16384-18432 | elapsed 0.05 min | eta 0.82 min
[PPL] step 18/292 | tokens 17408-19456 | elapsed 0.05 min | eta 0.82 min
[PPL] step 19/292 | tokens 18432-20480 | elapsed 0.06 min | eta 0.82 min
[PPL] step 20/292 | tokens 19456-21504 | elapsed 0.06 min | eta 0.82 min
[PPL] step 21/292 | tokens 20480-22528 | elapsed 0.06 min | eta 0.81 min
[PPL] step 22/292 | tokens 21504-23552 | elapsed 0.07 min | eta 0.81 min
[PPL] step 23/292 | tokens 22528-24576 | elapsed 0.07 min | eta 0.81 min
[PPL] step 24/292 | tokens 23552-25600 | elapsed 0.07 min | eta 0.81 min
[PPL] step 25/292 | tokens 24576-26624 | elapsed 0.08 min | eta 0.81 min
[PPL] step 26/292 | tokens 25600-27648 | elapsed 0.08 min | eta 0.80 min
[PPL] step 27/292 | tokens 26624-28672 | elapsed 0.08 min | eta 0.80 min
[PPL] step 28/292 | tokens 27648-29696 | elapsed 0.08 min | eta 0.80 min
[PPL] step 29/292 | tokens 28672-30720 | elapsed 0.09 min | eta 0.80 min
[PPL] step 30/292 | tokens 29696-31744 | elapsed 0.09 min | eta 0.80 min
[PPL] step 31/292 | tokens 30720-32768 | elapsed 0.09 min | eta 0.79 min
[PPL] step 32/292 | tokens 31744-33792 | elapsed 0.10 min | eta 0.79 min
[PPL] step 33/292 | tokens 32768-34816 | elapsed 0.10 min | eta 0.79 min
[PPL] step 34/292 | tokens 33792-35840 | elapsed 0.10 min | eta 0.79 min
[PPL] step 35/292 | tokens 34816-36864 | elapsed 0.11 min | eta 0.78 min
[PPL] step 36/292 | tokens 35840-37888 | elapsed 0.11 min | eta 0.78 min
[PPL] step 37/292 | tokens 36864-38912 | elapsed 0.11 min | eta 0.78 min
[PPL] step 38/292 | tokens 37888-39936 | elapsed 0.12 min | eta 0.78 min
[PPL] step 39/292 | tokens 38912-40960 | elapsed 0.12 min | eta 0.77 min
[PPL] step 40/292 | tokens 39936-41984 | elapsed 0.12 min | eta 0.77 min
[PPL] step 41/292 | tokens 40960-43008 | elapsed 0.13 min | eta 0.77 min
[PPL] step 42/292 | tokens 41984-44032 | elapsed 0.13 min | eta 0.76 min
[PPL] step 43/292 | tokens 43008-45056 | elapsed 0.13 min | eta 0.76 min
[PPL] step 44/292 | tokens 44032-46080 | elapsed 0.13 min | eta 0.76 min
[PPL] step 45/292 | tokens 45056-47104 | elapsed 0.14 min | eta 0.76 min
[PPL] step 46/292 | tokens 46080-48128 | elapsed 0.14 min | eta 0.75 min
[PPL] step 47/292 | tokens 47104-49152 | elapsed 0.14 min | eta 0.75 min
[PPL] step 48/292 | tokens 48128-50176 | elapsed 0.15 min | eta 0.75 min
[PPL] step 49/292 | tokens 49152-51200 | elapsed 0.15 min | eta 0.75 min
[PPL] step 50/292 | tokens 50176-52224 | elapsed 0.15 min | eta 0.74 min
[PPL] step 51/292 | tokens 51200-53248 | elapsed 0.16 min | eta 0.74 min
[PPL] step 52/292 | tokens 52224-54272 | elapsed 0.16 min | eta 0.74 min
[PPL] step 53/292 | tokens 53248-55296 | elapsed 0.16 min | eta 0.73 min
[PPL] step 54/292 | tokens 54272-56320 | elapsed 0.17 min | eta 0.73 min
[PPL] step 55/292 | tokens 55296-57344 | elapsed 0.17 min | eta 0.73 min
[PPL] step 56/292 | tokens 56320-58368 | elapsed 0.17 min | eta 0.73 min
[PPL] step 57/292 | tokens 57344-59392 | elapsed 0.18 min | eta 0.72 min
[PPL] step 58/292 | tokens 58368-60416 | elapsed 0.18 min | eta 0.72 min
[PPL] step 59/292 | tokens 59392-61440 | elapsed 0.18 min | eta 0.72 min
[PPL] step 60/292 | tokens 60416-62464 | elapsed 0.18 min | eta 0.71 min
[PPL] step 61/292 | tokens 61440-63488 | elapsed 0.19 min | eta 0.71 min
[PPL] step 62/292 | tokens 62464-64512 | elapsed 0.19 min | eta 0.71 min
[PPL] step 63/292 | tokens 63488-65536 | elapsed 0.19 min | eta 0.71 min
[PPL] step 64/292 | tokens 64512-66560 | elapsed 0.20 min | eta 0.70 min
[PPL] step 65/292 | tokens 65536-67584 | elapsed 0.20 min | eta 0.70 min
[PPL] step 66/292 | tokens 66560-68608 | elapsed 0.20 min | eta 0.70 min
[PPL] step 67/292 | tokens 67584-69632 | elapsed 0.21 min | eta 0.69 min
[PPL] step 68/292 | tokens 68608-70656 | elapsed 0.21 min | eta 0.69 min
[PPL] step 69/292 | tokens 69632-71680 | elapsed 0.21 min | eta 0.69 min
[PPL] step 70/292 | tokens 70656-72704 | elapsed 0.22 min | eta 0.69 min
[PPL] step 71/292 | tokens 71680-73728 | elapsed 0.22 min | eta 0.68 min
[PPL] step 72/292 | tokens 72704-74752 | elapsed 0.22 min | eta 0.68 min
[PPL] step 73/292 | tokens 73728-75776 | elapsed 0.23 min | eta 0.68 min
[PPL] step 74/292 | tokens 74752-76800 | elapsed 0.23 min | eta 0.67 min
[PPL] step 75/292 | tokens 75776-77824 | elapsed 0.23 min | eta 0.67 min
[PPL] step 76/292 | tokens 76800-78848 | elapsed 0.23 min | eta 0.67 min
[PPL] step 77/292 | tokens 77824-79872 | elapsed 0.24 min | eta 0.66 min
[PPL] step 78/292 | tokens 78848-80896 | elapsed 0.24 min | eta 0.66 min
[PPL] step 79/292 | tokens 79872-81920 | elapsed 0.24 min | eta 0.66 min
[PPL] step 80/292 | tokens 80896-82944 | elapsed 0.25 min | eta 0.66 min
[PPL] step 81/292 | tokens 81920-83968 | elapsed 0.25 min | eta 0.65 min
[PPL] step 82/292 | tokens 82944-84992 | elapsed 0.25 min | eta 0.65 min
[PPL] step 83/292 | tokens 83968-86016 | elapsed 0.26 min | eta 0.65 min
[PPL] step 84/292 | tokens 84992-87040 | elapsed 0.26 min | eta 0.64 min
[PPL] step 85/292 | tokens 86016-88064 | elapsed 0.26 min | eta 0.64 min
[PPL] step 86/292 | tokens 87040-89088 | elapsed 0.27 min | eta 0.64 min
[PPL] step 87/292 | tokens 88064-90112 | elapsed 0.27 min | eta 0.63 min
[PPL] step 88/292 | tokens 89088-91136 | elapsed 0.27 min | eta 0.63 min
[PPL] step 89/292 | tokens 90112-92160 | elapsed 0.28 min | eta 0.63 min
[PPL] step 90/292 | tokens 91136-93184 | elapsed 0.28 min | eta 0.63 min
[PPL] step 91/292 | tokens 92160-94208 | elapsed 0.28 min | eta 0.62 min
[PPL] step 92/292 | tokens 93184-95232 | elapsed 0.28 min | eta 0.62 min
[PPL] step 93/292 | tokens 94208-96256 | elapsed 0.29 min | eta 0.62 min
[PPL] step 94/292 | tokens 95232-97280 | elapsed 0.29 min | eta 0.61 min
[PPL] step 95/292 | tokens 96256-98304 | elapsed 0.29 min | eta 0.61 min
[PPL] step 96/292 | tokens 97280-99328 | elapsed 0.30 min | eta 0.61 min
[PPL] step 97/292 | tokens 98304-100352 | elapsed 0.30 min | eta 0.60 min
[PPL] step 98/292 | tokens 99328-101376 | elapsed 0.30 min | eta 0.60 min
[PPL] step 99/292 | tokens 100352-102400 | elapsed 0.31 min | eta 0.60 min
[PPL] step 100/292 | tokens 101376-103424 | elapsed 0.31 min | eta 0.60 min
[PPL] step 101/292 | tokens 102400-104448 | elapsed 0.31 min | eta 0.59 min
[PPL] step 102/292 | tokens 103424-105472 | elapsed 0.32 min | eta 0.59 min
[PPL] step 103/292 | tokens 104448-106496 | elapsed 0.32 min | eta 0.59 min
[PPL] step 104/292 | tokens 105472-107520 | elapsed 0.32 min | eta 0.58 min
[PPL] step 105/292 | tokens 106496-108544 | elapsed 0.33 min | eta 0.58 min
[PPL] step 106/292 | tokens 107520-109568 | elapsed 0.33 min | eta 0.58 min
[PPL] step 107/292 | tokens 108544-110592 | elapsed 0.33 min | eta 0.57 min
[PPL] step 108/292 | tokens 109568-111616 | elapsed 0.34 min | eta 0.57 min
[PPL] step 109/292 | tokens 110592-112640 | elapsed 0.34 min | eta 0.57 min
[PPL] step 110/292 | tokens 111616-113664 | elapsed 0.34 min | eta 0.56 min
[PPL] step 111/292 | tokens 112640-114688 | elapsed 0.34 min | eta 0.56 min
[PPL] step 112/292 | tokens 113664-115712 | elapsed 0.35 min | eta 0.56 min
[PPL] step 113/292 | tokens 114688-116736 | elapsed 0.35 min | eta 0.56 min
[PPL] step 114/292 | tokens 115712-117760 | elapsed 0.35 min | eta 0.55 min
[PPL] step 115/292 | tokens 116736-118784 | elapsed 0.36 min | eta 0.55 min
[PPL] step 116/292 | tokens 117760-119808 | elapsed 0.36 min | eta 0.55 min
[PPL] step 117/292 | tokens 118784-120832 | elapsed 0.36 min | eta 0.54 min
[PPL] step 118/292 | tokens 119808-121856 | elapsed 0.37 min | eta 0.54 min
[PPL] step 119/292 | tokens 120832-122880 | elapsed 0.37 min | eta 0.54 min
[PPL] step 120/292 | tokens 121856-123904 | elapsed 0.37 min | eta 0.53 min
[PPL] step 121/292 | tokens 122880-124928 | elapsed 0.38 min | eta 0.53 min
[PPL] step 122/292 | tokens 123904-125952 | elapsed 0.38 min | eta 0.53 min
[PPL] step 123/292 | tokens 124928-126976 | elapsed 0.38 min | eta 0.53 min
[PPL] step 124/292 | tokens 125952-128000 | elapsed 0.39 min | eta 0.52 min
[PPL] step 125/292 | tokens 126976-129024 | elapsed 0.39 min | eta 0.52 min
[PPL] step 126/292 | tokens 128000-130048 | elapsed 0.39 min | eta 0.52 min
[PPL] step 127/292 | tokens 129024-131072 | elapsed 0.39 min | eta 0.51 min
[PPL] step 128/292 | tokens 130048-132096 | elapsed 0.40 min | eta 0.51 min
[PPL] step 129/292 | tokens 131072-133120 | elapsed 0.40 min | eta 0.51 min
[PPL] step 130/292 | tokens 132096-134144 | elapsed 0.40 min | eta 0.50 min
[PPL] step 131/292 | tokens 133120-135168 | elapsed 0.41 min | eta 0.50 min
[PPL] step 132/292 | tokens 134144-136192 | elapsed 0.41 min | eta 0.50 min
[PPL] step 133/292 | tokens 135168-137216 | elapsed 0.41 min | eta 0.49 min
[PPL] step 134/292 | tokens 136192-138240 | elapsed 0.42 min | eta 0.49 min
[PPL] step 135/292 | tokens 137216-139264 | elapsed 0.42 min | eta 0.49 min
[PPL] step 136/292 | tokens 138240-140288 | elapsed 0.42 min | eta 0.49 min
[PPL] step 137/292 | tokens 139264-141312 | elapsed 0.43 min | eta 0.48 min
[PPL] step 138/292 | tokens 140288-142336 | elapsed 0.43 min | eta 0.48 min
[PPL] step 139/292 | tokens 141312-143360 | elapsed 0.43 min | eta 0.48 min
[PPL] step 140/292 | tokens 142336-144384 | elapsed 0.44 min | eta 0.47 min
[PPL] step 141/292 | tokens 143360-145408 | elapsed 0.44 min | eta 0.47 min
[PPL] step 142/292 | tokens 144384-146432 | elapsed 0.44 min | eta 0.47 min
[PPL] step 143/292 | tokens 145408-147456 | elapsed 0.44 min | eta 0.46 min
[PPL] step 144/292 | tokens 146432-148480 | elapsed 0.45 min | eta 0.46 min
[PPL] step 145/292 | tokens 147456-149504 | elapsed 0.45 min | eta 0.46 min
[PPL] step 146/292 | tokens 148480-150528 | elapsed 0.45 min | eta 0.45 min
[PPL] step 147/292 | tokens 149504-151552 | elapsed 0.46 min | eta 0.45 min
[PPL] step 148/292 | tokens 150528-152576 | elapsed 0.46 min | eta 0.45 min
[PPL] step 149/292 | tokens 151552-153600 | elapsed 0.46 min | eta 0.44 min
[PPL] step 150/292 | tokens 152576-154624 | elapsed 0.47 min | eta 0.44 min
[PPL] step 151/292 | tokens 153600-155648 | elapsed 0.47 min | eta 0.44 min
[PPL] step 152/292 | tokens 154624-156672 | elapsed 0.47 min | eta 0.44 min
[PPL] step 153/292 | tokens 155648-157696 | elapsed 0.48 min | eta 0.43 min
[PPL] step 154/292 | tokens 156672-158720 | elapsed 0.48 min | eta 0.43 min
[PPL] step 155/292 | tokens 157696-159744 | elapsed 0.48 min | eta 0.43 min
[PPL] step 156/292 | tokens 158720-160768 | elapsed 0.49 min | eta 0.42 min
[PPL] step 157/292 | tokens 159744-161792 | elapsed 0.49 min | eta 0.42 min
[PPL] step 158/292 | tokens 160768-162816 | elapsed 0.49 min | eta 0.42 min
[PPL] step 159/292 | tokens 161792-163840 | elapsed 0.49 min | eta 0.41 min
[PPL] step 160/292 | tokens 162816-164864 | elapsed 0.50 min | eta 0.41 min
[PPL] step 161/292 | tokens 163840-165888 | elapsed 0.50 min | eta 0.41 min
[PPL] step 162/292 | tokens 164864-166912 | elapsed 0.50 min | eta 0.40 min
[PPL] step 163/292 | tokens 165888-167936 | elapsed 0.51 min | eta 0.40 min
[PPL] step 164/292 | tokens 166912-168960 | elapsed 0.51 min | eta 0.40 min
[PPL] step 165/292 | tokens 167936-169984 | elapsed 0.51 min | eta 0.40 min
[PPL] step 166/292 | tokens 168960-171008 | elapsed 0.52 min | eta 0.39 min
[PPL] step 167/292 | tokens 169984-172032 | elapsed 0.52 min | eta 0.39 min
[PPL] step 168/292 | tokens 171008-173056 | elapsed 0.52 min | eta 0.39 min
[PPL] step 169/292 | tokens 172032-174080 | elapsed 0.53 min | eta 0.38 min
[PPL] step 170/292 | tokens 173056-175104 | elapsed 0.53 min | eta 0.38 min
[PPL] step 171/292 | tokens 174080-176128 | elapsed 0.53 min | eta 0.38 min
[PPL] step 172/292 | tokens 175104-177152 | elapsed 0.54 min | eta 0.37 min
[PPL] step 173/292 | tokens 176128-178176 | elapsed 0.54 min | eta 0.37 min
[PPL] step 174/292 | tokens 177152-179200 | elapsed 0.54 min | eta 0.37 min
[PPL] step 175/292 | tokens 178176-180224 | elapsed 0.54 min | eta 0.36 min
[PPL] step 176/292 | tokens 179200-181248 | elapsed 0.55 min | eta 0.36 min
[PPL] step 177/292 | tokens 180224-182272 | elapsed 0.55 min | eta 0.36 min
[PPL] step 178/292 | tokens 181248-183296 | elapsed 0.55 min | eta 0.35 min
[PPL] step 179/292 | tokens 182272-184320 | elapsed 0.56 min | eta 0.35 min
[PPL] step 180/292 | tokens 183296-185344 | elapsed 0.56 min | eta 0.35 min
[PPL] step 181/292 | tokens 184320-186368 | elapsed 0.56 min | eta 0.35 min
[PPL] step 182/292 | tokens 185344-187392 | elapsed 0.57 min | eta 0.34 min
[PPL] step 183/292 | tokens 186368-188416 | elapsed 0.57 min | eta 0.34 min
[PPL] step 184/292 | tokens 187392-189440 | elapsed 0.57 min | eta 0.34 min
[PPL] step 185/292 | tokens 188416-190464 | elapsed 0.58 min | eta 0.33 min
[PPL] step 186/292 | tokens 189440-191488 | elapsed 0.58 min | eta 0.33 min
[PPL] step 187/292 | tokens 190464-192512 | elapsed 0.58 min | eta 0.33 min
[PPL] step 188/292 | tokens 191488-193536 | elapsed 0.59 min | eta 0.32 min
[PPL] step 189/292 | tokens 192512-194560 | elapsed 0.59 min | eta 0.32 min
[PPL] step 190/292 | tokens 193536-195584 | elapsed 0.59 min | eta 0.32 min
[PPL] step 191/292 | tokens 194560-196608 | elapsed 0.59 min | eta 0.31 min
[PPL] step 192/292 | tokens 195584-197632 | elapsed 0.60 min | eta 0.31 min
[PPL] step 193/292 | tokens 196608-198656 | elapsed 0.60 min | eta 0.31 min
[PPL] step 194/292 | tokens 197632-199680 | elapsed 0.60 min | eta 0.30 min
[PPL] step 195/292 | tokens 198656-200704 | elapsed 0.61 min | eta 0.30 min
[PPL] step 196/292 | tokens 199680-201728 | elapsed 0.61 min | eta 0.30 min
[PPL] step 197/292 | tokens 200704-202752 | elapsed 0.61 min | eta 0.30 min
[PPL] step 198/292 | tokens 201728-203776 | elapsed 0.62 min | eta 0.29 min
[PPL] step 199/292 | tokens 202752-204800 | elapsed 0.62 min | eta 0.29 min
[PPL] step 200/292 | tokens 203776-205824 | elapsed 0.62 min | eta 0.29 min
[PPL] step 201/292 | tokens 204800-206848 | elapsed 0.63 min | eta 0.28 min
[PPL] step 202/292 | tokens 205824-207872 | elapsed 0.63 min | eta 0.28 min
[PPL] step 203/292 | tokens 206848-208896 | elapsed 0.63 min | eta 0.28 min
[PPL] step 204/292 | tokens 207872-209920 | elapsed 0.63 min | eta 0.27 min
[PPL] step 205/292 | tokens 208896-210944 | elapsed 0.64 min | eta 0.27 min
[PPL] step 206/292 | tokens 209920-211968 | elapsed 0.64 min | eta 0.27 min
[PPL] step 207/292 | tokens 210944-212992 | elapsed 0.64 min | eta 0.26 min
[PPL] step 208/292 | tokens 211968-214016 | elapsed 0.65 min | eta 0.26 min
[PPL] step 209/292 | tokens 212992-215040 | elapsed 0.65 min | eta 0.26 min
[PPL] step 210/292 | tokens 214016-216064 | elapsed 0.65 min | eta 0.26 min
[PPL] step 211/292 | tokens 215040-217088 | elapsed 0.66 min | eta 0.25 min
[PPL] step 212/292 | tokens 216064-218112 | elapsed 0.66 min | eta 0.25 min
[PPL] step 213/292 | tokens 217088-219136 | elapsed 0.66 min | eta 0.25 min
[PPL] step 214/292 | tokens 218112-220160 | elapsed 0.67 min | eta 0.24 min
[PPL] step 215/292 | tokens 219136-221184 | elapsed 0.67 min | eta 0.24 min
[PPL] step 216/292 | tokens 220160-222208 | elapsed 0.67 min | eta 0.24 min
[PPL] step 217/292 | tokens 221184-223232 | elapsed 0.67 min | eta 0.23 min
[PPL] step 218/292 | tokens 222208-224256 | elapsed 0.68 min | eta 0.23 min
[PPL] step 219/292 | tokens 223232-225280 | elapsed 0.68 min | eta 0.23 min
[PPL] step 220/292 | tokens 224256-226304 | elapsed 0.68 min | eta 0.22 min
[PPL] step 221/292 | tokens 225280-227328 | elapsed 0.69 min | eta 0.22 min
[PPL] step 222/292 | tokens 226304-228352 | elapsed 0.69 min | eta 0.22 min
[PPL] step 223/292 | tokens 227328-229376 | elapsed 0.69 min | eta 0.21 min
[PPL] step 224/292 | tokens 228352-230400 | elapsed 0.70 min | eta 0.21 min
[PPL] step 225/292 | tokens 229376-231424 | elapsed 0.70 min | eta 0.21 min
[PPL] step 226/292 | tokens 230400-232448 | elapsed 0.70 min | eta 0.21 min
[PPL] step 227/292 | tokens 231424-233472 | elapsed 0.71 min | eta 0.20 min
[PPL] step 228/292 | tokens 232448-234496 | elapsed 0.71 min | eta 0.20 min
[PPL] step 229/292 | tokens 233472-235520 | elapsed 0.71 min | eta 0.20 min
[PPL] step 230/292 | tokens 234496-236544 | elapsed 0.72 min | eta 0.19 min
[PPL] step 231/292 | tokens 235520-237568 | elapsed 0.72 min | eta 0.19 min
[PPL] step 232/292 | tokens 236544-238592 | elapsed 0.72 min | eta 0.19 min
[PPL] step 233/292 | tokens 237568-239616 | elapsed 0.72 min | eta 0.18 min
[PPL] step 234/292 | tokens 238592-240640 | elapsed 0.73 min | eta 0.18 min
[PPL] step 235/292 | tokens 239616-241664 | elapsed 0.73 min | eta 0.18 min
[PPL] step 236/292 | tokens 240640-242688 | elapsed 0.73 min | eta 0.17 min
[PPL] step 237/292 | tokens 241664-243712 | elapsed 0.74 min | eta 0.17 min
[PPL] step 238/292 | tokens 242688-244736 | elapsed 0.74 min | eta 0.17 min
[PPL] step 239/292 | tokens 243712-245760 | elapsed 0.74 min | eta 0.16 min
[PPL] step 240/292 | tokens 244736-246784 | elapsed 0.75 min | eta 0.16 min
[PPL] step 241/292 | tokens 245760-247808 | elapsed 0.75 min | eta 0.16 min
[PPL] step 242/292 | tokens 246784-248832 | elapsed 0.75 min | eta 0.16 min
[PPL] step 243/292 | tokens 247808-249856 | elapsed 0.76 min | eta 0.15 min
[PPL] step 244/292 | tokens 248832-250880 | elapsed 0.76 min | eta 0.15 min
[PPL] step 245/292 | tokens 249856-251904 | elapsed 0.76 min | eta 0.15 min
[PPL] step 246/292 | tokens 250880-252928 | elapsed 0.76 min | eta 0.14 min
[PPL] step 247/292 | tokens 251904-253952 | elapsed 0.77 min | eta 0.14 min
[PPL] step 248/292 | tokens 252928-254976 | elapsed 0.77 min | eta 0.14 min
[PPL] step 249/292 | tokens 253952-256000 | elapsed 0.77 min | eta 0.13 min
[PPL] step 250/292 | tokens 254976-257024 | elapsed 0.78 min | eta 0.13 min
[PPL] step 251/292 | tokens 256000-258048 | elapsed 0.78 min | eta 0.13 min
[PPL] step 252/292 | tokens 257024-259072 | elapsed 0.78 min | eta 0.12 min
[PPL] step 253/292 | tokens 258048-260096 | elapsed 0.79 min | eta 0.12 min
[PPL] step 254/292 | tokens 259072-261120 | elapsed 0.79 min | eta 0.12 min
[PPL] step 255/292 | tokens 260096-262144 | elapsed 0.79 min | eta 0.12 min
[PPL] step 256/292 | tokens 261120-263168 | elapsed 0.80 min | eta 0.11 min
[PPL] step 257/292 | tokens 262144-264192 | elapsed 0.80 min | eta 0.11 min
[PPL] step 258/292 | tokens 263168-265216 | elapsed 0.80 min | eta 0.11 min
[PPL] step 259/292 | tokens 264192-266240 | elapsed 0.81 min | eta 0.10 min
[PPL] step 260/292 | tokens 265216-267264 | elapsed 0.81 min | eta 0.10 min
[PPL] step 261/292 | tokens 266240-268288 | elapsed 0.81 min | eta 0.10 min
[PPL] step 262/292 | tokens 267264-269312 | elapsed 0.81 min | eta 0.09 min
[PPL] step 263/292 | tokens 268288-270336 | elapsed 0.82 min | eta 0.09 min
[PPL] step 264/292 | tokens 269312-271360 | elapsed 0.82 min | eta 0.09 min
[PPL] step 265/292 | tokens 270336-272384 | elapsed 0.82 min | eta 0.08 min
[PPL] step 266/292 | tokens 271360-273408 | elapsed 0.83 min | eta 0.08 min
[PPL] step 267/292 | tokens 272384-274432 | elapsed 0.83 min | eta 0.08 min

In [ ]:

# Cell 3 — Evaluate on GSM8K only
# Run this after the Perplexity cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    gsm8k_result = evaluate_gsm8k_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

In [ ]:

# Cell 4 — Evaluate on ARC-Challenge only and finalize the summary/results zip
# Run this after the GSM8K cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/pnnvijib-iqbxrhpb/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  The layer model.layers.0.mlp.gate_proj is not quantized.

INFO  The layer model.layers.0.mlp.up_proj is not quantized.

INFO  The layer model.layers.0.mlp.down_proj is not quantized.

INFO  The layer model.layers.1.mlp.gate_proj is not quantized.

INFO  The layer model.layers.1.mlp.up_proj is not quantized.

INFO  The layer model.layers.1.mlp.down_proj is not quantized.

INFO  The layer model.layers.2.mlp.gate_proj is not quantized.

INFO  The layer model.layers.2.mlp.up_proj is not quantized.

INFO  The layer model.layers.2.mlp.down_proj is not quantized.

INFO  The layer model.layers.3.mlp.gate_proj is not quantized.

INFO  The layer model.layers.3.mlp.up_proj is not quantized.

INFO  The layer model.layers.3.mlp.down_proj is not quantized.

INFO  The layer model.layers.4.mlp.gate_proj is not quantized.

INFO  The layer model.layers.4.mlp.up_proj is not quantized.

INFO  The layer model.layers.4.mlp.down_proj is not quantized.

INFO  The layer model.layers.5.mlp.gate_proj is not quantized.

INFO  The layer model.layers.5.mlp.up_proj is not quantized.

INFO  The layer model.layers.5.mlp.down_proj is not quantized.

INFO  The layer model.layers.6.mlp.gate_proj is not quantized.

INFO  The layer model.layers.6.mlp.up_proj is not quantized.

INFO  The layer model.layers.6.mlp.down_proj is not quantized.

INFO  The layer model.layers.7.mlp.gate_proj is not quantized.

INFO  The layer model.layers.7.mlp.up_proj is not quantized.

INFO  The layer model.layers.7.mlp.down_proj is not quantized.

INFO  The layer model.layers.8.mlp.gate_proj is not quantized.

INFO  The layer model.layers.8.mlp.up_proj is not quantized.

INFO  The layer model.layers.8.mlp.down_proj is not quantized.

INFO  The layer model.layers.9.mlp.gate_proj is not quantized.

INFO  The layer model.layers.9.mlp.up_proj is not quantized.

INFO  The layer model.layers.9.mlp.down_proj is not quantized.

INFO  The layer model.layers.10.mlp.gate_proj is not quantized.

INFO  The layer model.layers.10.mlp.up_proj is not quantized.

INFO  The layer model.layers.10.mlp.down_proj is not quantized.

INFO  The layer model.layers.11.mlp.gate_proj is not quantized.

INFO  The layer model.layers.11.mlp.up_proj is not quantized.

INFO  The layer model.layers.11.mlp.down_proj is not quantized.

INFO  The layer model.layers.12.mlp.gate_proj is not quantized.

INFO  The layer model.layers.12.mlp.up_proj is not quantized.

INFO  The layer model.layers.12.mlp.down_proj is not quantized.

INFO  The layer model.layers.13.mlp.gate_proj is not quantized.

INFO  The layer model.layers.13.mlp.up_proj is not quantized.

INFO  The layer model.layers.13.mlp.down_proj is not quantized.

INFO  The layer model.layers.14.mlp.gate_proj is not quantized.

INFO  The layer model.layers.14.mlp.up_proj is not quantized.

INFO  The layer model.layers.14.mlp.down_proj is not quantized.

INFO  The layer model.layers.15.mlp.gate_proj is not quantized.

INFO  The layer model.layers.15.mlp.up_proj is not quantized.

INFO  The layer model.layers.15.mlp.down_proj is not quantized.

INFO  The layer model.layers.16.mlp.gate_proj is not quantized.

INFO  The layer model.layers.16.mlp.up_proj is not quantized.

INFO  The layer model.layers.16.mlp.down_proj is not quantized.

INFO  The layer model.layers.17.mlp.gate_proj is not quantized.

INFO  The layer model.layers.17.mlp.up_proj is not quantized.

INFO  The layer model.layers.17.mlp.down_proj is not quantized.

INFO  The layer model.layers.18.mlp.gate_proj is not quantized.

INFO  The layer model.layers.18.mlp.up_proj is not quantized.

INFO  The layer model.layers.18.mlp.down_proj is not quantized.

INFO  The layer model.layers.19.mlp.gate_proj is not quantized.

INFO  The layer model.layers.19.mlp.up_proj is not quantized.

INFO  The layer model.layers.19.mlp.down_proj is not quantized.

INFO  The layer model.layers.20.mlp.gate_proj is not quantized.

INFO  The layer model.layers.20.mlp.up_proj is not quantized.

INFO  The layer model.layers.20.mlp.down_proj is not quantized.

INFO  The layer model.layers.21.mlp.gate_proj is not quantized.

INFO  The layer model.layers.21.mlp.up_proj is not quantized.

INFO  The layer model.layers.21.mlp.down_proj is not quantized.

INFO  The layer model.layers.22.mlp.gate_proj is not quantized.

INFO  The layer model.layers.22.mlp.up_proj is not quantized.

INFO  The layer model.layers.22.mlp.down_proj is not quantized.

INFO  The layer model.layers.23.mlp.gate_proj is not quantized.

INFO  The layer model.layers.23.mlp.up_proj is not quantized.

INFO  The layer model.layers.23.mlp.down_proj is not quantized.

INFO  The layer model.layers.24.mlp.gate_proj is not quantized.

INFO  The layer model.layers.24.mlp.up_proj is not quantized.

INFO  The layer model.layers.24.mlp.down_proj is not quantized.

INFO  The layer model.layers.25.mlp.gate_proj is not quantized.

INFO  The layer model.layers.25.mlp.up_proj is not quantized.

INFO  The layer model.layers.25.mlp.down_proj is not quantized.

INFO  The layer model.layers.26.mlp.gate_proj is not quantized.

INFO  The layer model.layers.26.mlp.up_proj is not quantized.

INFO  The layer model.layers.26.mlp.down_proj is not quantized.

INFO  The layer model.layers.27.mlp.gate_proj is not quantized.

INFO  The layer model.layers.27.mlp.up_proj is not quantized.

INFO  The layer model.layers.27.mlp.down_proj is not quantized.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-10 00:12:44,585 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  gc.collect() reclaimed 143 objects in 0.339s

2026-03-10 00:12:46,478 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

2026-03-10 00:12:46,499 | INFO    | Loading ARC-Challenge: 500 samples, max_new_tokens=5
2026-03-10 00:12:46,742 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 00:12:46,750 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/allenai/ai2_arc/210d026faf9955653af8916fad021475a3f00453/README.md "HTTP/1.1 200 OK"
2026-03-10 00:12:46,970 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/allenai/ai2_arc/210d026faf9955653af8916fad021475a3f00453/README.md "HTTP/1.1 200 OK"

README.md: 0.00B [00:00, ?B/s]

2026-03-10 00:12:47,214 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-10 00:12:47,905 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/allenai/ai2_arc/allenai/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-10 00:12:48,211 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/revision/210d026faf9955653af8916fad021475a3f00453 "HTTP/1.1 200 OK"
2026-03-10 00:12:48,452 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-10 00:12:48,714 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=allenai/ai2_arc "HTTP/1.1 200 OK"
2026-03-10 00:12:48,947 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 00:12:49,194 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-03-10 00:12:49,434 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-03-10 00:12:49,671 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/train-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-03-10 00:12:49,901 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/allenai/ai2_arc/xet-read-token/210d026faf9955653af8916fad021475a3f00453 "HTTP/1.1 200 OK"

ARC-Challenge/train-00000-of-00001.parqu(…):   0%|          | 0.00/190k [00:00<?, ?B/s]

2026-03-10 00:12:51,132 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/test-00000-of-00001.parquet "HTTP/1.1 302 Found"

ARC-Challenge/test-00000-of-00001.parque(…):   0%|          | 0.00/204k [00:00<?, ?B/s]

2026-03-10 00:12:51,704 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ARC-Challenge/validation-00000-of-00001.parquet "HTTP/1.1 302 Found"

ARC-Challenge/validation-00000-of-00001.(…):   0%|          | 0.00/55.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1119 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1172 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/299 [00:00<?, ? examples/s]

ARC-Challenge:   0%|          | 0/500 [00:00<?, ?q/s]

2026-03-10 00:13:09,851 | INFO    | ARC-Challenge | 50/500 | acc=0.6400 | elapsed=0:17 | eta=2:39 | 0.35s/item
2026-03-10 00:13:24,615 | INFO    | ARC-Challenge | 100/500 | acc=0.6800 | elapsed=0:32 | eta=2:09 | 0.32s/item
2026-03-10 00:13:39,345 | INFO    | ARC-Challenge | 150/500 | acc=0.6867 | elapsed=0:47 | eta=1:50 | 0.31s/item
2026-03-10 00:13:54,084 | INFO    | ARC-Challenge | 200/500 | acc=0.6550 | elapsed=1:01 | eta=1:32 | 0.31s/item
2026-03-10 00:14:08,770 | INFO    | ARC-Challenge | 250/500 | acc=0.6520 | elapsed=1:16 | eta=1:16 | 0.31s/item
2026-03-10 00:14:23,492 | INFO    | ARC-Challenge | 300/500 | acc=0.6433 | elapsed=1:31 | eta=1:00 | 0.30s/item
2026-03-10 00:14:38,144 | INFO    | ARC-Challenge | 350/500 | acc=0.6314 | elapsed=1:46 | eta=0:45 | 0.30s/item
2026-03-10 00:14:52,784 | INFO    | ARC-Challenge | 400/500 | acc=0.6375 | elapsed=2:00 | eta=0:30 | 0.30s/item
2026-03-10 00:15:07,405 | INFO    | ARC-Challenge | 450/500 | acc=0.6444 | elapsed=2:15 | eta=0:15 | 0.30s/item
2026-03-10 00:15:22,009 | INFO    | ARC-Challenge | 500/500 | acc=0.6480 | elapsed=2:29 | eta=0:00 | 0.30s/item
2026-03-10 00:15:22,026 | INFO    | Created zip: /content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant/full_quant_results_only.zip (0.03 MB)
2026-03-10 00:15:22,027 | INFO    | ARC-Challenge finished | acc=0.6480 | elapsed=2:29 | peak_vram_gb=11.182299613952637

,dataset,num_samples,max_new_tokens,accuracy,correct,elapsed_sec,elapsed_hms,peak_vram_gb
0,arc_challenge,500,5,0.648,324,149.871307,2:29,11.1823

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,attn_only_quant,GPTQ W4 g128,2.6636,11.1823,13.8359,None,None,0.648

Results zip: /content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant/full_quant_results_only.zip

In [16]:
# Optional: inspect the final table row (Perplexity + GSM8K + ARC) and all saved files
state = get_results_state()
summary = update_summary_table(state)
print(json.dumps(state, indent=2))
display(pd.DataFrame([summary]))
print('\nSaved files under results:')
for p in sorted(RESULTS_DIR.glob('*')):
    print('-', p.name)
print('\nSaved bundles:')
for p in sorted(BUNDLE_DIR.glob('*')):
    print('-', p.name)

{
  "quantization": {
    "variant": "attn_only_quant",
    "base_model": "Qwen/Qwen2-1.5B",
    "quant": {
      "bits": 4,
      "group_size": 128,
      "desc_act": false
    },
    "dynamic_config": {
      "-:.*mlp\\.(gate|up|down)_proj.*": {}
    },
    "artifact_dir": "/content/artifacts/gptq_w4_g128/attn_only_quant",
    "gptq_model_file": "model.safetensors",
    "quantization_elapsed_sec": 284.4835362434387,
    "model_size_gb": 2.6636,
    "bits_per_param": 13.8359,
    "created_at_unix": 1773100840.1789382,
    "zip_path": "/content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant/attn_only_quant_quantized_model.zip"
  },
  "arc_challenge": {
    "dataset": "arc_challenge",
    "num_samples": 500,
    "max_new_tokens": 5,
    "accuracy": 0.648,
    "correct": 324,
    "elapsed_sec": 149.8713071346283,
    "elapsed_hms": "2:29",
    "peak_vram_gb": 11.182299613952637
  },
  "results_zip": "/content/zip_bundles/gptq_w4_g128_attn_only_quant/attn_only_quant/full_quant_results_only.zip"
}

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,attn_only_quant,GPTQ W4 g128,2.6636,11.1823,13.8359,None,None,0.648

Saved files under results:
- arc_challenge_metrics.json
- arc_challenge_predictions.csv
- perplexity_metrics.json
- quantization_manifest.json
- state.json
- summary.csv
- summary.json

Saved bundles:
- attn_only_quant_quantized_model.zip
- full_quant_results_only.zip