# GPTQ MLP-only notebook — Perplexity + GSM8K + ARC-Challenge

This notebook runs the same execution order as the full-quant notebook, but for **Qwen2-1.5B MLP-only GPTQ quantization**:

1. quantize and save the model artifact
2. evaluate **Perplexity** on WikiText-2
3. evaluate **GSM8K**
4. evaluate **ARC-Challenge**

It saves:
- quantized GPTQ artifact folder
- quantized model zip
- perplexity / GSM8K / ARC-Challenge metrics and predictions
- summary table row
- results-only zip

In [ ]:

# Colab / notebook setup
!pip install -U pip setuptools wheel
!pip install -U gptqmodel
!pip install -q torch transformers accelerate datasets pandas pyarrow safetensors tqdm

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (26.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (82.0.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from wheel) (26.0)
Collecting gptqmodel
  Using cached gptqmodel-5.7.0.tar.gz (668 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate>=1.10.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.12.0)
Collecting numpy==2.2.6 (from gptqmodel)
  Using cached numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: torch>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (2.10.0+cu128)
Requirement already satisfied: safetensors>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.7.0)
Requirement already satisfied: transformers>=4.57.1 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (5.0.0)
Requirement already satisfied: threadpoolctl>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (3.6.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (26.0)
Collecting device-smi>=0.5.3 (from gptqmodel)
  Using cached device_smi-0.5.3.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting protobuf>=6.32.0 (from gptqmodel)
  Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: pillow>=11.3.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (11.3.0)
Collecting hf_transfer>=0.1.9 (from gptqmodel)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: huggingface_hub>=0.34.4 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (1.5.0)
Collecting tokenicer>=0.0.6 (from gptqmodel)
  Downloading tokenicer-0.0.8.tar.gz (9.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting logbar>=0.2.1 (from gptqmodel)
  Downloading logbar-0.2.2.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting maturin>=1.9.4 (from gptqmodel)
  Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl.metadata (16 kB)
Requirement already satisfied: datasets>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (4.0.0)
Collecting pyarrow>=21.0 (from gptqmodel)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from gptqmodel) (0.3.8)
Collecting pypcre>=0.2.9 (from gptqmodel)
  Downloading pypcre-0.2.12.tar.gz (119 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting torchao>=0.14.1 (from gptqmodel)
  Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting kernels>=0.11.1 (from gptqmodel)
  Downloading kernels-0.12.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.10.1->gptqmodel) (6.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.24.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.6.0->gptqmodel) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (1.22.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (3.11)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.6.0->gptqmodel) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.4->gptqmodel) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.34.4->gptqmodel) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.6.0->gptqmodel) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (82.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->gptqmodel) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.8.0->gptqmodel) (1.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.8.0->gptqmodel) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.1->gptqmodel) (0.24.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.8.0->gptqmodel) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.6.0->gptqmodel) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.6.0->gptqmodel) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.34.4->gptqmodel) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.34.4->gptqmodel) (0.1.2)
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 67.3 MB/s  0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 123.7 MB/s  0:00:00
Downloading kernels-0.12.2-py3-none-any.whl (55 kB)
Downloading maturin-1.12.6-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 161.6 MB/s  0:00:00
Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 78.3 MB/s  0:00:00
Downloading torchao-0.16.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 53.8 MB/s  0:00:00
Building wheels for collected packages: gptqmodel, device-smi, logbar, pypcre, tokenicer
  Building wheel for gptqmodel (pyproject.toml) ... done
  Created wheel for gptqmodel: filename=gptqmodel-5.7.0-py3-none-any.whl size=817346 sha256=04064efd6f5bd7e52bdac29334eb4c39c94abb8fdd3b6a5e49d4372e94231623
  Stored in directory: /root/.cache/pip/wheels/f1/89/4a/76480c491998e47c9b7dc4b46b9839d4c9bbb547595240e42f
  Building wheel for device-smi (pyproject.toml) ... done
  Created wheel for device-smi: filename=device_smi-0.5.3-py3-none-any.whl size=19983 sha256=cc6778ba732a33b2c5024ceb68e221900200f6e8f67e3cc60ca87c26604fe4c6
  Stored in directory: /root/.cache/pip/wheels/49/e4/63/c7c798f3ca05e6d3e15269dc7789adf9214fb1f5324cf2f0e3
  Building wheel for logbar (pyproject.toml) ... done
  Created wheel for logbar: filename=logbar-0.2.2-py3-none-any.whl size=31310 sha256=82b6d58e8c6f940fb68ebd97573716e8f7d8dcd641e410f8aa75aa226c8383aa
  Stored in directory: /root/.cache/pip/wheels/8d/89/e6/c44856115298a2e8c1d0fe2cbfedd1090372f68c5083cdacf9
  Building wheel for pypcre (pyproject.toml) ... done
  Created wheel for pypcre: filename=pypcre-0.2.12-cp312-cp312-linux_x86_64.whl size=204032 sha256=8cb43509de12872f7acc5a727dfc11458501d5a4df7e96611b9d3928526e95f2
  Stored in directory: /root/.cache/pip/wheels/30/ab/28/ed1230e6afa79e0412bc432fcce0ca7e26bfe74ccd0567154a
  Building wheel for tokenicer (pyproject.toml) ... done
  Created wheel for tokenicer: filename=tokenicer-0.0.8-py3-none-any.whl size=11710 sha256=1e2ab1dfefb68fbd3c35321d472ef7e3468661292d9c71a96d59d28abbeea68c
  Stored in directory: /root/.cache/pip/wheels/0d/5c/f8/f551cf580b631f76fb0e802127948b414c906b768fac0cf662
Successfully built gptqmodel device-smi logbar pypcre tokenicer
Installing collected packages: torchao, tokenicer, pypcre, pyarrow, protobuf, numpy, maturin, logbar, hf_transfer, device-smi, kernels, gptqmodel
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [gptqmodel]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-trace 1.18.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-dataproc 5.25.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
googleapis-common-protos 1.72.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-resource-manager 1.16.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-firestore 2.23.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.0 which is incompatible.
grpc-google-iam-v1 0.14.3 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigtable 2.35.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 7.34.0 which is incompatible.
google-cloud-aiplatform 1.139.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-bigquery-storage 2.36.2 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-appengine-logging 1.8.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-spanner 3.63.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.
google-cloud-iam 2.21.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.0 which is incompatible.

KeyboardInterrupt:

In [ ]:

# Restart once after installation in a fresh runtime, then skip this cell on reruns.
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

In [ ]:

from __future__ import annotations

import json
import logging
import math
import os
import re
import time
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd
import torch
from datasets import load_dataset
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from gptqmodel import GPTQModel, QuantizeConfig

# ------------------------------
# Logging
# ------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    force=True,
)
logger = logging.getLogger('gptq_mlp_only_quant')

PROJECT_ROOT = Path.cwd().resolve()
VARIANT = 'mlp_only_quant'
RUN_NAME = 'gptq_w4_g128_mlp_only_quant'
BASE_MODEL = 'Qwen/Qwen2-1.5B'

cfg = {
    'base_model': BASE_MODEL,
    'calibration': {
        'dataset': 'wikitext',
        'dataset_name': 'wikitext-2-raw-v1',
        'split': 'train',
        'num_samples': 512,
        'max_length': 2048,
        'seed': 42,
    },
    'quant': {
        'bits': 4,
        'group_size': 128,
        'desc_act': False,
    },
    'eval': {
        'perplexity': {
            'dataset': 'wikitext',
            'dataset_name': 'wikitext-2-raw-v1',
            'split': 'test',
            'max_length': 2048,
            'stride': 1024,
            'max_eval_tokens': 131072,
            'log_every': 25,
        },
        'gsm8k': {
            'num_fewshot': 8,
            'num_samples': 300,
            'max_new_tokens': 256,
            'log_every': 25,
        },
        'arc_challenge': {
            'num_samples': 500,
            'max_new_tokens': 5,
            'log_every': 50,
        },
    },
    'paths': {
        'artifacts_dir': str(PROJECT_ROOT / 'artifacts'),
        'results_dir': str(PROJECT_ROOT / 'results' / RUN_NAME),
        'calibration_dir': str(PROJECT_ROOT / 'calibration_data'),
        'bundles_dir': str(PROJECT_ROOT / 'zip_bundles' / RUN_NAME),
    },
}

PATHS = {k: Path(v) for k, v in cfg['paths'].items()}
for p in PATHS.values():
    p.mkdir(parents=True, exist_ok=True)

ARTIFACT_DIR = PATHS['artifacts_dir'] / 'gptq_w4_g128' / VARIANT
RESULTS_DIR = PATHS['results_dir'] / VARIANT
BUNDLE_DIR = PATHS['bundles_dir'] / VARIANT
CALIB_DIR = PATHS['calibration_dir']
for p in [ARTIFACT_DIR, RESULTS_DIR, BUNDLE_DIR, CALIB_DIR]:
    p.mkdir(parents=True, exist_ok=True)


def build_dynamic_config(variant: str) -> dict | None:
    if variant == 'full_quant':
        return None
    if variant == 'attn_only_quant':
        return {r'-:.*mlp\.(gate|up|down)_proj.*': {}}
    if variant == 'mlp_only_quant':
        return {r'-:.*self_attn\.(q|k|v|o)_proj.*': {}}
    raise ValueError(f'Unknown variant: {variant}')

print('Working directory:', PROJECT_ROOT)
print('Artifact dir:', ARTIFACT_DIR)
print('Results dir:', RESULTS_DIR)
print('Bundle dir:', BUNDLE_DIR)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

# ------------------------------
# Small utilities
# ------------------------------
def save_json(obj: Any, path: str | Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump(obj, f, indent=2)
    return path


def read_json(path: str | Path, default=None):
    path = Path(path)
    if not path.exists():
        return default
    with open(path) as f:
        return json.load(f)


def zip_directory(source_dir: str | Path, zip_path: str | Path, *, exclude_suffixes=('.lock',), exclude_dirs=('.ipynb_checkpoints',)):
    source_dir = Path(source_dir).resolve()
    zip_path = Path(zip_path).resolve()
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    tmp_zip = zip_path.with_suffix(zip_path.suffix + '.tmp')
    if tmp_zip.exists():
        tmp_zip.unlink()
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(tmp_zip, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        for path in sorted(source_dir.rglob('*')):
            if path.is_dir():
                continue
            if any(part in exclude_dirs for part in path.parts):
                continue
            if path.resolve() in {zip_path, tmp_zip}:
                continue
            if path.suffix in exclude_suffixes:
                continue
            zf.write(path, arcname=str(path.relative_to(source_dir)))

    tmp_zip.replace(zip_path)
    size_mb = zip_path.stat().st_size / (1024 ** 2)
    logger.info('Created zip: %s (%.2f MB)', zip_path, size_mb)
    return zip_path


def find_gptq_model_basename(model_dir: str | Path) -> str | None:
    model_dir = Path(model_dir)
    candidates = sorted(model_dir.glob('*.safetensors'))
    if not candidates:
        return None
    preferred = [p for p in candidates if 'gptq' in p.name.lower()]
    return (preferred[0] if preferred else candidates[0]).name


def estimate_num_params_from_config(model_dir: str | Path) -> int | None:
    cfg_path = Path(model_dir) / 'config.json'
    if not cfg_path.exists():
        return None
    cfg_json = json.loads(cfg_path.read_text())
    hidden_size = cfg_json.get('hidden_size')
    num_hidden_layers = cfg_json.get('num_hidden_layers')
    intermediate_size = cfg_json.get('intermediate_size')
    vocab_size = cfg_json.get('vocab_size')
    if not all(v is not None for v in [hidden_size, num_hidden_layers, intermediate_size, vocab_size]):
        return None
    rough_params = (
        vocab_size * hidden_size +
        num_hidden_layers * (4 * hidden_size * hidden_size) +
        num_hidden_layers * (3 * hidden_size * intermediate_size)
    )
    return int(rough_params)


def model_size_gb(model_dir: str | Path) -> float:
    files = list(Path(model_dir).glob('*.safetensors'))
    total_bytes = sum(p.stat().st_size for p in files)
    return total_bytes / (1024 ** 3)


def bits_per_param(model_dir: str | Path) -> float | None:
    files = list(Path(model_dir).glob('*.safetensors'))
    if not files:
        return None
    total_bytes = sum(p.stat().st_size for p in files)
    n_params = estimate_num_params_from_config(model_dir)
    if not n_params:
        return None
    return 8.0 * total_bytes / n_params


def get_results_state() -> dict:
    state = read_json(RESULTS_DIR / 'state.json', default={})
    return state or {}


def save_results_state(state: dict):
    save_json(state, RESULTS_DIR / 'state.json')
    return state


def update_summary_table(state: dict):
    size_gb = model_size_gb(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    bpp = bits_per_param(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    peak_candidates = []
    for key in ['perplexity', 'gsm8k', 'arc_challenge']:
        if key in state and isinstance(state[key], dict):
            val = state[key].get('peak_vram_gb')
            if val is not None:
                peak_candidates.append(val)

    summary_row = {
        'variant': VARIANT,
        'compression': f"GPTQ W{cfg['quant']['bits']} g{cfg['quant']['group_size']}",
        'model_size_gb': round(size_gb, 4) if size_gb is not None else None,
        'peak_vram_gb': round(max(peak_candidates), 4) if peak_candidates else None,
        'bits_per_param': round(bpp, 4) if bpp is not None else None,
        'perplexity': state.get('perplexity', {}).get('perplexity'),
        'gsm8k_accuracy': state.get('gsm8k', {}).get('accuracy'),
        'arc_accuracy': state.get('arc_challenge', {}).get('accuracy'),
    }
    save_json(summary_row, RESULTS_DIR / 'summary.json')
    pd.DataFrame([summary_row]).to_csv(RESULTS_DIR / 'summary.csv', index=False)
    return summary_row


def _is_gptq_checkpoint(model_path: str | Path) -> bool:
    cfg_path = Path(model_path) / 'config.json'
    if not cfg_path.exists():
        return False
    cfg_json = json.loads(cfg_path.read_text())
    return cfg_json.get('quantization_config', {}).get('quant_method') == 'gptq'


def load_quantized_model_and_tokenizer(model_path: str | Path):
    model_path = Path(model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'left'

    if not _is_gptq_checkpoint(model_path):
        raise ValueError(f'{model_path} is not a GPTQ checkpoint.')

    model_basename = find_gptq_model_basename(model_path)
    if model_basename is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {model_path}')

    model = GPTQModel.load(
        str(model_path),
        device_map='auto',
        trust_remote_code=True,
        model_basename=model_basename,
    )
    model.eval()
    return model, tokenizer


def get_model_device(model):
    if hasattr(model, 'device'):
        return model.device
    if hasattr(model, 'hf_device_map') and model.hf_device_map:
        first_device = next(iter(model.hf_device_map.values()))
        return torch.device(first_device)
    return torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


def generate_text(model, tokenizer, prompt: str, *, max_new_tokens: int):
    device = get_model_device(model)
    encoded = tokenizer(
        prompt,
        return_tensors='pt',
        truncation=True,
        max_length=min(getattr(tokenizer, 'model_max_length', 4096), 4096),
        padding=False,
    )
    input_ids = encoded['input_ids'].to(device)
    attention_mask = encoded['attention_mask'].to(device)

    with torch.inference_mode():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )
    gen_ids = outputs[0][input_ids.shape[-1]:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True)


ANSWER_RE = re.compile(r'####\s*(-?[\d,]+\.?\d*)')


def extract_numeric_answer(text: str):
    m = ANSWER_RE.search(text)
    if m:
        try:
            return float(m.group(1).replace(',', ''))
        except ValueError:
            return None
    nums = re.findall(r'-?[\d,]+\.?\d*', text)
    if not nums:
        return None
    try:
        return float(nums[-1].replace(',', ''))
    except ValueError:
        return None


def format_seconds(sec: float) -> str:
    sec = int(max(sec, 0))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    if h > 0:
        return f'{h:d}:{m:02d}:{s:02d}'
    return f'{m:d}:{s:02d}'


def log_progress(prefix: str, idx: int, total: int, start_time: float, correct: int):
    elapsed = time.time() - start_time
    avg = elapsed / max(idx, 1)
    eta = avg * max(total - idx, 0)
    logger.info(
        '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item',
        prefix,
        idx,
        total,
        correct / max(idx, 1),
        format_seconds(elapsed),
        format_seconds(eta),
        avg,
    )

Working directory: /content
Artifact dir: /content/artifacts/gptq_w4_g128/mlp_only_quant
Results dir: /content/results/gptq_w4_g128_mlp_only_quant/mlp_only_quant
Bundle dir: /content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant
CUDA available: True
GPU: NVIDIA L4

In [ ]:
import json
import logging
import math
import os
import re
import time
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd
import torch
from datasets import load_dataset
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from gptqmodel import GPTQModel, QuantizeConfig

# ------------------------------
# Logging
# ------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    force=True,
)
logger = logging.getLogger('gptq_mlp_only_quant')

PROJECT_ROOT = Path.cwd().resolve()
VARIANT = 'mlp_only_quant'
RUN_NAME = 'gptq_w4_g128_mlp_only_quant'
BASE_MODEL = 'Qwen/Qwen2-1.5B'

cfg = {
    'base_model': BASE_MODEL,
    'calibration': {
        'dataset': 'wikitext',
        'dataset_name': 'wikitext-2-raw-v1',
        'split': 'train',
        'num_samples': 512,
        'max_length': 2048,
        'seed': 42,
    },
    'quant': {
        'bits': 4,
        'group_size': 128,
        'desc_act': False,
    },
    'eval': {
        'perplexity': {
            'dataset': 'wikitext',
            'dataset_name': 'wikitext-2-raw-v1',
            'split': 'test',
            'max_length': 2048,
            'stride': 1024,
            'max_eval_tokens': 131072,
            'log_every': 25,
        },
        'gsm8k': {
            'num_fewshot': 8,
            'num_samples': 300,
            'max_new_tokens': 256,
            'log_every': 25,
        },
        'arc_challenge': {
            'num_samples': 500,
            'max_new_tokens': 5,
            'log_every': 50,
        },
    },
    'paths': {
        'artifacts_dir': str(PROJECT_ROOT / 'artifacts'),
        'results_dir': str(PROJECT_ROOT / 'results' / RUN_NAME),
        'calibration_dir': str(PROJECT_ROOT / 'calibration_data'),
        'bundles_dir': str(PROJECT_ROOT / 'zip_bundles' / RUN_NAME),
    },
}

PATHS = {k: Path(v) for k, v in cfg['paths'].items()}
for p in PATHS.values():
    p.mkdir(parents=True, exist_ok=True)

ARTIFACT_DIR = PATHS['artifacts_dir'] / 'gptq_w4_g128' / VARIANT
RESULTS_DIR = PATHS['results_dir'] / VARIANT
BUNDLE_DIR = PATHS['bundles_dir'] / VARIANT
CALIB_DIR = PATHS['calibration_dir']
for p in [ARTIFACT_DIR, RESULTS_DIR, BUNDLE_DIR, CALIB_DIR]:
    p.mkdir(parents=True, exist_ok=True)


def build_dynamic_config(variant: str) -> dict | None:
    if variant == 'full_quant':
        return None
    if variant == 'attn_only_quant':
        return {r'-:.*mlp\.(gate|up|down)_proj.*': {}}
    if variant == 'mlp_only_quant':
        return {r'-:.*self_attn\.(q|k|v|o)_proj.*': {}}
    raise ValueError(f'Unknown variant: {variant}')


print('Working directory:', PROJECT_ROOT)
print('Artifact dir:', ARTIFACT_DIR)
print('Results dir:', RESULTS_DIR)
print('Bundle dir:', BUNDLE_DIR)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))


# ------------------------------
# Small utilities
# ------------------------------
def save_json(obj: Any, path: str | Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump(obj, f, indent=2)
    return path


def read_json(path: str | Path, default=None):
    path = Path(path)
    if not path.exists():
        return default
    with open(path) as f:
        return json.load(f)


def zip_directory(source_dir: str | Path, zip_path: str | Path, *, exclude_suffixes=('.lock',), exclude_dirs=('.ipynb_checkpoints',)):
    source_dir = Path(source_dir).resolve()
    zip_path = Path(zip_path).resolve()
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    tmp_zip = zip_path.with_suffix(zip_path.suffix + '.tmp')
    if tmp_zip.exists():
        tmp_zip.unlink()
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(tmp_zip, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        for path in sorted(source_dir.rglob('*')):
            if path.is_dir():
                continue
            if any(part in exclude_dirs for part in path.parts):
                continue
            if path.resolve() in {zip_path, tmp_zip}:
                continue
            if path.suffix in exclude_suffixes:
                continue
            zf.write(path, arcname=str(path.relative_to(source_dir)))

    tmp_zip.replace(zip_path)
    size_mb = zip_path.stat().st_size / (1024 ** 2)
    logger.info('Created zip: %s (%.2f MB)', zip_path, size_mb)
    return zip_path


def find_gptq_model_basename(model_dir: str | Path) -> str | None:
    model_dir = Path(model_dir)
    candidates = sorted(model_dir.glob('*.safetensors'))
    if not candidates:
        return None
    preferred = [p for p in candidates if 'gptq' in p.name.lower()]
    return (preferred[0] if preferred else candidates[0]).name


def estimate_num_params_from_config(model_dir: str | Path) -> int | None:
    cfg_path = Path(model_dir) / 'config.json'
    if not cfg_path.exists():
        return None
    cfg_json = json.loads(cfg_path.read_text())
    hidden_size = cfg_json.get('hidden_size')
    num_hidden_layers = cfg_json.get('num_hidden_layers')
    intermediate_size = cfg_json.get('intermediate_size')
    vocab_size = cfg_json.get('vocab_size')
    if not all(v is not None for v in [hidden_size, num_hidden_layers, intermediate_size, vocab_size]):
        return None
    rough_params = (
        vocab_size * hidden_size +
        num_hidden_layers * (4 * hidden_size * hidden_size) +
        num_hidden_layers * (3 * hidden_size * intermediate_size)
    )
    return int(rough_params)


def model_size_gb(model_dir: str | Path) -> float:
    files = list(Path(model_dir).glob('*.safetensors'))
    total_bytes = sum(p.stat().st_size for p in files)
    return total_bytes / (1024 ** 3)


def bits_per_param(model_dir: str | Path) -> float | None:
    files = list(Path(model_dir).glob('*.safetensors'))
    if not files:
        return None
    total_bytes = sum(p.stat().st_size for p in files)
    n_params = estimate_num_params_from_config(model_dir)
    if not n_params:
        return None
    return 8.0 * total_bytes / n_params


def get_results_state() -> dict:
    state = read_json(RESULTS_DIR / 'state.json', default={})
    return state or {}


def save_results_state(state: dict):
    save_json(state, RESULTS_DIR / 'state.json')
    return state


def update_summary_table(state: dict):
    size_gb = model_size_gb(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    bpp = bits_per_param(ARTIFACT_DIR) if ARTIFACT_DIR.exists() else None
    peak_candidates = []
    for key in ['perplexity', 'gsm8k', 'arc_challenge']:
        if key in state and isinstance(state[key], dict):
            val = state[key].get('peak_vram_gb')
            if val is not None:
                peak_candidates.append(val)

    summary_row = {
        'variant': VARIANT,
        'compression': f"GPTQ W{cfg['quant']['bits']} g{cfg['quant']['group_size']}",
        'model_size_gb': round(size_gb, 4) if size_gb is not None else None,
        'peak_vram_gb': round(max(peak_candidates), 4) if peak_candidates else None,
        'bits_per_param': round(bpp, 4) if bpp is not None else None,
        'perplexity': state.get('perplexity', {}).get('perplexity'),
        'gsm8k_accuracy': state.get('gsm8k', {}).get('accuracy'),
        'arc_accuracy': state.get('arc_challenge', {}).get('accuracy'),
    }
    save_json(summary_row, RESULTS_DIR / 'summary.json')
    pd.DataFrame([summary_row]).to_csv(RESULTS_DIR / 'summary.csv', index=False)
    return summary_row


def _is_gptq_checkpoint(model_path: str | Path) -> bool:
    cfg_path = Path(model_path) / 'config.json'
    if not cfg_path.exists():
        return False
    cfg_json = json.loads(cfg_path.read_text())
    return cfg_json.get('quantization_config', {}).get('quant_method') == 'gptq'


def load_quantized_model_and_tokenizer(model_path: str | Path):
    model_path = Path(model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = 'left'

    if not _is_gptq_checkpoint(model_path):
        raise ValueError(f'{model_path} is not a GPTQ checkpoint.')

    model_basename = find_gptq_model_basename(model_path)
    if model_basename is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {model_path}')

    model = GPTQModel.load(
        str(model_path),
        device_map='auto',
        trust_remote_code=True,
        model_basename=model_basename,
    )
    model.eval()
    return model, tokenizer


def get_model_device(model):
    if hasattr(model, 'device'):
        return model.device
    if hasattr(model, 'hf_device_map') and model.hf_device_map:
        first_device = next(iter(model.hf_device_map.values()))
        return torch.device(first_device)
    return torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')


def generate_text(model, tokenizer, prompt: str, *, max_new_tokens: int):
    device = get_model_device(model)
    encoded = tokenizer(
        prompt,
        return_tensors='pt',
        truncation=True,
        max_length=min(getattr(tokenizer, 'model_max_length', 4096), 4096),
        padding=False,
    )
    input_ids = encoded['input_ids'].to(device)
    attention_mask = encoded['attention_mask'].to(device)

    with torch.inference_mode():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=True,
        )
    gen_ids = outputs[0][input_ids.shape[-1]:]
    return tokenizer.decode(gen_ids, skip_special_tokens=True)


ANSWER_RE = re.compile(r'####\s*(-?[\d,]+\.?\d*)')


def extract_numeric_answer(text: str):
    m = ANSWER_RE.search(text)
    if m:
        try:
            return float(m.group(1).replace(',', ''))
        except ValueError:
            return None
    nums = re.findall(r'-?[\d,]+\.?\d*', text)
    if not nums:
        return None
    try:
        return float(nums[-1].replace(',', ''))
    except ValueError:
        return None


def format_seconds(sec: float) -> str:
    sec = int(max(sec, 0))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    if h > 0:
        return f'{h:d}:{m:02d}:{s:02d}'
    return f'{m:d}:{s:02d}'


def log_progress(prefix: str, idx: int, total: int, start_time: float, correct: int):
    elapsed = time.time() - start_time
    avg = elapsed / max(idx, 1)
    eta = avg * max(total - idx, 0)
    logger.info(
        '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item',
        prefix,
        idx,
        total,
        correct / max(idx, 1),
        format_seconds(elapsed),
        format_seconds(eta),
        format_seconds(eta),
        avg,
    )


# Quantization helpers

def get_calibration_data(cfg, tokenizer=None):
    cal_cfg = cfg['calibration']
    cache_path = CALIB_DIR / f"calibration_{cal_cfg['num_samples']}_{cal_cfg['max_length']}.pt"
    if cache_path.exists():
        logger.info('Using cached calibration samples: %s', cache_path)
        return torch.load(cache_path, weights_only=False)

    if tokenizer is None:
        tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

    logger.info('Loading calibration dataset: %s / %s / %s', cal_cfg['dataset'], cal_cfg['dataset_name'], cal_cfg['split'])
    ds = load_dataset(cal_cfg['dataset'], cal_cfg['dataset_name'], split=cal_cfg['split'])
    all_text = '\n\n'.join(t for t in ds['text'] if t and t.strip())
    encoded = tokenizer(all_text, return_tensors='pt')
    total_tokens = encoded.input_ids.shape[1]
    max_len = cal_cfg['max_length']

    if total_tokens <= max_len:
        raise ValueError(f'Calibration corpus too short: total_tokens={total_tokens}, max_length={max_len}')

    rng = torch.Generator().manual_seed(cal_cfg['seed'])
    starts = torch.randint(0, total_tokens - max_len, (cal_cfg['num_samples'],), generator=rng)
    samples = []
    for start in tqdm(starts.tolist(), desc='Preparing calibration windows', unit='sample'):
        end = start + max_len
        input_ids = encoded.input_ids[:, start:end]
        samples.append({
            'input_ids': input_ids,
            'attention_mask': torch.ones_like(input_ids),
        })

    torch.save(samples, cache_path)
    logger.info('Saved calibration cache: %s', cache_path)
    return samples


def quantize_variant_gptq(cfg):
    tokenizer = AutoTokenizer.from_pretrained(cfg['base_model'], trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quantized_already = (ARTIFACT_DIR / 'config.json').exists() and find_gptq_model_basename(ARTIFACT_DIR) is not None
    if quantized_already:
        logger.info('Quantized artifact already exists at %s', ARTIFACT_DIR)
        zip_path = BUNDLE_DIR / f'{VARIANT}_quantized_model.zip'
        if not zip_path.exists():
            zip_directory(ARTIFACT_DIR, zip_path)
        return {
            'artifact_dir': str(ARTIFACT_DIR),
            'zip_path': str(zip_path),
            'gptq_model_file': find_gptq_model_basename(ARTIFACT_DIR),
            'dynamic_config': build_dynamic_config(VARIANT),
            'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
            'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        }

    samples = get_calibration_data(cfg, tokenizer)
    cal_dataset = [
        {
            'input_ids': s['input_ids'].squeeze(0),
            'attention_mask': s['attention_mask'].squeeze(0),
        }
        for s in samples
    ]

    qcfg_kwargs = {
        'bits': cfg['quant']['bits'],
        'group_size': cfg['quant']['group_size'],
        'desc_act': cfg['quant'].get('desc_act', False),
    }
    dynamic = build_dynamic_config(VARIANT)
    if dynamic is not None:
        qcfg_kwargs['dynamic'] = dynamic

    quantize_config = QuantizeConfig(**qcfg_kwargs)

    logger.info('Starting GPTQ %s for %s', VARIANT, cfg['base_model'])
    t0 = time.time()
    model = GPTQModel.load(cfg['base_model'], quantize_config, trust_remote_code=True)
    model.quantize(cal_dataset)
    model.save(str(ARTIFACT_DIR))
    tokenizer.save_pretrained(str(ARTIFACT_DIR))
    elapsed = time.time() - t0
    logger.info('Quantization finished in %s', format_seconds(elapsed))

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    model_file = find_gptq_model_basename(ARTIFACT_DIR)
    if model_file is None:
        raise FileNotFoundError(f'No GPTQ safetensors found in {ARTIFACT_DIR}')

    manifest = {
        'variant': VARIANT,
        'base_model': cfg['base_model'],
        'quant': cfg['quant'],
        'dynamic_config': dynamic,
        'artifact_dir': str(ARTIFACT_DIR),
        'gptq_model_file': model_file,
        'quantization_elapsed_sec': elapsed,
        'model_size_gb': round(model_size_gb(ARTIFACT_DIR), 4),
        'bits_per_param': round(bits_per_param(ARTIFACT_DIR), 4),
        'created_at_unix': time.time(),
    }
    save_json(manifest, ARTIFACT_DIR / 'artifact_manifest.json')
    save_json(manifest, RESULTS_DIR / 'quantization_manifest.json')

    zip_path = zip_directory(ARTIFACT_DIR, BUNDLE_DIR / f'{VARIANT}_quantized_model.zip')

    state = get_results_state()
    state['quantization'] = manifest | {'zip_path': str(zip_path)}
    save_results_state(state)
    summary = update_summary_table(state)

    print('Quantized artifact ready.')
    print(json.dumps(manifest, indent=2))
    display(pd.DataFrame([summary]))
    return manifest | {'zip_path': str(zip_path)}

Working directory: /content
Artifact dir: /content/artifacts/gptq_w4_g128/mlp_only_quant
Results dir: /content/results/gptq_w4_g128_mlp_only_quant/mlp_only_quant
Bundle dir: /content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant
CUDA available: True
GPU: NVIDIA L4

In [ ]:
# Cell 1 — Quantize the model and save the quantized artifact zip
quant_manifest = quantize_variant_gptq(cfg)

2026-03-10 04:00:28,626 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:28,633 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:28,642 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

2026-03-10 04:00:28,892 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:28,900 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:28,907 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json: 0.00B [00:00, ?B/s]

2026-03-10 04:00:29,161 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-10 04:00:29,395 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:29,628 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-10 04:00:29,630 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-03-10 04:00:29,637 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"
2026-03-10 04:00:29,644 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/vocab.json "HTTP/1.1 200 OK"

vocab.json: 0.00B [00:00, ?B/s]

2026-03-10 04:00:29,907 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/merges.txt "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:29,914 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"
2026-03-10 04:00:29,925 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/merges.txt "HTTP/1.1 200 OK"

merges.txt: 0.00B [00:00, ?B/s]

2026-03-10 04:00:30,184 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:30,191 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"
2026-03-10 04:00:30,200 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer.json "HTTP/1.1 200 OK"

tokenizer.json: 0.00B [00:00, ?B/s]

2026-03-10 04:00:30,476 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-03-10 04:00:30,704 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-03-10 04:00:30,937 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-03-10 04:00:31,996 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"
2026-03-10 04:00:31,998 | INFO    | Loading calibration dataset: wikitext / wikitext-2-raw-v1 / train
2026-03-10 04:00:32,242 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:32,481 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:32,489 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-10 04:00:32,497 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"

README.md: 0.00B [00:00, ?B/s]

2026-03-10 04:00:32,740 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:32,970 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-10 04:00:33,652 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-10 04:00:33,903 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:34,131 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"
2026-03-10 04:00:34,365 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:34,601 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-10 04:00:34,874 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-10 04:00:35,125 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:35,357 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-103-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:35,591 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:35,824 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:36,063 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:36,294 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-03-10 04:00:36,524 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:36,767 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/tree/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:37,091 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:37,328 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/test-00000-of-00001.parquet "HTTP/1.1 302 Found"
2026-03-10 04:00:37,608 | INFO    | HTTP Request: GET https://huggingface.co/api/datasets/Salesforce/wikitext/xet-read-token/b08601e04326c79dfdd32d625aee71d232d685c3 "HTTP/1.1 200 OK"

wikitext-2-raw-v1/test-00000-of-00001.pa(…):   0%|          | 0.00/733k [00:00<?, ?B/s]

2026-03-10 04:00:39,099 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:39,328 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/train-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/train-00000-of-00001.p(…):   0%|          | 0.00/6.36M [00:00<?, ?B/s]

2026-03-10 04:00:40,177 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:40,411 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext-2-raw-v1/validation-00000-of-00001.parquet "HTTP/1.1 302 Found"

wikitext-2-raw-v1/validation-00000-of-00(…):   0%|          | 0.00/657k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4358 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/36718 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3760 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (2517232 > 32768). Running this sequence through the model will result in indexing errors

Preparing calibration windows:   0%|          | 0/512 [00:00<?, ?sample/s]

2026-03-10 04:00:53,539 | INFO    | Saved calibration cache: /content/calibration_data/calibration_512_2048.pt

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/hqdpgrum-rkaakpxx/`

2026-03-10 04:00:53,861 | INFO    | Starting GPTQ mlp_only_quant for Qwen/Qwen2-1.5B
2026-03-10 04:00:54,105 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:54,112 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:54,347 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:54,581 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:00:54,812 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:54,819 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"

WARN  GPTQModel's per-module `dynamic` quantization feature is fully supported in latest vLLM and SGLang but not yet available in hf transformers.

2026-03-10 04:00:55,059 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:55,065 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:55,299 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/revision/main "HTTP/1.1 200 OK"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

2026-03-10 04:00:55,555 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:55,558 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:55,560 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:55,562 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-10 04:00:55,563 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/model.safetensors "HTTP/1.1 302 Found"
2026-03-10 04:00:55,565 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:00:55,566 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-10 04:00:55,568 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-10 04:00:55,575 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:55,579 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/.gitattributes "HTTP/1.1 200 OK"
2026-03-10 04:00:55,583 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/README.md "HTTP/1.1 200 OK"
2026-03-10 04:00:55,585 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/generation_config.json "HTTP/1.1 200 OK"
2026-03-10 04:00:55,588 | INFO    | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/LICENSE "HTTP/1.1 200 OK"
2026-03-10 04:00:55,805 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/xet-read-token/8a16abf2848eda07cc5253dec660bf1ce007ad7a "HTTP/1.1 200 OK"
2026-03-10 04:01:06,387 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:01:06,394 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-10 04:01:06,633 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:01:06,639 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-10 04:01:06,881 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-10 04:01:07,109 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-10 04:01:08,221 | INFO    | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen2-1.5B "HTTP/1.1 200 OK"

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

model: Qwen2ForCausalLM  (P=0 B=0) [- | - | ~0B]
├─ model.model: Qwen2Model  (P=0 B=0) [- | - | ~0B]
│  ├─ model.model.embed_tokens: Embedding  (P=233.37M B=0) [meta | bfloat16 | ~0B (est~445.12MB)]
│  │  │  param: weight  shape=(151936, 1536) dtype=bfloat16 device=meta ~445.12MB
│  ├─ model.model.layers: ModuleList  (P=0 B=0) [- | - | ~0B]
│  │  ├─ model.model.layers.0: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.0.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.0.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.0.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.0.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.0.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.0.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.0.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.0.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.1: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.1.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.1.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.1.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.1.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.1.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.1.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.1.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.1.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.1.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.2: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.2.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.2.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.2.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.2.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.2.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.2.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.2.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.2.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.2.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.3: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.3.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.3.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.3.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.3.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.3.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.3.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.3.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.3.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.3.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.4: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.4.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.4.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.4.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.4.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.4.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.4.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.4.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.4.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.4.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.5: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.5.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.5.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.5.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.5.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.5.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.5.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.5.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.5.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.5.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.6: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.6.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.6.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.6.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.6.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.6.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.6.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.6.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.6.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.6.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  ├─ model.model.layers.7: Qwen2DecoderLayer  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.self_attn: Qwen2Attention  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.self_attn.q_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  │  │  param: bias  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  │  ├─ model.model.layers.7.self_attn.k_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.v_proj: Linear  (P=393.47K B=0) [meta | bfloat16 | ~0B (est~768.50KB)]
│  │  │  │  │  │  param: weight  shape=(256, 1536) dtype=bfloat16 device=meta ~768.00KB
│  │  │  │  │  │  param: bias  shape=(256,) dtype=bfloat16 device=meta ~512B
│  │  │  │  ├─ model.model.layers.7.self_attn.o_proj: Linear  (P=2.36M B=0) [meta | bfloat16 | ~0B (est~4.50MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 1536) dtype=bfloat16 device=meta ~4.50MB
│  │  │  │  └─ model.model.layers.7.self_attn.rotary_fn: Func  (P=0 B=0) [- | - | ~0B]  ↩ shared ref
│  │  │  ├─ model.model.layers.7.mlp: Qwen2MLP  (P=0 B=0) [- | - | ~0B]
│  │  │  │  ├─ model.model.layers.7.mlp.gate_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.up_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(8960, 1536) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  ├─ model.model.layers.7.mlp.down_proj: Linear  (P=13.76M B=0) [meta | bfloat16 | ~0B (est~26.25MB)]
│  │  │  │  │  │  param: weight  shape=(1536, 8960) dtype=bfloat16 device=meta ~26.25MB
│  │  │  │  └─ model.model.layers.7.mlp.act_fn: SiLUActivation  (P=0 B=0) [- | - | ~0B]
│  │  │  ├─ model.model.layers.7.input_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │  │  │  param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB
│  │  │  └─ model.model.layers.7.post_attention_layernorm: Qwen2RMSNorm  (P=1.54K B=0) [meta | bfloat16 | ~0B (est~3.00KB)]
│  │  │        param: weight  shape=(1536,) dtype=bfloat16 device=meta ~3.00KB

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

2026-03-10 04:01:09,117 | INFO    | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen2-1.5B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:01:09,124 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen2-1.5B/8a16abf2848eda07cc5253dec660bf1ce007ad7a/config.json "HTTP/1.1 200 OK"
2026-03-10 04:01:09,267 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[]`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Packing Kernel: selected: `TorchQuantLinear`

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Calibration: Sort in descending order by length

INFO  Calibration: Total padded tokens: 0

INFO  Calibration: Total non-padded tokens: 1048576

INFO  Calibration: Total tokens: 1048576

INFO  Disk subsystem write throughput detected at 268.7 MB/s.

2026-03-10 04:01:10,738 | INFO    | Not a TTY. Pause/resume from keyboard is disabled.

INFO  ModuleLooper: capturing layer inputs from 512 calibration batches

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  Offloading base modules to disk...

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | region     | count | last_s | avg_s | total_s | pct    | source  |

INFO  +------------+-------+--------+-------+---------+--------+---------+

INFO  | Capture inputs | 1     | 2.197  | 2.197 | 2.197   | 84.8%  | cache_inputs:Qwen2DecoderLayer |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  | Turtle reload  | 1     | 0.394  | 0.394 | 0.394   | 15.2%  | auto:Embedding                 |

INFO  +----------------+-------+--------+-------+---------+--------+--------------------------------+

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000020767 | 1048576 | 0.05000 | 1.638 | 4.234    | cuda 1.04G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000032307 | 1048576 | 0.05000 | 1.666 | 4.234    | cuda 1.04G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 0     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000001269 | 1048576 | 0.05000 | 3.453 | 17.307   | cuda 2.36G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward | 2     | 17.307 | 10.770 | 21.541  | 43.8%  | model.layers.0:subset2/2       |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Forward hook      | 1536  | 0.027  | 0.010  | 15.118  | 30.7%  | model.layers.0.mlp.down_proj   |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Process quant     | 6     | 3.462  | 1.134  | 6.802   | 13.8%  | model.layers.0.mlp.down_proj   |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Post-quant replay | 1     | 3.119  | 3.119  | 3.119   | 6.3%   | model.layers.0:subset2/2       |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Capture inputs    | 1     | 2.197  | 2.197  | 2.197   | 4.5%   | cache_inputs:Qwen2DecoderLayer |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Turtle reload     | 1     | 0.394  | 0.394  | 0.394   | 0.8%   | auto:Embedding                 |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  Format: Converting GPTQ v2 to v1

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000068941 | 1048576 | 0.05000 | 0.988 | 3.705    | cuda 4.17G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000098419 | 1048576 | 0.05000 | 1.007 | 3.705    | cuda 4.17G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 1     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010069 | 1048576 | 0.05000 | 3.509 | 17.209   | cuda 5.44G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward | 4     | 17.209 | 10.614 | 42.454  | 40.3%  | model.layers.1:subset2/2       |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Forward hook      | 3072  | 0.028  | 0.010  | 30.922  | 29.4%  | model.layers.1.mlp.down_proj   |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Process quant     | 12    | 3.519  | 1.029  | 12.344  | 11.7%  | model.layers.1.mlp.down_proj   |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Post-quant replay | 2     | 2.749  | 2.934  | 5.867   | 5.6%   | model.layers.1:subset2/2       |

INFO  +-------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Submodule finalize | 6     | 1.926  | 0.958  | 5.747   | 5.5%   | model.layers.0.mlp.up_proj     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Finalize create    | 3     | 1.315  | 0.877  | 2.632   | 2.5%   | model.layers.0.mlp.gate_proj   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 2.1%   | cache_inputs:Qwen2DecoderLayer |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------+

INFO  | Finalize pack      | 3     | 0.564  | 0.721  | 2.163   | 2.1%   | model.layers.0.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 3     | 0.028  | 0.209  | 0.627   | 0.6%   | model.layers.0.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.394  | 0.394  | 0.394   | 0.4%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000156482 | 1048576 | 0.05000 | 0.992 | 3.320    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000113838 | 1048576 | 0.05000 | 1.027 | 3.320    | cuda 6.85G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 2     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000004879 | 1048576 | 0.05000 | 3.429 | 17.400   | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 6     | 17.400 | 10.529 | 63.174  | 40.7%  | model.layers.2:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 4608  | 0.027  | 0.010  | 46.948  | 30.3%  | model.layers.2.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 18    | 3.439  | 0.991  | 17.835  | 11.5%  | model.layers.2.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 3     | 2.768  | 2.878  | 8.635   | 5.6%   | model.layers.2:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 12    | 0.897  | 0.700  | 8.403   | 5.4%   | model.layers.1.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 6     | 0.545  | 0.549  | 3.294   | 2.1%   | model.layers.1.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 6     | 0.308  | 0.542  | 3.251   | 2.1%   | model.layers.1.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 1.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 6     | 0.019  | 0.158  | 0.949   | 0.6%   | model.layers.1.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.394  | 0.394  | 0.394   | 0.3%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000201522 | 1048576 | 0.05000 | 0.968 | 3.332    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000145031 | 1048576 | 0.05000 | 0.994 | 3.332    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 3     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007805 | 1048576 | 0.05000 | 3.444 | 17.559   | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 8     | 17.559 | 10.508 | 84.065  | 41.1%  | model.layers.3:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 6144  | 0.028  | 0.010  | 63.151  | 30.9%  | model.layers.3.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 24    | 3.453  | 0.970  | 23.280  | 11.4%  | model.layers.3.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 4     | 2.762  | 2.849  | 11.397  | 5.6%   | model.layers.3:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 18    | 0.895  | 0.584  | 10.510  | 5.1%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 9     | 0.550  | 0.494  | 4.444   | 2.2%   | model.layers.2.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 9     | 0.311  | 0.431  | 3.876   | 1.9%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 1.1%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 9     | 0.019  | 0.110  | 0.991   | 0.5%   | model.layers.2.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.394  | 0.394  | 0.394   | 0.2%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000174040 | 1048576 | 0.05000 | 0.995 | 3.300    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000256827 | 1048576 | 0.05000 | 1.019 | 3.300    | cuda 7.15G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 4     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008540 | 1048576 | 0.05000 | 3.427 | 17.394   | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 10    | 17.394 | 10.476 | 104.759 | 41.3%  | model.layers.4:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 7680  | 0.027  | 0.010  | 79.179  | 31.2%  | model.layers.4.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 30    | 3.437  | 0.959  | 28.759  | 11.3%  | model.layers.4.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 5     | 2.746  | 2.829  | 14.143  | 5.6%   | model.layers.4:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 24    | 0.903  | 0.538  | 12.918  | 5.1%   | model.layers.3.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 12    | 0.564  | 0.467  | 5.609   | 2.2%   | model.layers.3.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 12    | 0.308  | 0.375  | 4.495   | 1.8%   | model.layers.3.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.9%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 12    | 0.007  | 0.108  | 1.293   | 0.5%   | model.layers.3.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.394  | 0.394  | 0.394   | 0.2%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000321277 | 1048576 | 0.05000 | 1.006 | 3.291    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000199865 | 1048576 | 0.05000 | 1.027 | 3.291    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 5     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000009633 | 1048576 | 0.05000 | 3.434 | 17.503   | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 12    | 17.503 | 10.463 | 125.552 | 41.5%  | model.layers.5:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 9216  | 0.027  | 0.010  | 95.267  | 31.5%  | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 36    | 3.444  | 0.952  | 34.264  | 11.3%  | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 6     | 2.753  | 2.816  | 16.896  | 5.6%   | model.layers.5:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 30    | 0.885  | 0.500  | 15.008  | 5.0%   | model.layers.4.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 15    | 0.545  | 0.450  | 6.749   | 2.2%   | model.layers.4.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 15    | 0.314  | 0.341  | 5.117   | 1.7%   | model.layers.4.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.7%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 15    | 0.015  | 0.089  | 1.331   | 0.4%   | model.layers.4.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 1     | 0.394  | 0.394  | 0.394   | 0.1%   | auto:Embedding                                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000315654 | 1048576 | 0.05000 | 1.081 | 3.324    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000209702 | 1048576 | 0.05000 | 1.110 | 3.324    | cuda 7.45G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 6     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010831 | 1048576 | 0.05000 | 3.470 | 17.501   | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 14    | 17.501 | 10.455 | 146.377 | 41.2%  | model.layers.6:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 10752 | 0.028  | 0.010  | 111.428 | 31.4%  | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 42    | 3.480  | 0.952  | 39.965  | 11.2%  | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 7     | 2.764  | 2.809  | 19.660  | 5.5%   | model.layers.6:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 36    | 1.175  | 0.514  | 18.506  | 5.2%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 18    | 0.624  | 0.456  | 8.210   | 2.3%   | model.layers.5.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 18    | 0.510  | 0.341  | 6.138   | 1.7%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.6%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 18    | 0.015  | 0.110  | 1.989   | 0.6%   | model.layers.5.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000244665 | 1048576 | 0.05000 | 0.989 | 3.323    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000198750 | 1048576 | 0.05000 | 1.004 | 3.323    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 7     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010944 | 1048576 | 0.05000 | 3.461 | 17.497   | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 16    | 17.497 | 10.450 | 167.197 | 41.3%  | model.layers.7:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 12288 | 0.028  | 0.010  | 127.543 | 31.5%  | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 48    | 3.470  | 0.947  | 45.466  | 11.2%  | model.layers.7.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 8     | 2.755  | 2.802  | 22.415  | 5.5%   | model.layers.7:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 42    | 0.914  | 0.505  | 21.216  | 5.2%   | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 21    | 0.561  | 0.446  | 9.361   | 2.3%   | model.layers.6.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 21    | 0.312  | 0.322  | 6.763   | 1.7%   | model.layers.6.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 21    | 0.016  | 0.111  | 2.327   | 0.6%   | model.layers.6.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.5%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000185266 | 1048576 | 0.05000 | 0.972 | 3.315    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000247368 | 1048576 | 0.05000 | 0.994 | 3.315    | cuda 7.75G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 8     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000010358 | 1048576 | 0.05000 | 3.524 | 17.435   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 18    | 17.435 | 10.442 | 187.947 | 41.3%  | model.layers.8:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 13824 | 0.028  | 0.010  | 143.566 | 31.5%  | model.layers.8.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 54    | 3.533  | 0.944  | 50.996  | 11.2%  | model.layers.8.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 9     | 2.766  | 2.798  | 25.181  | 5.5%   | model.layers.8:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 48    | 0.914  | 0.498  | 23.927  | 5.3%   | model.layers.7.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 24    | 0.583  | 0.439  | 10.541  | 2.3%   | model.layers.7.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 24    | 0.290  | 0.306  | 7.346   | 1.6%   | model.layers.7.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 24    | 0.016  | 0.123  | 2.947   | 0.6%   | model.layers.7.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.5%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000207762 | 1048576 | 0.05000 | 0.984 | 3.319    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000179515 | 1048576 | 0.05000 | 0.994 | 3.319    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 9     | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008618 | 1048576 | 0.05000 | 3.491 | 17.467   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 20    | 17.467 | 10.437 | 208.733 | 41.3%  | model.layers.9:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 15360 | 0.028  | 0.010  | 159.614 | 31.6%  | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 60    | 3.501  | 0.942  | 56.515  | 11.2%  | model.layers.9.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 10    | 2.756  | 2.794  | 27.937  | 5.5%   | model.layers.9:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 54    | 0.855  | 0.490  | 26.459  | 5.2%   | model.layers.8.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 27    | 0.514  | 0.430  | 11.608  | 2.3%   | model.layers.8.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 27    | 0.300  | 0.294  | 7.950   | 1.6%   | model.layers.8.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 27    | 0.016  | 0.130  | 3.497   | 0.7%   | model.layers.8.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.2%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000166211 | 1048576 | 0.05000 | 0.982 | 3.313    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000188940 | 1048576 | 0.05000 | 1.009 | 3.313    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 10    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007817 | 1048576 | 0.05000 | 3.460 | 17.412   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 22    | 17.412 | 10.430 | 229.459 | 41.3%  | model.layers.10:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 16896 | 0.028  | 0.010  | 175.628 | 31.6%  | model.layers.10.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 66    | 3.470  | 0.939  | 62.005  | 11.2%  | model.layers.10.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 11    | 2.760  | 2.791  | 30.697  | 5.5%   | model.layers.10:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 60    | 0.889  | 0.485  | 29.100  | 5.2%   | model.layers.9.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 30    | 0.546  | 0.425  | 12.740  | 2.3%   | model.layers.9.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 30    | 0.304  | 0.285  | 8.560   | 1.5%   | model.layers.9.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 30    | 0.016  | 0.127  | 3.812   | 0.7%   | model.layers.9.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.1%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000157839 | 1048576 | 0.05000 | 1.022 | 3.310    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000180244 | 1048576 | 0.05000 | 1.023 | 3.310    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 11    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007306 | 1048576 | 0.05000 | 3.494 | 17.455   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 24    | 17.455 | 10.426 | 250.224 | 41.4%  | model.layers.11:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 18432 | 0.027  | 0.010  | 191.722 | 31.7%  | model.layers.11.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 72    | 3.504  | 0.939  | 67.594  | 11.2%  | model.layers.11.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 12    | 2.751  | 2.787  | 33.449  | 5.5%   | model.layers.11:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 66    | 0.881  | 0.476  | 31.442  | 5.2%   | model.layers.10.mlp.up_proj                      |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 33    | 0.551  | 0.420  | 13.868  | 2.3%   | model.layers.10.mlp.up_proj [module.pack_block]  |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize create    | 33    | 0.299  | 0.278  | 9.161   | 1.5%   | model.layers.10.mlp.up_proj                      |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize offload   | 33    | 0.008  | 0.133  | 4.387   | 0.7%   | model.layers.10.mlp.up_proj                      |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.4%   | cache_inputs:Qwen2DecoderLayer                   |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Turtle reload      | 2     | 0.432  | 0.413  | 0.826   | 0.1%   | auto:Qwen2DecoderLayer                           |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000157224 | 1048576 | 0.05000 | 1.146 | 3.334    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000202478 | 1048576 | 0.05000 | 1.169 | 3.334    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 12    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007324 | 1048576 | 0.05000 | 3.464 | 17.482   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 26    | 17.482 | 10.425 | 271.040 | 41.2%  | model.layers.12:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Forward hook       | 19968 | 0.028  | 0.010  | 207.811 | 31.6%  | model.layers.12.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Process quant      | 78    | 3.473  | 0.941  | 73.414  | 11.2%  | model.layers.12.mlp.down_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Post-quant replay  | 13    | 2.758  | 2.785  | 36.207  | 5.5%   | model.layers.12:subset2/2                        |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Submodule finalize | 72    | 1.215  | 0.487  | 35.055  | 5.3%   | model.layers.11.mlp.gate_proj                    |

INFO  +--------------------+-------+--------+--------+---------+--------+--------------------------------------------------+

INFO  | Finalize pack      | 36    | 0.512  | 0.425  | 15.315  | 2.3%   | model.layers.11.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 36    | 0.664  | 0.291  | 10.490  | 1.6%   | model.layers.11.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 36    | 0.017  | 0.130  | 4.676   | 0.7%   | model.layers.11.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000155838 | 1048576 | 0.05000 | 0.979 | 3.305    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000173618 | 1048576 | 0.05000 | 1.001 | 3.305    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 13    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000007007 | 1048576 | 0.05000 | 3.486 | 17.457   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 28    | 17.457 | 10.421 | 291.801 | 41.3%  | model.layers.13:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 21504 | 0.028  | 0.010  | 223.848 | 31.7%  | model.layers.13.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 84    | 3.496  | 0.939  | 78.918  | 11.2%  | model.layers.13.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 14    | 2.757  | 2.783  | 38.964  | 5.5%   | model.layers.13:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 78    | 0.887  | 0.483  | 37.681  | 5.3%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 39    | 0.531  | 0.421  | 16.436  | 2.3%   | model.layers.12.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 39    | 0.312  | 0.285  | 11.119  | 1.6%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 39    | 0.017  | 0.128  | 4.981   | 0.7%   | model.layers.12.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000178526 | 1048576 | 0.05000 | 1.002 | 3.330    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000180193 | 1048576 | 0.05000 | 1.008 | 3.330    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 14    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008329 | 1048576 | 0.05000 | 3.436 | 17.443   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 30    | 17.443 | 10.419 | 312.574 | 41.3%  | model.layers.14:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 23040 | 0.028  | 0.010  | 239.925 | 31.7%  | model.layers.14.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 90    | 3.445  | 0.938  | 84.413  | 11.2%  | model.layers.14.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 15    | 2.753  | 2.781  | 41.717  | 5.5%   | model.layers.14:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 84    | 0.852  | 0.479  | 40.200  | 5.3%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 42    | 0.499  | 0.417  | 17.516  | 2.3%   | model.layers.13.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 42    | 0.309  | 0.280  | 11.740  | 1.6%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 42    | 0.008  | 0.125  | 5.251   | 0.7%   | model.layers.13.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000177345 | 1048576 | 0.05000 | 0.996 | 3.340    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000195642 | 1048576 | 0.05000 | 1.018 | 3.340    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 15    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000008622 | 1048576 | 0.05000 | 3.500 | 17.479   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 32    | 17.479 | 10.419 | 333.393 | 41.3%  | model.layers.15:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 24576 | 0.028  | 0.010  | 255.972 | 31.7%  | model.layers.15.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 96    | 3.510  | 0.937  | 89.968  | 11.2%  | model.layers.15.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 16    | 2.758  | 2.780  | 44.475  | 5.5%   | model.layers.15:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 90    | 0.868  | 0.475  | 42.776  | 5.3%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 45    | 0.515  | 0.413  | 18.593  | 2.3%   | model.layers.14.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 45    | 0.313  | 0.275  | 12.370  | 1.5%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 45    | 0.016  | 0.124  | 5.569   | 0.7%   | model.layers.14.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000215234 | 1048576 | 0.05000 | 1.011 | 3.312    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000197652 | 1048576 | 0.05000 | 1.040 | 3.312    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 16    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000011316 | 1048576 | 0.05000 | 3.452 | 17.459   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 34    | 17.459 | 10.417 | 354.165 | 41.4%  | model.layers.16:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 26112 | 0.028  | 0.010  | 272.089 | 31.8%  | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 102   | 3.462  | 0.936  | 95.510  | 11.2%  | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 17    | 2.757  | 2.778  | 47.231  | 5.5%   | model.layers.16:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 96    | 0.881  | 0.473  | 45.394  | 5.3%   | model.layers.15.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 48    | 0.533  | 0.411  | 19.711  | 2.3%   | model.layers.15.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 48    | 0.306  | 0.270  | 12.983  | 1.5%   | model.layers.15.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 48    | 0.024  | 0.117  | 5.627   | 0.7%   | model.layers.15.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.3%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000231447 | 1048576 | 0.05000 | 1.044 | 3.324    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000255859 | 1048576 | 0.05000 | 1.074 | 3.324    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 17    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000016251 | 1048576 | 0.05000 | 3.445 | 17.483   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 36    | 17.483 | 10.416 | 374.971 | 41.4%  | model.layers.17:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 27648 | 0.029  | 0.010  | 288.213 | 31.8%  | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 108   | 3.454  | 0.936  | 101.113 | 11.2%  | model.layers.17.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 18    | 2.764  | 2.778  | 49.995  | 5.5%   | model.layers.17:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 102   | 0.896  | 0.471  | 48.052  | 5.3%   | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 51    | 0.570  | 0.409  | 20.843  | 2.3%   | model.layers.16.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 51    | 0.287  | 0.266  | 13.561  | 1.5%   | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 51    | 0.007  | 0.117  | 5.960   | 0.7%   | model.layers.16.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 3     | 0.460  | 0.429  | 1.286   | 0.1%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000290188 | 1048576 | 0.05000 | 1.062 | 3.357    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000247119 | 1048576 | 0.05000 | 1.090 | 3.357    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 18    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000018735 | 1048576 | 0.05000 | 3.464 | 17.529   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 38    | 17.529 | 10.417 | 395.858 | 41.3%  | model.layers.18:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 29184 | 0.029  | 0.010  | 304.397 | 31.7%  | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 114   | 3.472  | 0.937  | 106.767 | 11.1%  | model.layers.18.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 19    | 2.751  | 2.776  | 52.746  | 5.5%   | model.layers.18:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 108   | 1.244  | 0.479  | 51.752  | 5.4%   | model.layers.17.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 54    | 0.557  | 0.414  | 22.338  | 2.3%   | model.layers.17.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 54    | 0.649  | 0.275  | 14.861  | 1.5%   | model.layers.17.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 54    | 0.008  | 0.116  | 6.266   | 0.7%   | model.layers.17.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000323326 | 1048576 | 0.05000 | 1.082 | 3.299    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000276292 | 1048576 | 0.05000 | 1.109 | 3.299    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 19    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000023650 | 1048576 | 0.05000 | 3.445 | 17.520   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 40    | 17.520 | 10.417 | 416.677 | 41.3%  | model.layers.19:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 30720 | 0.029  | 0.010  | 320.560 | 31.8%  | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 120   | 3.454  | 0.937  | 112.442 | 11.1%  | model.layers.19.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 20    | 2.756  | 2.775  | 55.502  | 5.5%   | model.layers.19:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 114   | 0.892  | 0.477  | 54.396  | 5.4%   | model.layers.18.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 57    | 0.535  | 0.412  | 23.458  | 2.3%   | model.layers.18.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 57    | 0.316  | 0.272  | 15.495  | 1.5%   | model.layers.18.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 57    | 0.028  | 0.120  | 6.862   | 0.7%   | model.layers.18.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000428491 | 1048576 | 0.05000 | 1.079 | 3.335    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000360028 | 1048576 | 0.05000 | 1.109 | 3.335    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 20    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000041681 | 1048576 | 0.05000 | 3.492 | 17.505   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 42    | 17.505 | 10.417 | 437.517 | 41.3%  | model.layers.20:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 32256 | 0.028  | 0.010  | 336.658 | 31.8%  | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 126   | 3.503  | 0.938  | 118.163 | 11.2%  | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 21    | 2.762  | 2.774  | 58.264  | 5.5%   | model.layers.20:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 120   | 0.933  | 0.476  | 57.162  | 5.4%   | model.layers.19.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 60    | 0.557  | 0.410  | 24.623  | 2.3%   | model.layers.19.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 60    | 0.333  | 0.269  | 16.166  | 1.5%   | model.layers.19.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 60    | 0.016  | 0.120  | 7.196   | 0.7%   | model.layers.19.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000544989 | 1048576 | 0.05000 | 1.019 | 3.309    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000441446 | 1048576 | 0.05000 | 1.044 | 3.309    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 21    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000057920 | 1048576 | 0.05000 | 3.466 | 17.556   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 44    | 17.556 | 10.418 | 458.381 | 41.3%  | model.layers.21:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 33792 | 0.029  | 0.010  | 352.841 | 31.8%  | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 132   | 3.475  | 0.937  | 123.730 | 11.2%  | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 22    | 2.763  | 2.774  | 61.028  | 5.5%   | model.layers.21:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 126   | 0.893  | 0.470  | 59.244  | 5.3%   | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 63    | 0.575  | 0.409  | 25.765  | 2.3%   | model.layers.20.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 63    | 0.286  | 0.266  | 16.736  | 1.5%   | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 63    | 0.018  | 0.115  | 7.240   | 0.7%   | model.layers.20.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000632706 | 1048576 | 0.05000 | 1.050 | 3.327    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000515119 | 1048576 | 0.05000 | 1.070 | 3.327    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 22    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000065176 | 1048576 | 0.05000 | 3.460 | 17.553   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 46    | 17.553 | 10.419 | 479.262 | 41.4%  | model.layers.22:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 35328 | 0.028  | 0.010  | 368.970 | 31.9%  | model.layers.22.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 138   | 3.469  | 0.937  | 129.350 | 11.2%  | model.layers.22.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 23    | 2.760  | 2.773  | 63.788  | 5.5%   | model.layers.22:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 132   | 0.896  | 0.465  | 61.320  | 5.3%   | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 66    | 0.585  | 0.408  | 26.906  | 2.3%   | model.layers.21.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 66    | 0.279  | 0.262  | 17.296  | 1.5%   | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 66    | 0.008  | 0.115  | 7.579   | 0.7%   | model.layers.21.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.1%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000608976 | 1048576 | 0.05000 | 1.070 | 3.326    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000528122 | 1048576 | 0.05000 | 1.094 | 3.326    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 23    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000068912 | 1048576 | 0.05000 | 3.432 | 17.552   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 48    | 17.552 | 10.420 | 500.140 | 41.4%  | model.layers.23:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 36864 | 0.027  | 0.010  | 385.141 | 31.9%  | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 144   | 3.440  | 0.937  | 134.982 | 11.2%  | model.layers.23.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 24    | 2.762  | 2.773  | 66.550  | 5.5%   | model.layers.23:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 138   | 0.854  | 0.463  | 63.852  | 5.3%   | model.layers.22.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 69    | 0.497  | 0.405  | 27.955  | 2.3%   | model.layers.22.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 69    | 0.315  | 0.260  | 17.928  | 1.5%   | model.layers.22.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 69    | 0.016  | 0.118  | 8.112   | 0.7%   | model.layers.22.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 4     | 0.446  | 0.433  | 1.732   | 0.1%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000636415 | 1048576 | 0.05000 | 1.064 | 3.325    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000674604 | 1048576 | 0.05000 | 1.082 | 3.325    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 24    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000098639 | 1048576 | 0.05000 | 3.450 | 17.557   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 50    | 17.557 | 10.420 | 521.022 | 41.3%  | model.layers.24:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 38400 | 0.028  | 0.010  | 401.343 | 31.8%  | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 150   | 3.459  | 0.937  | 140.618 | 11.2%  | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 25    | 2.765  | 2.773  | 69.315  | 5.5%   | model.layers.24:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 144   | 1.153  | 0.467  | 67.277  | 5.3%   | model.layers.23.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 72    | 0.597  | 0.408  | 29.405  | 2.3%   | model.layers.23.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 72    | 0.511  | 0.263  | 18.953  | 1.5%   | model.layers.23.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 72    | 0.018  | 0.122  | 8.750   | 0.7%   | model.layers.23.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000670810 | 1048576 | 0.05000 | 1.017 | 3.329    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000674571 | 1048576 | 0.05000 | 1.042 | 3.329    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 25    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000139742 | 1048576 | 0.05000 | 3.439 | 17.536   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 52    | 17.536 | 10.421 | 541.887 | 41.4%  | model.layers.25:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 39936 | 0.028  | 0.010  | 417.498 | 31.9%  | model.layers.25.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 156   | 3.449  | 0.937  | 146.155 | 11.2%  | model.layers.25.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 26    | 2.771  | 2.773  | 72.085  | 5.5%   | model.layers.25:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 150   | 0.891  | 0.462  | 69.343  | 5.3%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 75    | 0.584  | 0.407  | 30.545  | 2.3%   | model.layers.24.mlp.down_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 75    | 0.275  | 0.260  | 19.500  | 1.5%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 75    | 0.017  | 0.117  | 8.792   | 0.7%   | model.layers.24.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000647035 | 1048576 | 0.05000 | 1.095 | 3.331    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000681988 | 1048576 | 0.05000 | 1.135 | 3.331    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 26    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000215390 | 1048576 | 0.05000 | 3.405 | 17.551   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 54    | 17.551 | 10.422 | 562.769 | 41.4%  | model.layers.26:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 41472 | 0.027  | 0.010  | 433.674 | 31.9%  | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 162   | 3.414  | 0.937  | 151.831 | 11.2%  | model.layers.26.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.769  | 2.772  | 74.854  | 5.5%   | model.layers.26:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 156   | 0.887  | 0.461  | 71.961  | 5.3%   | model.layers.25.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 78    | 0.551  | 0.406  | 31.671  | 2.3%   | model.layers.25.mlp.gate_proj [module.pack_block] |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 78    | 0.291  | 0.257  | 20.085  | 1.5%   | model.layers.25.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 78    | 0.009  | 0.117  | 9.100   | 0.7%   | model.layers.25.mlp.gate_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | process | layer | module                    | feat: in, out | dtype: size  | loss         | samples | damp    | time  | fwd_time | (v)ram       | dynamic |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.up_proj               | 1536, 8960    | bf16: 27.1MB | 0.0000840956 | 1048576 | 0.05000 | 1.022 | 3.327    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.gate_proj             | 1536, 8960    | bf16: 27.1MB | 0.0000893053 | 1048576 | 0.05000 | 1.047 | 3.327    | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | gptq    | 27    | mlp.down_proj             | 8960, 1536    | bf16: 27.1MB | 0.0000418691 | 1048576 | 0.05000 | 3.433 | 17.535   | cuda 8.05G   |         |

INFO  +---------+-------+---------------------------+---------------+--------------+--------------+---------+---------+-------+----------+--------------+---------+

INFO  | Pre-quant forward  | 56    | 17.535 | 10.422 | 583.631 | 41.5%  | model.layers.27:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 43008 | 0.027  | 0.010  | 449.879 | 32.0%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 168   | 3.442  | 0.937  | 157.370 | 11.2%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.769  | 2.772  | 74.854  | 5.3%   | model.layers.26:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 162   | 0.918  | 0.461  | 74.685  | 5.3%   | model.layers.26.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 81    | 0.613  | 0.406  | 32.877  | 2.3%   | model.layers.26.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 81    | 0.262  | 0.254  | 20.611  | 1.5%   | model.layers.26.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 81    | 0.016  | 0.120  | 9.754   | 0.7%   | model.layers.26.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000020767', 'samples': '1048576', 'damp': '0.05000', 'time': '1.638', 'fwd_time': '4.234', '(v)ram': 'cuda 1.04G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000032307', 'samples': '1048576', 'damp': '0.05000', 'time': '1.666', 'fwd_time': '4.234', '(v)ram': 'cuda 1.04G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 0, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000001269', 'samples': '1048576', 'damp': '0.05000', 'time': '3.453', 'fwd_time': '17.307', '(v)ram': 'cuda 2.36G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000068941', 'samples': '1048576', 'damp': '0.05000', 'time': '0.988', 'fwd_time': '3.705', '(v)ram': 'cuda 4.17G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000098419', 'samples': '1048576', 'damp': '0.05000', 'time': '1.007', 'fwd_time': '3.705', '(v)ram': 'cuda 4.17G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 1, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010069', 'samples': '1048576', 'damp': '0.05000', 'time': '3.509', 'fwd_time': '17.209', '(v)ram': 'cuda 5.44G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000156482', 'samples': '1048576', 'damp': '0.05000', 'time': '0.992', 'fwd_time': '3.320', '(v)ram': 'cuda 6.85G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000113838', 'samples': '1048576', 'damp': '0.05000', 'time': '1.027', 'fwd_time': '3.320', '(v)ram': 'cuda 6.85G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 2, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000004879', 'samples': '1048576', 'damp': '0.05000', 'time': '3.429', 'fwd_time': '17.400', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000201522', 'samples': '1048576', 'damp': '0.05000', 'time': '0.968', 'fwd_time': '3.332', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000145031', 'samples': '1048576', 'damp': '0.05000', 'time': '0.994', 'fwd_time': '3.332', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 3, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007805', 'samples': '1048576', 'damp': '0.05000', 'time': '3.444', 'fwd_time': '17.559', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000174040', 'samples': '1048576', 'damp': '0.05000', 'time': '0.995', 'fwd_time': '3.300', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000256827', 'samples': '1048576', 'damp': '0.05000', 'time': '1.019', 'fwd_time': '3.300', '(v)ram': 'cuda 7.15G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 4, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008540', 'samples': '1048576', 'damp': '0.05000', 'time': '3.427', 'fwd_time': '17.394', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000321277', 'samples': '1048576', 'damp': '0.05000', 'time': '1.006', 'fwd_time': '3.291', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000199865', 'samples': '1048576', 'damp': '0.05000', 'time': '1.027', 'fwd_time': '3.291', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 5, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000009633', 'samples': '1048576', 'damp': '0.05000', 'time': '3.434', 'fwd_time': '17.503', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000315654', 'samples': '1048576', 'damp': '0.05000', 'time': '1.081', 'fwd_time': '3.324', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000209702', 'samples': '1048576', 'damp': '0.05000', 'time': '1.110', 'fwd_time': '3.324', '(v)ram': 'cuda 7.45G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 6, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010831', 'samples': '1048576', 'damp': '0.05000', 'time': '3.470', 'fwd_time': '17.501', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000244665', 'samples': '1048576', 'damp': '0.05000', 'time': '0.989', 'fwd_time': '3.323', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000198750', 'samples': '1048576', 'damp': '0.05000', 'time': '1.004', 'fwd_time': '3.323', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 7, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010944', 'samples': '1048576', 'damp': '0.05000', 'time': '3.461', 'fwd_time': '17.497', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000185266', 'samples': '1048576', 'damp': '0.05000', 'time': '0.972', 'fwd_time': '3.315', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000247368', 'samples': '1048576', 'damp': '0.05000', 'time': '0.994', 'fwd_time': '3.315', '(v)ram': 'cuda 7.75G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 8, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000010358', 'samples': '1048576', 'damp': '0.05000', 'time': '3.524', 'fwd_time': '17.435', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000207762', 'samples': '1048576', 'damp': '0.05000', 'time': '0.984', 'fwd_time': '3.319', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000179515', 'samples': '1048576', 'damp': '0.05000', 'time': '0.994', 'fwd_time': '3.319', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 9, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008618', 'samples': '1048576', 'damp': '0.05000', 'time': '3.491', 'fwd_time': '17.467', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000166211', 'samples': '1048576', 'damp': '0.05000', 'time': '0.982', 'fwd_time': '3.313', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000188940', 'samples': '1048576', 'damp': '0.05000', 'time': '1.009', 'fwd_time': '3.313', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 10, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007817', 'samples': '1048576', 'damp': '0.05000', 'time': '3.460', 'fwd_time': '17.412', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000157839', 'samples': '1048576', 'damp': '0.05000', 'time': '1.022', 'fwd_time': '3.310', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000180244', 'samples': '1048576', 'damp': '0.05000', 'time': '1.023', 'fwd_time': '3.310', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 11, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007306', 'samples': '1048576', 'damp': '0.05000', 'time': '3.494', 'fwd_time': '17.455', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000157224', 'samples': '1048576', 'damp': '0.05000', 'time': '1.146', 'fwd_time': '3.334', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000202478', 'samples': '1048576', 'damp': '0.05000', 'time': '1.169', 'fwd_time': '3.334', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 12, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007324', 'samples': '1048576', 'damp': '0.05000', 'time': '3.464', 'fwd_time': '17.482', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000155838', 'samples': '1048576', 'damp': '0.05000', 'time': '0.979', 'fwd_time': '3.305', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000173618', 'samples': '1048576', 'damp': '0.05000', 'time': '1.001', 'fwd_time': '3.305', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 13, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000007007', 'samples': '1048576', 'damp': '0.05000', 'time': '3.486', 'fwd_time': '17.457', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000178526', 'samples': '1048576', 'damp': '0.05000', 'time': '1.002', 'fwd_time': '3.330', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000180193', 'samples': '1048576', 'damp': '0.05000', 'time': '1.008', 'fwd_time': '3.330', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 14, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008329', 'samples': '1048576', 'damp': '0.05000', 'time': '3.436', 'fwd_time': '17.443', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000177345', 'samples': '1048576', 'damp': '0.05000', 'time': '0.996', 'fwd_time': '3.340', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000195642', 'samples': '1048576', 'damp': '0.05000', 'time': '1.018', 'fwd_time': '3.340', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 15, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000008622', 'samples': '1048576', 'damp': '0.05000', 'time': '3.500', 'fwd_time': '17.479', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000215234', 'samples': '1048576', 'damp': '0.05000', 'time': '1.011', 'fwd_time': '3.312', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000197652', 'samples': '1048576', 'damp': '0.05000', 'time': '1.040', 'fwd_time': '3.312', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 16, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000011316', 'samples': '1048576', 'damp': '0.05000', 'time': '3.452', 'fwd_time': '17.459', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000231447', 'samples': '1048576', 'damp': '0.05000', 'time': '1.044', 'fwd_time': '3.324', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000255859', 'samples': '1048576', 'damp': '0.05000', 'time': '1.074', 'fwd_time': '3.324', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 17, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000016251', 'samples': '1048576', 'damp': '0.05000', 'time': '3.445', 'fwd_time': '17.483', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000290188', 'samples': '1048576', 'damp': '0.05000', 'time': '1.062', 'fwd_time': '3.357', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000247119', 'samples': '1048576', 'damp': '0.05000', 'time': '1.090', 'fwd_time': '3.357', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 18, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000018735', 'samples': '1048576', 'damp': '0.05000', 'time': '3.464', 'fwd_time': '17.529', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000323326', 'samples': '1048576', 'damp': '0.05000', 'time': '1.082', 'fwd_time': '3.299', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000276292', 'samples': '1048576', 'damp': '0.05000', 'time': '1.109', 'fwd_time': '3.299', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 19, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000023650', 'samples': '1048576', 'damp': '0.05000', 'time': '3.445', 'fwd_time': '17.520', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000428491', 'samples': '1048576', 'damp': '0.05000', 'time': '1.079', 'fwd_time': '3.335', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000360028', 'samples': '1048576', 'damp': '0.05000', 'time': '1.109', 'fwd_time': '3.335', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 20, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000041681', 'samples': '1048576', 'damp': '0.05000', 'time': '3.492', 'fwd_time': '17.505', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000544989', 'samples': '1048576', 'damp': '0.05000', 'time': '1.019', 'fwd_time': '3.309', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000441446', 'samples': '1048576', 'damp': '0.05000', 'time': '1.044', 'fwd_time': '3.309', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 21, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000057920', 'samples': '1048576', 'damp': '0.05000', 'time': '3.466', 'fwd_time': '17.556', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000632706', 'samples': '1048576', 'damp': '0.05000', 'time': '1.050', 'fwd_time': '3.327', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000515119', 'samples': '1048576', 'damp': '0.05000', 'time': '1.070', 'fwd_time': '3.327', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 22, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000065176', 'samples': '1048576', 'damp': '0.05000', 'time': '3.460', 'fwd_time': '17.553', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000608976', 'samples': '1048576', 'damp': '0.05000', 'time': '1.070', 'fwd_time': '3.326', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000528122', 'samples': '1048576', 'damp': '0.05000', 'time': '1.094', 'fwd_time': '3.326', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 23, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000068912', 'samples': '1048576', 'damp': '0.05000', 'time': '3.432', 'fwd_time': '17.552', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000636415', 'samples': '1048576', 'damp': '0.05000', 'time': '1.064', 'fwd_time': '3.325', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000674604', 'samples': '1048576', 'damp': '0.05000', 'time': '1.082', 'fwd_time': '3.325', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 24, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000098639', 'samples': '1048576', 'damp': '0.05000', 'time': '3.450', 'fwd_time': '17.557', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000670810', 'samples': '1048576', 'damp': '0.05000', 'time': '1.017', 'fwd_time': '3.329', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000674571', 'samples': '1048576', 'damp': '0.05000', 'time': '1.042', 'fwd_time': '3.329', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 25, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000139742', 'samples': '1048576', 'damp': '0.05000', 'time': '3.439', 'fwd_time': '17.536', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000647035', 'samples': '1048576', 'damp': '0.05000', 'time': '1.095', 'fwd_time': '3.331', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000681988', 'samples': '1048576', 'damp': '0.05000', 'time': '1.135', 'fwd_time': '3.331', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 26, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000215390', 'samples': '1048576', 'damp': '0.05000', 'time': '3.405', 'fwd_time': '17.551', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.up_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000840956', 'samples': '1048576', 'damp': '0.05000', 'time': '1.022', 'fwd_time': '3.327', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.gate_proj', 'feat: in, out': '1536, 8960', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000893053', 'samples': '1048576', 'damp': '0.05000', 'time': '1.047', 'fwd_time': '3.327', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  {'process': 'gptq', 'layer': 27, 'module': 'mlp.down_proj', 'feat: in, out': '8960, 1536', 'dtype: size': 'bf16: 27.1MB', 'loss': '0.0000418691', 'samples': '1048576', 'damp': '0.05000', 'time': '3.433', 'fwd_time': '17.535', '(v)ram': 'cuda 8.05G', 'dynamic': None}

INFO  tp-pre-pad summary:
[]

INFO  | Pre-quant forward  | 56    | 17.535 | 10.422 | 583.631 | 41.3%  | model.layers.27:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 43008 | 0.027  | 0.010  | 449.879 | 31.8%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 168   | 3.442  | 0.937  | 157.370 | 11.1%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 168   | 0.873  | 0.460  | 77.274  | 5.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.769  | 2.772  | 74.854  | 5.3%   | model.layers.26:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 84    | 0.546  | 0.404  | 33.965  | 2.4%   | model.layers.27.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 84    | 0.287  | 0.252  | 21.185  | 1.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 84    | 0.017  | 0.120  | 10.092  | 0.7%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process finalize   | 2     | 0.000  | 0.000  | 0.001   | 0.0%   | tp-pre-pad                                        |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

Writing model shards: 0it [00:00, ?it/s]

INFO  Saved Quantize Config:
{
  "bits": 4,
  "dynamic": {
    "-:.*self_attn\\.(q|k|v|o)_proj.*": {}
  },
  "group_size": 128,
  "desc_act": false,
  "lm_head": false,
  "quant_method": "gptq",
  "checkpoint_format": "gptq",
  "pack_dtype": "int32",
  "meta": {
    "quantizer": [
      "gptqmodel:5.7.0"
    ],
    "uri": "https://github.com/modelcloud/gptqmodel",
    "damp_percent": 0.05,
    "damp_auto_increment": 0.01,
    "static_groups": false,
    "true_sequential": true,
    "mse": 0.0,
    "gptaq": null,
    "act_group_aware": true,
    "failsafe": {
      "strategy": "rtn",
      "threshold": "0.5%",
      "smooth": {
        "type": "mad",
        "group_size_threshold": 128,
        "k": 2.75
      }
    },
    "offload_to_disk": true,
    "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
    "pack_impl": "cpu",
    "mock_quantization": false,
    "gc_mode": "interval",
    "wait_for_submodule_finalizers": false,
    "auto_forward_data_parallel": true,
    "hessian": {
      "chunk_size": null,
      "chunk_bytes": null,
      "staging_dtype": "float32"
    },
    "vram_strategy": "exclusive"
  },
  "sym": true,
  "format": "gptq"
}

Files in directory:
quant_log.csv
quantize_config.json
generation_config.json
config.json
Content of saved `generation_config.json`:
{
    "bos_token_id": 151643,
    "do_sample": true,
    "eos_token_id": 151643,
    "max_new_tokens": 2048,
    "transformers_version": "5.0.0"
}
Content of saved `config.json`:
{
    "architectures": [
        "Qwen2ForCausalLM"
    ],
    "attention_dropout": 0.0,
    "bos_token_id": 151643,
    "dtype": "bfloat16",
    "eos_token_id": 151643,
    "hidden_act": "silu",
    "hidden_size": 1536,
    "initializer_range": 0.02,
    "intermediate_size": 8960,
    "layer_types": [
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention",
        "full_attention"
    ],
    "max_position_embeddings": 131072,
    "max_window_layers": 28,
    "model_type": "qwen2",
    "num_attention_heads": 12,
    "num_hidden_layers": 28,
    "num_key_value_heads": 2,
    "pad_token_id": null,
    "quantization_config": {
        "bits": 4,
        "checkpoint_format": "gptq",
        "desc_act": false,
        "dynamic": {
            "-:.*self_attn\\.(q|k|v|o)_proj.*": {}
        },
        "format": "gptq",
        "group_size": 128,
        "lm_head": false,
        "meta": {
            "act_group_aware": true,
            "auto_forward_data_parallel": true,
            "damp_auto_increment": 0.01,
            "damp_percent": 0.05,
            "failsafe": {
                "smooth": {
                    "group_size_threshold": 128,
                    "k": 2.75,
                    "type": "mad"
                },
                "strategy": "rtn",
                "threshold": "0.5%"
            },
            "gc_mode": "interval",
            "gptaq": null,
            "hessian": {
                "chunk_bytes": null,
                "chunk_size": null,
                "staging_dtype": "float32"
            },
            "mock_quantization": false,
            "mse": 0.0,
            "offload_to_disk": true,
            "offload_to_disk_path": "./gptqmodel_offload/hqdpgrum-rkaakpxx/",
            "pack_impl": "cpu",
            "quantizer": [
                "gptqmodel:5.7.0"
            ],
            "static_groups": false,
            "true_sequential": true,
            "uri": "https://github.com/modelcloud/gptqmodel",
            "vram_strategy": "exclusive",
            "wait_for_submodule_finalizers": false
        },
        "pack_dtype": "int32",
        "quant_method": "gptq",
        "sym": true
    },
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
        "rope_theta": 1000000.0,
        "rope_type": "default"
    },
    "sliding_window": null,
    "tie_word_embeddings": true,
    "transformers_version": "5.0.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
}

INFO  Module: Sync model.embed_tokens <- from turtle (Embedding)

INFO  Module: Sync lm_head <- from turtle (Linear)

INFO  Module: Re-tied embedding weights on shell model after full sync

INFO  Module: Total synced modules: 2

INFO  Pre-Quantized model size: 2944.44MB, 2.88GB

INFO  Quantized model size: 1313.53MB, 1.28GB

INFO  Size difference: 1630.91MB, 1.59GB - 55.39%

INFO  | Pre-quant forward  | 56    | 17.535 | 10.422 | 583.631 | 41.2%  | model.layers.27:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Forward hook       | 43008 | 0.027  | 0.010  | 449.879 | 31.8%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process quant      | 168   | 3.442  | 0.937  | 157.370 | 11.1%  | model.layers.27.mlp.down_proj                     |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Submodule finalize | 168   | 0.873  | 0.460  | 77.274  | 5.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Post-quant replay  | 27    | 2.769  | 2.772  | 74.854  | 5.3%   | model.layers.26:subset2/2                         |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize pack      | 84    | 0.546  | 0.404  | 33.965  | 2.4%   | model.layers.27.mlp.up_proj [module.pack_block]   |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize create    | 84    | 0.287  | 0.252  | 21.185  | 1.5%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Finalize offload   | 84    | 0.017  | 0.120  | 10.092  | 0.7%   | model.layers.27.mlp.up_proj                       |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Model save         | 1     | 3.781  | 3.781  | 3.781   | 0.3%   | /content/artifacts/gptq_w4_g128/mlp_only_quant    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Capture inputs     | 1     | 2.197  | 2.197  | 2.197   | 0.2%   | cache_inputs:Qwen2DecoderLayer                    |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Turtle reload      | 5     | 0.427  | 0.432  | 2.159   | 0.2%   | auto:Qwen2DecoderLayer                            |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

INFO  | Process finalize   | 2     | 0.000  | 0.000  | 0.001   | 0.0%   | tp-pre-pad                                        |

INFO  +--------------------+-------+--------+--------+---------+--------+---------------------------------------------------+

2026-03-10 04:14:32,349 | INFO    | Quantization finished in 13:38
2026-03-10 04:16:27,992 | INFO    | Created zip: /content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant/mlp_only_quant_quantized_model.zip (1079.38 MB)

Quantized artifact ready.
{
  "variant": "mlp_only_quant",
  "base_model": "Qwen/Qwen2-1.5B",
  "quant": {
    "bits": 4,
    "group_size": 128,
    "desc_act": false
  },
  "dynamic_config": {
    "-:.*self_attn\\.(q|k|v|o)_proj.*": {}
  },
  "artifact_dir": "/content/artifacts/gptq_w4_g128/mlp_only_quant",
  "gptq_model_file": "model.safetensors",
  "quantization_elapsed_sec": 818.4876461029053,
  "model_size_gb": 1.2827,
  "bits_per_param": 6.6632,
  "created_at_unix": 1773116072.4020019
}

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,mlp_only_quant,GPTQ W4 g128,1.2827,None,6.6632,None,None,None

In [ ]:
def evaluate_perplexity_only(model, tokenizer, cfg):
    ppl_cfg = cfg['eval']['perplexity']
    logger.info(
        'Loading Perplexity dataset: %s / %s / %s | max_length=%d stride=%d max_eval_tokens=%d',
        ppl_cfg['dataset'],
        ppl_cfg['dataset_name'],
        ppl_cfg['split'],
        ppl_cfg['max_length'],
        ppl_cfg['stride'],
        ppl_cfg.get('max_eval_tokens', 131072),
    )
    ds = load_dataset(ppl_cfg['dataset'], ppl_cfg['dataset_name'], split=ppl_cfg['split'])
    text = '\n\n'.join(t for t in ds['text'] if t and t.strip())
    encodings = tokenizer(text, return_tensors='pt')
    seq_len = min(encodings.input_ids.size(1), ppl_cfg.get('max_eval_tokens', 131072))
    max_len = ppl_cfg['max_length']
    stride = ppl_cfg['stride']
    log_every = ppl_cfg.get('log_every', 25)

    nlls = []
    prev_end = 0
    start_time = time.time()
    peak_vram = 0.0
    windows = list(range(0, seq_len, stride))
    total_windows = max(1, len(windows))
    device = get_model_device(model)

    for idx, begin in enumerate(tqdm(windows, desc='Perplexity', unit='win'), start=1):
        end = min(begin + max_len, seq_len)
        input_ids = encodings.input_ids[:, begin:end].to(device)
        attention_mask = torch.ones_like(input_ids)
        target_ids = input_ids.clone()
        target_ids[:, :max(0, prev_end - begin)] = -100

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        with torch.no_grad():
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=target_ids)
            nlls.append(outputs.loss.detach().float())

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        prev_end = end
        if idx % log_every == 0 or end >= seq_len:
            elapsed = time.time() - start_time
            eta = (elapsed / idx) * (total_windows - idx) if idx else 0.0
            logger.info(
                'Perplexity progress %d/%d | elapsed=%s | eta=%s',
                idx,
                total_windows,
                format_seconds(elapsed),
                format_seconds(eta),
            )
        if end >= seq_len:
            break

    perplexity = math.exp(torch.stack(nlls).mean().item())
    elapsed = time.time() - start_time
    result = {
        'dataset': f"{ppl_cfg['dataset']}/{ppl_cfg['dataset_name']}",
        'split': ppl_cfg['split'],
        'max_length': max_len,
        'stride': stride,
        'num_tokens': int(seq_len),
        'num_windows': len(nlls),
        'perplexity': perplexity,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    save_json(result, RESULTS_DIR / 'perplexity_metrics.json')

    state = get_results_state()
    state['perplexity'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    logger.info(
        'Perplexity finished | ppl=%.4f | elapsed=%s | peak_vram_gb=%s',
        result['perplexity'],
        result['elapsed_hms'],
        result['peak_vram_gb'],
    )
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    return result


GSM_PROMPT = "Question: {question} Answer: Let's think step by step. "


def evaluate_gsm8k_only(model, tokenizer, cfg):
    gsm_cfg = cfg['eval']['gsm8k']
    n_shot = gsm_cfg['num_fewshot']
    num_samples = gsm_cfg['num_samples']
    max_new = gsm_cfg['max_new_tokens']
    log_every = gsm_cfg.get('log_every', 25)

    logger.info('Loading GSM8K: %d-shot, %d samples, max_new_tokens=%d', n_shot, num_samples, max_new)
    train_ds = load_dataset('openai/gsm8k', 'main', split='train').shuffle(seed=42)
    test_ds = load_dataset('openai/gsm8k', 'main', split='test').shuffle(seed=42).select(range(num_samples))
    exemplars = train_ds.select(range(n_shot))

    prefix = ''
    for ex in exemplars:
        prefix += GSM_PROMPT.format(question=ex['question']) + ex['answer'] + '\n\n'

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(test_ds)

    for idx, row in enumerate(tqdm(test_ds, desc='GSM8K', unit='q'), start=1):
        prompt = prefix + GSM_PROMPT.format(question=row['question'])

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new)
        pred = extract_numeric_answer(generated)
        gold = extract_numeric_answer(row['answer'])
        is_correct = pred is not None and gold is not None and abs(pred - gold) < 1e-3
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_value': pred,
            'gold_value': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('GSM8K', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'gsm8k',
        'num_fewshot': n_shot,
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'gsm8k_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'gsm8k_metrics.json')

    state = get_results_state()
    state['gsm8k'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    logger.info('GSM8K finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    return result


def format_arc_prompt(row):
    labels = row['choices']['label']
    texts = row['choices']['text']
    prompt = row['question'] + '\n'
    for lbl, txt in zip(labels, texts):
        prompt += f'{lbl}. {txt}\n'
    prompt += 'Answer:'
    return prompt


def evaluate_arc_only(model, tokenizer, cfg):
    arc_cfg = cfg['eval']['arc_challenge']
    num_samples = arc_cfg['num_samples']
    max_new = arc_cfg['max_new_tokens']
    log_every = arc_cfg.get('log_every', 50)

    logger.info('Loading ARC-Challenge: %d samples, max_new_tokens=%d', num_samples, max_new)
    ds = load_dataset('allenai/ai2_arc', 'ARC-Challenge', split='test').shuffle(seed=42).select(range(num_samples))

    rows = []
    correct = 0
    start_time = time.time()
    peak_vram = 0.0
    total = len(ds)

    for idx, row in enumerate(tqdm(ds, desc='ARC-Challenge', unit='q'), start=1):
        prompt = format_arc_prompt(row)

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()

        generated = generate_text(model, tokenizer, prompt, max_new_tokens=max_new).strip()
        pred = generated[:1].upper() if generated else None
        gold = row['answerKey'].strip().upper()
        is_correct = pred == gold
        correct += int(is_correct)

        if torch.cuda.is_available():
            peak_vram = max(peak_vram, torch.cuda.max_memory_allocated() / (1024 ** 3))

        rows.append({
            'index': idx - 1,
            'question': row['question'],
            'prediction_text': generated,
            'predicted_label': pred,
            'gold_label': gold,
            'correct': bool(is_correct),
        })

        if idx % log_every == 0 or idx == total:
            log_progress('ARC-Challenge', idx, total, start_time, correct)

    elapsed = time.time() - start_time
    result = {
        'dataset': 'arc_challenge',
        'num_samples': total,
        'max_new_tokens': max_new,
        'accuracy': correct / max(total, 1),
        'correct': correct,
        'elapsed_sec': elapsed,
        'elapsed_hms': format_seconds(elapsed),
        'peak_vram_gb': peak_vram if torch.cuda.is_available() else None,
    }

    pd.DataFrame(rows).to_csv(RESULTS_DIR / 'arc_challenge_predictions.csv', index=False)
    save_json(result, RESULTS_DIR / 'arc_challenge_metrics.json')

    state = get_results_state()
    state['arc_challenge'] = result
    save_results_state(state)
    summary = update_summary_table(state)

    results_zip = zip_directory(RESULTS_DIR, BUNDLE_DIR / 'full_quant_results_only.zip')
    state['results_zip'] = str(results_zip)
    save_results_state(state)

    logger.info('ARC-Challenge finished | acc=%.4f | elapsed=%s | peak_vram_gb=%s', result['accuracy'], result['elapsed_hms'], result['peak_vram_gb'])
    display(pd.DataFrame([result]))
    display(pd.DataFrame([summary]))
    print('Results zip:', results_zip)
    return result

In [ ]:
# Cell 2 — Evaluate Perplexity only
# Run this after the quantization cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    perplexity_result = evaluate_perplexity_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

`torch_dtype` is deprecated! Use `dtype` instead!

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/wtwpfhyg-qaghghla/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  The layer model.layers.0.self_attn.q_proj is not quantized.

INFO  The layer model.layers.0.self_attn.k_proj is not quantized.

INFO  The layer model.layers.0.self_attn.v_proj is not quantized.

INFO  The layer model.layers.0.self_attn.o_proj is not quantized.

INFO  The layer model.layers.1.self_attn.q_proj is not quantized.

INFO  The layer model.layers.1.self_attn.k_proj is not quantized.

INFO  The layer model.layers.1.self_attn.v_proj is not quantized.

INFO  The layer model.layers.1.self_attn.o_proj is not quantized.

INFO  The layer model.layers.2.self_attn.q_proj is not quantized.

INFO  The layer model.layers.2.self_attn.k_proj is not quantized.

INFO  The layer model.layers.2.self_attn.v_proj is not quantized.

INFO  The layer model.layers.2.self_attn.o_proj is not quantized.

INFO  The layer model.layers.3.self_attn.q_proj is not quantized.

INFO  The layer model.layers.3.self_attn.k_proj is not quantized.

INFO  The layer model.layers.3.self_attn.v_proj is not quantized.

INFO  The layer model.layers.3.self_attn.o_proj is not quantized.

INFO  The layer model.layers.4.self_attn.q_proj is not quantized.

INFO  The layer model.layers.4.self_attn.k_proj is not quantized.

INFO  The layer model.layers.4.self_attn.v_proj is not quantized.

INFO  The layer model.layers.4.self_attn.o_proj is not quantized.

INFO  The layer model.layers.5.self_attn.q_proj is not quantized.

INFO  The layer model.layers.5.self_attn.k_proj is not quantized.

INFO  The layer model.layers.5.self_attn.v_proj is not quantized.

INFO  The layer model.layers.5.self_attn.o_proj is not quantized.

INFO  The layer model.layers.6.self_attn.q_proj is not quantized.

INFO  The layer model.layers.6.self_attn.k_proj is not quantized.

INFO  The layer model.layers.6.self_attn.v_proj is not quantized.

INFO  The layer model.layers.6.self_attn.o_proj is not quantized.

INFO  The layer model.layers.7.self_attn.q_proj is not quantized.

INFO  The layer model.layers.7.self_attn.k_proj is not quantized.

INFO  The layer model.layers.7.self_attn.v_proj is not quantized.

INFO  The layer model.layers.7.self_attn.o_proj is not quantized.

INFO  The layer model.layers.8.self_attn.q_proj is not quantized.

INFO  The layer model.layers.8.self_attn.k_proj is not quantized.

INFO  The layer model.layers.8.self_attn.v_proj is not quantized.

INFO  The layer model.layers.8.self_attn.o_proj is not quantized.

INFO  The layer model.layers.9.self_attn.q_proj is not quantized.

INFO  The layer model.layers.9.self_attn.k_proj is not quantized.

INFO  The layer model.layers.9.self_attn.v_proj is not quantized.

INFO  The layer model.layers.9.self_attn.o_proj is not quantized.

INFO  The layer model.layers.10.self_attn.q_proj is not quantized.

INFO  The layer model.layers.10.self_attn.k_proj is not quantized.

INFO  The layer model.layers.10.self_attn.v_proj is not quantized.

INFO  The layer model.layers.10.self_attn.o_proj is not quantized.

INFO  The layer model.layers.11.self_attn.q_proj is not quantized.

INFO  The layer model.layers.11.self_attn.k_proj is not quantized.

INFO  The layer model.layers.11.self_attn.v_proj is not quantized.

INFO  The layer model.layers.11.self_attn.o_proj is not quantized.

INFO  The layer model.layers.12.self_attn.q_proj is not quantized.

INFO  The layer model.layers.12.self_attn.k_proj is not quantized.

INFO  The layer model.layers.12.self_attn.v_proj is not quantized.

INFO  The layer model.layers.12.self_attn.o_proj is not quantized.

INFO  The layer model.layers.13.self_attn.q_proj is not quantized.

INFO  The layer model.layers.13.self_attn.k_proj is not quantized.

INFO  The layer model.layers.13.self_attn.v_proj is not quantized.

INFO  The layer model.layers.13.self_attn.o_proj is not quantized.

INFO  The layer model.layers.14.self_attn.q_proj is not quantized.

INFO  The layer model.layers.14.self_attn.k_proj is not quantized.

INFO  The layer model.layers.14.self_attn.v_proj is not quantized.

INFO  The layer model.layers.14.self_attn.o_proj is not quantized.

INFO  The layer model.layers.15.self_attn.q_proj is not quantized.

INFO  The layer model.layers.15.self_attn.k_proj is not quantized.

INFO  The layer model.layers.15.self_attn.v_proj is not quantized.

INFO  The layer model.layers.15.self_attn.o_proj is not quantized.

INFO  The layer model.layers.16.self_attn.q_proj is not quantized.

INFO  The layer model.layers.16.self_attn.k_proj is not quantized.

INFO  The layer model.layers.16.self_attn.v_proj is not quantized.

INFO  The layer model.layers.16.self_attn.o_proj is not quantized.

INFO  The layer model.layers.17.self_attn.q_proj is not quantized.

INFO  The layer model.layers.17.self_attn.k_proj is not quantized.

INFO  The layer model.layers.17.self_attn.v_proj is not quantized.

INFO  The layer model.layers.17.self_attn.o_proj is not quantized.

INFO  The layer model.layers.18.self_attn.q_proj is not quantized.

INFO  The layer model.layers.18.self_attn.k_proj is not quantized.

INFO  The layer model.layers.18.self_attn.v_proj is not quantized.

INFO  The layer model.layers.18.self_attn.o_proj is not quantized.

INFO  The layer model.layers.19.self_attn.q_proj is not quantized.

INFO  The layer model.layers.19.self_attn.k_proj is not quantized.

INFO  The layer model.layers.19.self_attn.v_proj is not quantized.

INFO  The layer model.layers.19.self_attn.o_proj is not quantized.

INFO  The layer model.layers.20.self_attn.q_proj is not quantized.

INFO  The layer model.layers.20.self_attn.k_proj is not quantized.

INFO  The layer model.layers.20.self_attn.v_proj is not quantized.

INFO  The layer model.layers.20.self_attn.o_proj is not quantized.

INFO  The layer model.layers.21.self_attn.q_proj is not quantized.

INFO  The layer model.layers.21.self_attn.k_proj is not quantized.

INFO  The layer model.layers.21.self_attn.v_proj is not quantized.

INFO  The layer model.layers.21.self_attn.o_proj is not quantized.

INFO  The layer model.layers.22.self_attn.q_proj is not quantized.

INFO  The layer model.layers.22.self_attn.k_proj is not quantized.

INFO  The layer model.layers.22.self_attn.v_proj is not quantized.

INFO  The layer model.layers.22.self_attn.o_proj is not quantized.

INFO  The layer model.layers.23.self_attn.q_proj is not quantized.

INFO  The layer model.layers.23.self_attn.k_proj is not quantized.

INFO  The layer model.layers.23.self_attn.v_proj is not quantized.

INFO  The layer model.layers.23.self_attn.o_proj is not quantized.

INFO  The layer model.layers.24.self_attn.q_proj is not quantized.

INFO  The layer model.layers.24.self_attn.k_proj is not quantized.

INFO  The layer model.layers.24.self_attn.v_proj is not quantized.

INFO  The layer model.layers.24.self_attn.o_proj is not quantized.

INFO  The layer model.layers.25.self_attn.q_proj is not quantized.

INFO  The layer model.layers.25.self_attn.k_proj is not quantized.

INFO  The layer model.layers.25.self_attn.v_proj is not quantized.

INFO  The layer model.layers.25.self_attn.o_proj is not quantized.

INFO  The layer model.layers.26.self_attn.q_proj is not quantized.

INFO  The layer model.layers.26.self_attn.k_proj is not quantized.

INFO  The layer model.layers.26.self_attn.v_proj is not quantized.

INFO  The layer model.layers.26.self_attn.o_proj is not quantized.

INFO  The layer model.layers.27.self_attn.q_proj is not quantized.

INFO  The layer model.layers.27.self_attn.k_proj is not quantized.

INFO  The layer model.layers.27.self_attn.v_proj is not quantized.

INFO  The layer model.layers.27.self_attn.o_proj is not quantized.

2026-03-10 04:21:21,223 | INFO    | HTTP Request: GET https://huggingface.co/api/models/kernels-community/quantization_gptq/revision/main "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:21,460 | INFO    | HTTP Request: GET https://huggingface.co/api/models/kernels-community/quantization-gptq/revision/main "HTTP/1.1 200 OK"

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 0 files: 0it [00:00, ?it/s]

Failed to load CPU gemm_4bit kernel: Cannot install kernel from repo kernels-community/quantization_gptq (revision: main). Use fallback path.                         Please make sure you already `pip install kernels` and the kernels >= 0.11.1

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-10 04:21:21,689 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Format: Converting GPTQ v1 to v2

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Optimize: `TritonV2QuantLinear` compilation triggered.

INFO  gc.collect() reclaimed 173 objects in 0.306s

2026-03-10 04:21:25,904 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

2026-03-10 04:21:25,923 | INFO    | Loading Perplexity dataset: wikitext / wikitext-2-raw-v1 / test | max_length=2048 stride=1024 max_eval_tokens=131072
2026-03-10 04:21:26,161 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:26,387 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:26,393 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/Salesforce/wikitext/b08601e04326c79dfdd32d625aee71d232d685c3/README.md "HTTP/1.1 200 OK"
2026-03-10 04:21:26,627 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:26,870 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/wikitext.py "HTTP/1.1 404 Not Found"
2026-03-10 04:21:27,568 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/wikitext/wikitext.py "HTTP/1.1 200 OK"
2026-03-10 04:21:27,815 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:28,050 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-10 04:21:28,313 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=wikitext "HTTP/1.1 404 Not Found"
2026-03-10 04:21:28,544 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:21:28,787 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/Salesforce/wikitext/resolve/b08601e04326c79dfdd32d625aee71d232d685c3/dataset_infos.json "HTTP/1.1 404 Not Found"
Token indices sequence length is longer than the specified maximum sequence length for this model (298938 > 32768). Running this sequence through the model will result in indexing errors

Perplexity:   0%|          | 0/128 [00:00<?, ?win/s]

2026-03-10 04:21:37,620 | INFO    | Perplexity progress 25/128 | elapsed=0:07 | eta=0:31
2026-03-10 04:21:42,459 | INFO    | Perplexity progress 50/128 | elapsed=0:12 | eta=0:19
2026-03-10 04:21:47,325 | INFO    | Perplexity progress 75/128 | elapsed=0:17 | eta=0:12
2026-03-10 04:21:52,206 | INFO    | Perplexity progress 100/128 | elapsed=0:22 | eta=0:06
2026-03-10 04:21:57,097 | INFO    | Perplexity progress 125/128 | elapsed=0:27 | eta=0:00
2026-03-10 04:21:57,489 | INFO    | Perplexity progress 127/128 | elapsed=0:27 | eta=0:00
2026-03-10 04:21:57,631 | INFO    | Perplexity finished | ppl=8.5767 | elapsed=0:27 | peak_vram_gb=7.97538423538208

,dataset,split,max_length,stride,num_tokens,num_windows,perplexity,elapsed_sec,elapsed_hms,peak_vram_gb
0,wikitext/wikitext-2-raw-v1,test,2048,1024,131072,127,8.576692,27.546925,0:27,7.975384

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,mlp_only_quant,GPTQ W4 g128,1.2827,7.9754,6.6632,8.576692,None,None

In [ ]:

# Cell 3 — Evaluate on GSM8K only
# Run this after the Perplexity cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    gsm8k_result = evaluate_gsm8k_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

In [ ]:

# Cell 4 — Evaluate on ARC-Challenge only and finalize the summary/results zip
# Run this after the GSM8K cell.
if not ARTIFACT_DIR.exists():
    raise FileNotFoundError(f'Quantized artifact not found: {ARTIFACT_DIR}')

model, tokenizer = load_quantized_model_and_tokenizer(ARTIFACT_DIR)
try:
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
finally:
    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

from_quantized: adapter: None

INFO  Loader: Auto dtype (native bfloat16): `torch.bfloat16`

INFO  QuantizeConfig: offload_to_disk_path auto set to `./gptqmodel_offload/pnnvijib-iqbxrhpb/`

INFO  Estimated Quantization BPW (bits per weight): 4.2875 bpw, based on [bits: 4, group_size: 128]

INFO  The layer model.layers.0.self_attn.q_proj is not quantized.

INFO  The layer model.layers.0.self_attn.k_proj is not quantized.

INFO  The layer model.layers.0.self_attn.v_proj is not quantized.

INFO  The layer model.layers.0.self_attn.o_proj is not quantized.

INFO  The layer model.layers.1.self_attn.q_proj is not quantized.

INFO  The layer model.layers.1.self_attn.k_proj is not quantized.

INFO  The layer model.layers.1.self_attn.v_proj is not quantized.

INFO  The layer model.layers.1.self_attn.o_proj is not quantized.

INFO  The layer model.layers.2.self_attn.q_proj is not quantized.

INFO  The layer model.layers.2.self_attn.k_proj is not quantized.

INFO  The layer model.layers.2.self_attn.v_proj is not quantized.

INFO  The layer model.layers.2.self_attn.o_proj is not quantized.

INFO  The layer model.layers.3.self_attn.q_proj is not quantized.

INFO  The layer model.layers.3.self_attn.k_proj is not quantized.

INFO  The layer model.layers.3.self_attn.v_proj is not quantized.

INFO  The layer model.layers.3.self_attn.o_proj is not quantized.

INFO  The layer model.layers.4.self_attn.q_proj is not quantized.

INFO  The layer model.layers.4.self_attn.k_proj is not quantized.

INFO  The layer model.layers.4.self_attn.v_proj is not quantized.

INFO  The layer model.layers.4.self_attn.o_proj is not quantized.

INFO  The layer model.layers.5.self_attn.q_proj is not quantized.

INFO  The layer model.layers.5.self_attn.k_proj is not quantized.

INFO  The layer model.layers.5.self_attn.v_proj is not quantized.

INFO  The layer model.layers.5.self_attn.o_proj is not quantized.

INFO  The layer model.layers.6.self_attn.q_proj is not quantized.

INFO  The layer model.layers.6.self_attn.k_proj is not quantized.

INFO  The layer model.layers.6.self_attn.v_proj is not quantized.

INFO  The layer model.layers.6.self_attn.o_proj is not quantized.

INFO  The layer model.layers.7.self_attn.q_proj is not quantized.

INFO  The layer model.layers.7.self_attn.k_proj is not quantized.

INFO  The layer model.layers.7.self_attn.v_proj is not quantized.

INFO  The layer model.layers.7.self_attn.o_proj is not quantized.

INFO  The layer model.layers.8.self_attn.q_proj is not quantized.

INFO  The layer model.layers.8.self_attn.k_proj is not quantized.

INFO  The layer model.layers.8.self_attn.v_proj is not quantized.

INFO  The layer model.layers.8.self_attn.o_proj is not quantized.

INFO  The layer model.layers.9.self_attn.q_proj is not quantized.

INFO  The layer model.layers.9.self_attn.k_proj is not quantized.

INFO  The layer model.layers.9.self_attn.v_proj is not quantized.

INFO  The layer model.layers.9.self_attn.o_proj is not quantized.

INFO  The layer model.layers.10.self_attn.q_proj is not quantized.

INFO  The layer model.layers.10.self_attn.k_proj is not quantized.

INFO  The layer model.layers.10.self_attn.v_proj is not quantized.

INFO  The layer model.layers.10.self_attn.o_proj is not quantized.

INFO  The layer model.layers.11.self_attn.q_proj is not quantized.

INFO  The layer model.layers.11.self_attn.k_proj is not quantized.

INFO  The layer model.layers.11.self_attn.v_proj is not quantized.

INFO  The layer model.layers.11.self_attn.o_proj is not quantized.

INFO  The layer model.layers.12.self_attn.q_proj is not quantized.

INFO  The layer model.layers.12.self_attn.k_proj is not quantized.

INFO  The layer model.layers.12.self_attn.v_proj is not quantized.

INFO  The layer model.layers.12.self_attn.o_proj is not quantized.

INFO  The layer model.layers.13.self_attn.q_proj is not quantized.

INFO  The layer model.layers.13.self_attn.k_proj is not quantized.

INFO  The layer model.layers.13.self_attn.v_proj is not quantized.

INFO  The layer model.layers.13.self_attn.o_proj is not quantized.

INFO  The layer model.layers.14.self_attn.q_proj is not quantized.

INFO  The layer model.layers.14.self_attn.k_proj is not quantized.

INFO  The layer model.layers.14.self_attn.v_proj is not quantized.

INFO  The layer model.layers.14.self_attn.o_proj is not quantized.

INFO  The layer model.layers.15.self_attn.q_proj is not quantized.

INFO  The layer model.layers.15.self_attn.k_proj is not quantized.

INFO  The layer model.layers.15.self_attn.v_proj is not quantized.

INFO  The layer model.layers.15.self_attn.o_proj is not quantized.

INFO  The layer model.layers.16.self_attn.q_proj is not quantized.

INFO  The layer model.layers.16.self_attn.k_proj is not quantized.

INFO  The layer model.layers.16.self_attn.v_proj is not quantized.

INFO  The layer model.layers.16.self_attn.o_proj is not quantized.

INFO  The layer model.layers.17.self_attn.q_proj is not quantized.

INFO  The layer model.layers.17.self_attn.k_proj is not quantized.

INFO  The layer model.layers.17.self_attn.v_proj is not quantized.

INFO  The layer model.layers.17.self_attn.o_proj is not quantized.

INFO  The layer model.layers.18.self_attn.q_proj is not quantized.

INFO  The layer model.layers.18.self_attn.k_proj is not quantized.

INFO  The layer model.layers.18.self_attn.v_proj is not quantized.

INFO  The layer model.layers.18.self_attn.o_proj is not quantized.

INFO  The layer model.layers.19.self_attn.q_proj is not quantized.

INFO  The layer model.layers.19.self_attn.k_proj is not quantized.

INFO  The layer model.layers.19.self_attn.v_proj is not quantized.

INFO  The layer model.layers.19.self_attn.o_proj is not quantized.

INFO  The layer model.layers.20.self_attn.q_proj is not quantized.

INFO  The layer model.layers.20.self_attn.k_proj is not quantized.

INFO  The layer model.layers.20.self_attn.v_proj is not quantized.

INFO  The layer model.layers.20.self_attn.o_proj is not quantized.

INFO  The layer model.layers.21.self_attn.q_proj is not quantized.

INFO  The layer model.layers.21.self_attn.k_proj is not quantized.

INFO  The layer model.layers.21.self_attn.v_proj is not quantized.

INFO  The layer model.layers.21.self_attn.o_proj is not quantized.

INFO  The layer model.layers.22.self_attn.q_proj is not quantized.

INFO  The layer model.layers.22.self_attn.k_proj is not quantized.

INFO  The layer model.layers.22.self_attn.v_proj is not quantized.

INFO  The layer model.layers.22.self_attn.o_proj is not quantized.

INFO  The layer model.layers.23.self_attn.q_proj is not quantized.

INFO  The layer model.layers.23.self_attn.k_proj is not quantized.

INFO  The layer model.layers.23.self_attn.v_proj is not quantized.

INFO  The layer model.layers.23.self_attn.o_proj is not quantized.

INFO  The layer model.layers.24.self_attn.q_proj is not quantized.

INFO  The layer model.layers.24.self_attn.k_proj is not quantized.

INFO  The layer model.layers.24.self_attn.v_proj is not quantized.

INFO  The layer model.layers.24.self_attn.o_proj is not quantized.

INFO  The layer model.layers.25.self_attn.q_proj is not quantized.

INFO  The layer model.layers.25.self_attn.k_proj is not quantized.

INFO  The layer model.layers.25.self_attn.v_proj is not quantized.

INFO  The layer model.layers.25.self_attn.o_proj is not quantized.

INFO  The layer model.layers.26.self_attn.q_proj is not quantized.

INFO  The layer model.layers.26.self_attn.k_proj is not quantized.

INFO  The layer model.layers.26.self_attn.v_proj is not quantized.

INFO  The layer model.layers.26.self_attn.o_proj is not quantized.

INFO  The layer model.layers.27.self_attn.q_proj is not quantized.

INFO  The layer model.layers.27.self_attn.k_proj is not quantized.

INFO  The layer model.layers.27.self_attn.v_proj is not quantized.

INFO  The layer model.layers.27.self_attn.o_proj is not quantized.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: Auto-selection: adding candidate `TorchQuantLinear`

INFO  Kernel: candidates -> `[TritonV2QuantLinear, TorchQuantLinear]`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  Loader: device = DEVICE.CUDA

INFO  Loader: Built map across 1 GPU(s), 32 entries. First 8: [('model.embed_tokens', 'cuda:0'), ('model.layers.0', 'cuda:0'), ('model.layers.1', 'cuda:0'), ('model.layers.2', 'cuda:0'), ('model.layers.3', 'cuda:0'), ('model.layers.4', 'cuda:0'), ('model.layers.5', 'cuda:0'), ('model.layers.6', 'cuda:0')]

INFO  Loader: device_map = {'model.embed_tokens': 'cuda:0', 'model.layers.0': 'cuda:0', 'model.layers.1': 'cuda:0', 'model.layers.2': 'cuda:0', 'model.layers.3': 'cuda:0', 'model.layers.4': 'cuda:0', 'model.layers.5': 'cuda:0', 'model.layers.6': 'cuda:0', 'model.layers.7': 'cuda:0', 'model.layers.8': 'cuda:0', 'model.layers.9': 'cuda:0', 'model.layers.10': 'cuda:0', 'model.layers.11': 'cuda:0', 'model.layers.12': 'cuda:0', 'model.layers.13': 'cuda:0', 'model.layers.14': 'cuda:0', 'model.layers.15': 'cuda:0', 'model.layers.16': 'cuda:0', 'model.layers.17': 'cuda:0', 'model.layers.18': 'cuda:0', 'model.layers.19': 'cuda:0', 'model.layers.20': 'cuda:0', 'model.layers.21': 'cuda:0', 'model.layers.22': 'cuda:0', 'model.layers.23': 'cuda:0', 'model.layers.24': 'cuda:0', 'model.layers.25': 'cuda:0', 'model.layers.26': 'cuda:0', 'model.layers.27': 'cuda:0', 'lm_head': 'cuda:0', 'model.norm': 'cuda:0', 'model.rotary_emb': 'cuda:0'}

2026-03-10 04:36:59,642 | WARNING | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.

INFO  Format: Converting `checkpoint_format` from `FORMAT.GPTQ` to internal `FORMAT.GPTQ_V2`.

INFO  Kernel: Auto-selection: adding candidate `TritonV2QuantLinear`

INFO  Kernel: selected -> `TritonV2QuantLinear`.

INFO  gc.collect() reclaimed 65 objects in 0.327s

2026-03-10 04:37:01,073 | INFO    | Tokenicer: Auto fixed pad_token_id=151643 (token='<|endoftext|>').

INFO  Model: Loaded `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151643,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": true
}

INFO  Model: Auto-fixed `generation_config` mismatch between model and `generation_config.json`.

INFO  Model: Updated `generation_config`: GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 2048
}

INFO  Kernel: loaded -> `[TritonV2QuantLinear]`

2026-03-10 04:37:01,094 | INFO    | Loading ARC-Challenge: 500 samples, max_new_tokens=5
2026-03-10 04:37:01,332 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-03-10 04:37:01,338 | INFO    | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/allenai/ai2_arc/210d026faf9955653af8916fad021475a3f00453/README.md "HTTP/1.1 200 OK"
2026-03-10 04:37:01,563 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-10 04:37:02,226 | INFO    | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/allenai/ai2_arc/allenai/ai2_arc.py "HTTP/1.1 404 Not Found"
2026-03-10 04:37:02,472 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-03-10 04:37:02,735 | INFO    | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=allenai/ai2_arc "HTTP/1.1 200 OK"
2026-03-10 04:37:02,984 | INFO    | HTTP Request: HEAD https://huggingface.co/datasets/allenai/ai2_arc/resolve/210d026faf9955653af8916fad021475a3f00453/dataset_infos.json "HTTP/1.1 404 Not Found"

ARC-Challenge:   0%|          | 0/500 [00:00<?, ?q/s]

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1801/1162075249.py", line 8, in <cell line: 0>
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
  File "/tmp/ipykernel_1801/2515946732.py", line 221, in evaluate_arc_only
    log_progress('ARC-Challenge', idx, total, start_time, correct)
  File "/tmp/ipykernel_1801/1863022896.py", line 337, in log_progress
    logger.info(
Message: '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item'
Arguments: ('ARC-Challenge', 50, 500, 0.56, '0:13', '1:58', '1:58', 0.26317731380462644)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1801/1162075249.py", line 8, in <cell line: 0>
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
  File "/tmp/ipykernel_1801/2515946732.py", line 221, in evaluate_arc_only
    log_progress('ARC-Challenge', idx, total, start_time, correct)
  File "/tmp/ipykernel_1801/1863022896.py", line 337, in log_progress
    logger.info(
Message: '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item'
Arguments: ('ARC-Challenge', 100, 500, 0.62, '0:26', '1:45', '1:45', 0.2625190472602844)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1801/1162075249.py", line 8, in <cell line: 0>
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
  File "/tmp/ipykernel_1801/2515946732.py", line 221, in evaluate_arc_only
    log_progress('ARC-Challenge', idx, total, start_time, correct)
  File "/tmp/ipykernel_1801/1863022896.py", line 337, in log_progress
    logger.info(
Message: '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item'
Arguments: ('ARC-Challenge', 150, 500, 0.64, '0:39', '1:31', '1:31', 0.2626370127995809)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1801/1162075249.py", line 8, in <cell line: 0>
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
  File "/tmp/ipykernel_1801/2515946732.py", line 221, in evaluate_arc_only
    log_progress('ARC-Challenge', idx, total, start_time, correct)
  File "/tmp/ipykernel_1801/1863022896.py", line 337, in log_progress
    logger.info(
Message: '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item'
Arguments: ('ARC-Challenge', 200, 500, 0.625, '0:52', '1:18', '1:18', 0.2622891843318939)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1801/1162075249.py", line 8, in <cell line: 0>
    arc_result = evaluate_arc_only(model, tokenizer, cfg)
  File "/tmp/ipykernel_1801/2515946732.py", line 221, in evaluate_arc_only
    log_progress('ARC-Challenge', idx, total, start_time, correct)
  File "/tmp/ipykernel_1801/1863022896.py", line 337, in log_progress
    logger.info(
Message: '%s | %d/%d | acc=%.4f | elapsed=%s | eta=%s | %.2fs/item'
Arguments: ('ARC-Challenge', 250, 500, 0.652, '1:05', '1:05', '1:05', 0.2622261743545532)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not str
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()

,dataset,num_samples,max_new_tokens,accuracy,correct,elapsed_sec,elapsed_hms,peak_vram_gb
0,arc_challenge,500,5,0.648,324,131.28405,2:11,5.705068

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,mlp_only_quant,GPTQ W4 g128,1.2827,7.9754,6.6632,8.576692,None,0.648

Results zip: /content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant/full_quant_results_only.zip

In [15]:
state = get_results_state()
summary = update_summary_table(state)
print(json.dumps(state, indent=2))
display(pd.DataFrame([summary]))
print('''
Saved files under results:''')
for p in sorted(RESULTS_DIR.glob('*')):
    print('-', p.name)
print('''
Saved bundles:''')
for p in sorted(BUNDLE_DIR.glob('*')):
    print('-', p.name)

{
  "quantization": {
    "variant": "mlp_only_quant",
    "base_model": "Qwen/Qwen2-1.5B",
    "quant": {
      "bits": 4,
      "group_size": 128,
      "desc_act": false
    },
    "dynamic_config": {
      "-:.*self_attn\\.(q|k|v|o)_proj.*": {}
    },
    "artifact_dir": "/content/artifacts/gptq_w4_g128/mlp_only_quant",
    "gptq_model_file": "model.safetensors",
    "quantization_elapsed_sec": 818.4876461029053,
    "model_size_gb": 1.2827,
    "bits_per_param": 6.6632,
    "created_at_unix": 1773116072.4020019,
    "zip_path": "/content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant/mlp_only_quant_quantized_model.zip"
  },
  "perplexity": {
    "dataset": "wikitext/wikitext-2-raw-v1",
    "split": "test",
    "max_length": 2048,
    "stride": 1024,
    "num_tokens": 131072,
    "num_windows": 127,
    "perplexity": 8.576692317577685,
    "elapsed_sec": 27.54692506790161,
    "elapsed_hms": "0:27",
    "peak_vram_gb": 7.97538423538208
  },
  "arc_challenge": {
    "dataset": "arc_challenge",
    "num_samples": 500,
    "max_new_tokens": 5,
    "accuracy": 0.648,
    "correct": 324,
    "elapsed_sec": 131.2840497493744,
    "elapsed_hms": "2:11",
    "peak_vram_gb": 5.7050676345825195
  },
  "results_zip": "/content/zip_bundles/gptq_w4_g128_mlp_only_quant/mlp_only_quant/full_quant_results_only.zip"
}

,variant,compression,model_size_gb,peak_vram_gb,bits_per_param,perplexity,gsm8k_accuracy,arc_accuracy
0,mlp_only_quant,GPTQ W4 g128,1.2827,7.9754,6.6632,8.576692,None,0.648

Saved files under results:
- arc_challenge_metrics.json
- arc_challenge_predictions.csv
- perplexity_metrics.json
- quantization_manifest.json
- state.json
- summary.csv
- summary.json

Saved bundles:
- full_quant_results_only.zip
- mlp_only_quant_quantized_model.zip